### ISSUE TITLE
"dependencies exceed the version found"

### ISSUE THREAD

**Issue by Ribesg** [ben-manes/gradle-versions-plugin#100]
I have this little problem with the great [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger).
The latest version is 1.1.4, and my project compiles with it. But `dependencyUpdates` says the latest available version is 1.1.2.

I discovered that ShortcutBadger's latest version, 1.1.4,  is available on [Maven Central](http://repo1.maven.org/maven2/me/leolin/ShortcutBadger/) but [not on Bintray](https://bintray.com/leolin310148/maven/me.leolin%3AShortcutBadger/view). I guess that the gradle-versions-plugin doesn't try all available sources, and somehow jcenter is the first one tried?

This is not a big problem, but things like that happen. A project can be hosted on central and move to jcenter later. I thought jcenter was a superset of central, but it clearly isn't.

**Comment by ben-manes** [comment]
It tries to use all the repositories in the configuration that the dependency is attached to. We used to aggregate all repositories throughout the project, but ran into Gradle bugs.

So it should query all the repositories for the search. If you can provide a sample, then I can give it a whirl.

**Comment by Ribesg** [comment]
Uh... I had `mavenCentral()` called in my main `build.gradle`'s `buildscript`'s `repositories` and my app `build.gradle`'s `buildscript`'s `repositories`... But not in my main `build.gradle`'s `allprojects`'s `repositories`.

So it does work, it was just not looking where I expected it to look for it, Gradle sucks and I don't even know why I need to specify all the repositories 3 times.

Unless you can make it so that it looks into repositories defines elsewhere, there's nothing to do I guess.
