### ISSUE TITLE
Classpath dependencies are not shows

### ISSUE THREAD

**Issue by WonderCsabo** [ben-manes/gradle-versions-plugin#102]
For some reason, `classpath` aka `buildScript` dependency updates are not shown in the report.

**Comment by ben-manes** [comment]
They should be. Please provide a sample demonstrating the problem.

**Comment by WonderCsabo** [comment]
It doesn't work in my android project. It will try to create an example in the next couple days. Thanks!

**Comment by ben-manes** [comment]
It works for my projects, so perhaps you are running it on a sub-project and not the root?

**Comment by WonderCsabo** [comment]
I am running from the root, but the plugin is applied in a subproject. I will check it tomorrow as I am AFK now. Thanks for the hint!

**Comment by WonderCsabo** [comment]
Sorry for the delay @ben-manes . The problem was indeed that i applied the plugin on the sub-project, and not on the root. I changed it and not everything works as expected. Thanks!
