### ISSUE TITLE
Add to Gradle plugins

### ISSUE THREAD

**Issue by jaredsburrows** [ben-manes/gradle-versions-plugin#108]
So we can use new plugins id:
```
plugins {
    id 'com.github.ben-manes.versions' version '0.12.0'
}
```

**Comment by ben-manes** [comment]
Pardon? It should be possible per the [plugin portal](https://plugins.gradle.org/plugin/com.github.ben-manes.versions).

**Comment by jaredsburrows** [comment]
@ben-manes Hey, I am sorry. I just checked, I must have misspelled something. You mind if I add this to the README.md?

**Comment by ben-manes** [comment]
Sure, you can convert the example to the new syntax. I don't think we need to show the Gradle 1.x anymore with 3.x in beta.

**Comment by ben-manes** [comment]
Thanks!

**Comment by jaredsburrows** [comment]
Thank you!
