### ISSUE TITLE
Add option to check for latest Gradle version

### ISSUE THREAD

**Issue by jaredsburrows** [ben-manes/gradle-versions-plugin#110]
@ben-manes Could we add support to check the latest version of Gradle from the services.gradle.org/distributions?

`gradlew dependencyUpdates` -> Show latest deps
`gradlew gradleUpdate` -> Show latest gradle

**Comment by ben-manes** [comment]
Yep, see #76 where you asked for this and that was my answer =)

I'm happy to take contributions as I'm not actively working on any of the feature requests.

**Comment by jaredsburrows** [comment]
@ben-manes Haha! Im so sorry. I just thought of this again. Thanks for the fast reply.
