### ISSUE TITLE
Allow to exclude repo 

### ISSUE THREAD

**Issue by cypressious** [ben-manes/gradle-versions-plugin#116]
In my project I'm using the `http://repository.jetbrains.com/all` repo for the [Spek](https://github.com/JetBrains/spek) dependency. When executing the `dependencyUpdates` task, it takes a lot of time because the aforementioned repo containes a lot of snapshots for my dependencies and is really slow in comparison to maven or bintray. 

My request is to add a possibility to exclude a given repo from the update checks.

**Comment by ben-manes** [comment]
#98 shows how to add repositories in a `doFirst` block. Perhaps you can remove one similarly? Unfortunately `RepositoryHandler` is buggy, so I try to avoid manipulating the repository list to avoid surprising behavior.

**Comment by cypressious** [comment]
Good tip. I managed to do it like this:

```groovy
tasks.dependencyUpdates.doFirst {
    project.repositories.remove(project.repositories.find {
        it instanceof MavenArtifactRepository && it.url.toString() == 'http://repository.jetbrains.com/all'
    })
}
```

**Comment by ben-manes** [comment]
If you name the repository then you might be able to remove it slightly more succinctly.

Glad it worked.

**Comment by cypressious** [comment]
Cool, even better:

```groovy
//the repo definition
repositories {
    //...
    maven { url 'http://repository.jetbrains.com/all'; name 'jetbrains' }
}


tasks.dependencyUpdates.doFirst {
    project.repositories.removeAll {
        it instanceof MavenArtifactRepository && it.name == 'jetbrains'
    }
}

```

**Comment by ben-manes** [comment]
Since the name is unique, you can drop the `instanceof` too. :)

**Comment by cypressious** [comment]
Awesome, thanks again. Final code:

```groovy
//the repo definition
repositories {
    //...
    maven { url 'http://repository.jetbrains.com/all'; name 'jetbrains' }
}


tasks.dependencyUpdates.doFirst {
    project.repositories.removeAll { it.name == 'jetbrains' }
}

```
