### ISSUE TITLE
Being able to see the current version when doing component selection

### ISSUE THREAD

**Issue by jonasb** [ben-manes/gradle-versions-plugin#117]
As a general rule I'd like to avoid release candidates. But if I already am using e.g. a `beta` version of one dependency, I'm interested in knowing if there are newer `beta` versions. I couldn't figure out how to do that (other than check for specific groups/modules, but I want a generic solution).

What about adding `ComponentSelection.getCurrent()` which returns the `ModuleComponentIdentifier` for the currently used dependency?

**Comment by ben-manes** [comment]
That's a bit out of our control, right? You're requesting a change to Gradle's APIs, so it seems like a valid improvement to bring up on their forum.

If you centrally define your dependencies ([example](https://github.com/ben-manes/caffeine/blob/master/gradle/dependencies.gradle)) then you could probably query the mapping. E.g. if the update would be rejected but the current one would be to, then allow. So in a sense this is generic if you follow a convention of a central definition.

**Comment by ben-manes** [comment]
Closing due to lack of feedback and appears to be something we can change. Please reopen if you'd like to discuss.
