### ISSUE TITLE
Unexpected version of glide recommended

### ISSUE THREAD

**Issue by kroikie** [ben-manes/gradle-versions-plugin#119]
When using:

    ./gradlew dependencyUpdates -Drevision=integration

I am getting the report:

    The following dependencies exceed the version found at the integration revision level:
     - com.github.bumptech.glide:glide [3.7.0 <- 3.6.1]

Using the dependency:

    compile 'com.github.bumptech.glide:glide:3.7.0'

when I use the 3.6.1 version of the dependency, 3.7.0 is not reported as a new version.

I'm not sure if this is an issue with the gradle-versions-plugin or an issue with the way that the glide versions are defined. Any ideas?

**Comment by ben-manes** [comment]
Please add `mavenCentral()` to your repository listings.

JCenter appears to be evaluating with this [repository](https://bintray.com/sam-a-judd/maven/com.github.bumptech.glide%3Aglide) which only goes up to `3.6.1`. On Central the latest version in `maven-metadata.xml` is `3.7.0` so a query to that repository gives the latest information.

In JCenter the owner has to "unlink" their repository to have it correctly sync with central. At least that was what JCenter did with my Caffeine project when they contacted me about users unable to download later versions. When you state that you "own" the dependency (e.g. to see stats) they unexpectedly stop tracking Central and require that you to switch to publishing through them instead. That wasn't obvious to me so I relinquished ownership as requested, and I presume the Glide team made the same mistake.

**Comment by ben-manes** [comment]
@sjudd please update your repository so that other Glide users don't run into this quirk.
