### ISSUE TITLE
Add JCenter as the source

### ISSUE THREAD

**Issue by MisterY** [ben-manes/gradle-versions-plugin#120]
Hi,

Thanks a lot for the useful plugin!
I've recently had an [issue](https://github.com/spacecowboy/NoNonsense-FilePicker/issues/117) where an old version of a library is listed as the latest. It turns out that the library is being deployed to JCenter, while Maven Central still contains only the old versions.
Would it be possible to add support for other Maven repositories as the source?

**Comment by ben-manes** [comment]
The plugin uses the repositories defined by the project's configuration and does not default to a particular one. So once you add jcenter to your repository list it should query it.

**Comment by MisterY** [comment]
Oh, great. Thanks for that information. I'm a bit puzzled now as I have jcenter at the top of the repository list in both `buildscript` and `allprojects` blocks. mavenCentral is the next one in the list but the version is taken from Maven Central.
If I comment out the mavenCentral line in 'allprojects', I get the following:
```
Failed to determine the latest version for the following dependencies (use --info for details):
 - com.nononsenseapps:filepicker
```
which may point out that there is some other issue, in fact.

**Comment by ben-manes** [comment]
Since we're scripting Gradle's dependency resolution you can inspect the logs to see what it's doing. Most often a resolution strategy or bad maven-metadata.xml is to blame.

**Comment by MisterY** [comment]
Ben, thanks a lot for this investigative work!
