### ISSUE TITLE
Question (or possible bug?) about exceeding version

### ISSUE THREAD

**Issue by twilek** [ben-manes/gradle-versions-plugin#14]
I have a question about exceeding version.

According to the Java Version String Naming convension the underscore is used to indicate an update release, and the dash is used to indicate a non-GA-relase, so as I understand it, a version that only contain an underscore but not a dash is still a GA-release.

I have an component that have the version 1.8.9_build9, but in the repository there is an older version 1.8.8_build8. When running gradle dependencyUpdates I get this message:

The following dependencies exceed the version found at the milestone revision level:
 - component:component [1.8.9_build9 <- 1.8.8_build8]
 
What exactly does this mean? Is that correct? Shall this not only be reported for non-GA-releases?

**Comment by ben-manes** [comment]
Closing as Gradle caching issue.
