### ISSUE TITLE
1.0.0.RELEASE vs 1.0.0.RC2 (io.spring.gradle dependency-management-plugin)

### ISSUE THREAD

**Issue by Petikoch** [ben-manes/gradle-versions-plugin#140]
Hi,

thanks for the excellent `gradle-versions-plugin`, I love it!

Now "my issue": 
We use `io.spring.gradle:dependency-management-plugin` in version `1.0.0.RELEASE` (that's a spring style version number). 
`gradle-versions-plugin` proposes me in `dependencyUpdates` to use `1.0.0.RC2` instead:

``` 
The following dependencies have later milestone versions:
 - io.spring.gradle:dependency-management-plugin [1.0.0.RELEASE -> 1.0.0.RC2]
``` 

This seems to be like a misinterpretation of the version number... what do you think?

Best regards,
Peti

**Comment by ben-manes** [comment]
This is a limitation in Gradle's version comparator. This [forum post](https://discuss.gradle.org/t/wrong-version-comparison-for-maven-affecting-spring/11066/2) has more details. I think they agreed to the fix but it was lost in their backlog.

**Comment by Petikoch** [comment]
Thanks @ben-manes for your answer.

Bad news... I'll see if I can raise an issue in their github gradle project.

**Comment by ben-manes** [comment]
You should probably mention `bigdaz` since he's prompt and had agreement on making the changes. I think he just forgot.

**Comment by ben-manes** [comment]
Thanks for helping to get this fixed.
