### ISSUE TITLE
Wrong latest release version

### ISSUE THREAD

**Issue by IonutNegru87** [ben-manes/gradle-versions-plugin#142]
Hello,

I've noticed that for `javax.annotation:jsr250-api` the latest version is not detected correctly.

The report shows the following:

> The following dependencies have later release versions:
>  - javax.annotation:jsr250-api [1.0 -> 1.0-20050927.133100]

The command run was `gradlew dependencyUpdates -Drevision=release`

**Comment by ben-manes** [comment]
Its an annoying dependency (#81, #82, #136). The [maven-metadata](https://jcenter.bintray.com/javax/annotation/jsr250-api/maven-metadata.xml) states the wrong latest release. The easiest workaround is to use a `resolutionStrategy` to reject that version.

**Comment by ben-manes** [comment]
If you point to Maven Central is might not show up wrong. It looks like they fixed it manually and jcenter has a stale copy. But if you hit both repositories, I'm not sure which would be resolved as the latest.

**Comment by IonutNegru87** [comment]
In my project I have **jcenter** and **mavenCentral**.
How can I update the `resolutionStrategy` to reject that version, for this specific library?

**Comment by ben-manes** [comment]
You can force the version or reject by checking the coordinates. See the readme for a generic example and link to Gradle's user guide.

**Comment by IonutNegru87** [comment]
I've updated the resolution strategy to exclude only that specific version:
```
// Disallow release candidates as upgradable versions
dependencyUpdates.resolutionStrategy = {
    componentSelection { rules ->
        rules.all { ComponentSelection selection ->
            boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier ->
                selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
            }
            if (rejected) {
                selection.reject('Release candidate')
            }

             if (selection.candidate.group == 'javax.annotation'
                    && selection.candidate.module == 'jsr250-api'
                    // && selection.candidate.version == '1.0-20050927.133100'
                    && selection.candidate.version ==~ /[\d]*[.][\d]*[-].*/) {
                // This version is actually older than 1.0, we reject it as it is false-positive
                selection.reject('Unsuported javaxAnnotation version')
            }
        }
    }
}
```

As I'm not great with regex, do you think there is a better way to correctly reject that version?
Thank you.

**Comment by ben-manes** [comment]
Why not use `force` so it's a one liner?

**Comment by IonutNegru87** [comment]
How can I use the `force` ? :D

**Comment by ben-manes** [comment]
```gradle
dependencyUpdates.resolutionStrategy = {
  force 'javax.annotation:jsr250-api:1.0'
}
```
