### ISSUE TITLE
Older lombok version as update

### ISSUE THREAD

**Issue by volphy** [ben-manes/gradle-versions-plugin#144]
As far as I understand it this is not the same issue as:
https://github.com/ben-manes/gradle-versions-plugin/issues/121

I used Gradle 3.4 via Gradle Wrapper.

I have dependency on Lombok defined in my build.gradle:
dependencies {
  ...
  compile 'org.projectlombok:lombok:1.16.14'
 ...
}

Gradle's "dependencies" task confirms it:
./gradlew dependencies | grep lombok
+--- org.projectlombok:lombok:1.16.14
[8 more duplicates)

If I run gradle version plugin, results look as follows:
./gradlew dependencyUpdates -Drevision=release
....
The following dependencies have later release versions:
 - org.projectlombok:lombok [1.16.12 -> 1.16.14]

Is there something wrong with lombok's metadata?

**Comment by ben-manes** [comment]
This is usually due to jcenter having an older version that skews metadata checks, but proxying central when a fixed version is specified. Can you try with both jcenter and central are in your repository block?

**Comment by ben-manes** [comment]
Oh sorry, I misread and jumped to a conclusion.

This can happen when a configuration is using an older version so we have to show each distinct pair. Otherwise it could be a bug. If you put together a reproduction then I can help investigate.

**Comment by volphy** [comment]
You are right. It seems to be a Spring-related issue.

In my pure Java & Gradle pet project, Gradle Version plugins works as expected.

I will delve into #123 and let you know if this is the same issue.

**Comment by volphy** [comment]
I was not aware that lombok was already include in Spring Boot's BOM.

The following did the trick:

build.gradle:
```
ext['lombok.version'] = '1.16.14'

dependencies {
    compile 'org.springframework.cloud:spring-cloud-starter-aws:1.1.3.RELEASE'
    compile 'org.springframework.boot:spring-boot-starter-web'
    compile 'org.springframework.boot:spring-boot-starter-hateoas'
    compile 'org.projectlombok:lombok'
    compile 'com.google.code.gson:gson:2.8.0'

    testCompile 'org.springframework.boot:spring-boot-starter-test'
}
```
