### ISSUE TITLE
How to programatically add repositories

### ISSUE THREAD

**Issue by josetesan** [ben-manes/gradle-versions-plugin#147]
Hi !
Congratulations on your great plugin , it does help me a lot.

I have a question to ask, do not know if it's possible to achieve or not.

In my company current project, we are resolving artifacts only by requesting them to our private nexus repository, ( new libraries are updated by request ), but in order to make the versions plugin work, i'll need access to both mavenCentral() or jcenter().

I thought that by accessing the _dependencyUpdates.project.repositories_ property, i'll be able to add them by code, but didn't work.
Is this possible ?

Thanks a lot !

**Comment by ben-manes** [comment]
I think #98 might help you.

This plugin uses the repositories assigned to your project's configurations. Ideally you would have your private repository act as a proxy ("virtual repository") by querying the external ones. The alternative in #98 was to add the external repositories prior to the task being run, assuming its used independently so as not to conflict with other tasks.

**Comment by josetesan** [comment]
Brilliant !
Thanks :)
