### ISSUE TITLE
"Error listing versions" messages

### ISSUE THREAD

**Issue by huxi** [ben-manes/gradle-versions-plugin#15]
I suddenly get lots of messages like

`Error listing versions of org.apache.maven.wagon:wagon-webdav-jackrabbit:latest.milestone using class org.gradle.api.internal.artifacts.repositories.resolver.MavenVersionLister$1. Will attempt an alternate way to list versions. This behaviour has been deprecated and is scheduled to be removed in Gradle 2.0`

I didn't have this problem before. It was introduced by the [this (rather trivial) commit](https://github.com/huxi/lilith/commit/a18339fc07939713aff450567e1738f5efc4fddb) which looks OK to me.

Everything seems to be working fine beside those messages.

**Comment by ben-manes** [comment]
Closing as this appears to be a Gradle problem. Please reopen if you think we can fix this at the plugin.
