### ISSUE TITLE
No support for soter dependency

### ISSUE THREAD

**Issue by IonutNegru87** [ben-manes/gradle-versions-plugin#153]
Hello,

I've included this library in a project which uses [Soter](https://github.com/kaminomobile/soter) library as dependency, but it fails to determine the latest dependencies for it:
```
Failed to determine the latest version for the following dependencies (use --info for details):
 - gradle.plugin.si.kamino.gradle:soter
```

This is how it is added as dependency:
```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
         classpath "gradle.plugin.si.kamino.gradle:soter:2.1.1"
    }
}

apply plugin: 'si.kamino.soter'
```

**Comment by ben-manes** [comment]
This is the same underlying problem as you had in #126. Here the dependency is only on the plugin portal, whereas in that bug an older version was on Central. This is a Gradle bug and there is nothing I can do.

**Comment by IonutNegru87** [comment]
Hello @ben-manes,

I see, I thought that due to the fact that it was never found it was an different issue. Then I will have to add this one to the black-list and exclude it from the check.

Thank you and keep up the great work ;)
