### ISSUE TITLE
Any debug level to show from where a dependency was derived?

### ISSUE THREAD

**Issue by memelet** [ben-manes/gradle-versions-plugin#154]
I am getting the following
```
The following dependencies have later milestone versions:
 - org.elasticsearch:elasticsearch [2.4.4 -> 5.3.0]
```
But I can find no trace of elasticsearch:2.4.4. The dependency included for the project is 5.2.2.  Is there some to figure out why the plugin thinks I have 2.4.4?

**Comment by ben-manes** [comment]
Do you see it in `gradle dependencies`?

If you are using Spring, it's dependency plugin interacts badly with this one. That is due to a bug in Gradle that is fixed in the next release, I think.

**Comment by ben-manes** [comment]
Closing due to lack of feedback.
