### ISSUE TITLE
alpha/preview checking

### ISSUE THREAD

**Issue by iamtodor** [ben-manes/gradle-versions-plugin#159]
Could you please provide a flag to turn on/off checking every single alpha/preview version? 
I'm not interested in such tools because of unstable things, so I want to be able to skip that output.

**Comment by ben-manes** [comment]
Please see the resolutionStrategy example in the README. Is there something different you need?

**Comment by iamtodor** [comment]
@ben-manes looks like what I need. Somehow I have missed the part. Thank you

**Comment by iamtodor** [comment]
@ben-manes also, take a look at the last PR please :)
