### ISSUE TITLE
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0

### ISSUE THREAD

**Issue by westonal** [ben-manes/gradle-versions-plugin#160]
> The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead. :app:dependencyUpdates

Not sure where the offense is but would appear that something below `dependencyUpdates` is using `<<`

**Comment by ben-manes** [comment]
I don't recall using this, as it is less readable. I only see `<<` used in the Spec tests. Are you sure it isn't in your project customizations of the task?

**Comment by westonal** [comment]
No I don't think it is you, sorry. I just ran `./gradlew tasks` and I got: 

> The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
:tasks

So the error message includes the task that's running, not the task that caused it, it would appear.

**Comment by ben-manes** [comment]
Supposedly `-Dorg.gradle.deprecation.trace=true` will show where it is coming from. Good luck.

**Comment by westonal** [comment]
Thanks very much, that worked great: `at com.crashlytics.tools.gradle.tasks.FabricTaskBuilder.pluginGenerateResources(FabricTaskBuilder.groovy:112)` crashlytics, tut
