### ISSUE TITLE
Unable to determine version when dependencies are numbered like 1.1706.1

### ISSUE THREAD

**Issue by Thunderforge** [ben-manes/gradle-versions-plugin#163]
We have internal dependencies that are numbered like 1.1706.1. More precisely, the format is:

    1.<two-digit year><two-digit month>.<release-number>

We also have `-SNAPSHOT` suffixes.

Unfortunately, this plugin seems to be unable to determine the latest release version. Here is the log output with `--info` enabled:

````
Failed to determine the latest version for the following dependencies (use --info for details):
 - com.example:OurInternalModule
The exception that is the cause of unresolved state: Could not find any version that matches com.example:OurInternalModule:+.
Versions rejected by component selection rules:
    1.1706.1-SNAPSHOT
    1.1705.2
    1.1705.1
    1.1705.1-SNAPSHOT
    1.1704.1
    + 17 more
````

If this could be fixed so that this version number could be parsed correctly, we would be obliged.

**Comment by ben-manes** [comment]
This plugin is using Gradle's dependency resolution, so any failure should be reproducible in your dependency resolution. That way we don't reinvent the wheel and can minimize surprises (plus, much less work!).

It looks like your component selection rules are rejecting all versions that Gradle discovers and evaluates with. We honor both the configuration's rules and let you add your own customizations just for this task. Can you check if your rule has a bug making it too restrictive?

**Comment by Thunderforge** [comment]
I'm having a hard time figuring out how we are changing our component selection rules, but if this plugin is using those, then the issue is elsewhere rather than this plugin. I'll go ahead and close this issue.

**Comment by ben-manes** [comment]
I would recommend giving a reason in your rejection call, which is useful for debugging purposes (e.g. `Release Candidate`)

**Comment by ben-manes** [comment]
One idea is that perhaps you are forcing all modules to a minimum global version (`1.1706.1-SNAPSHOT`). However, you are running the plugin's task at the default revision level (ivy concept), which rejects `SNAPSHOTs`. Therefore the combination results in all candidates being rejected.

If you change the default level from `milestone` to `integration`, if the theory holds, version `1.1706.1-SNAPSHOT` would be reported. You can do this at the command line or configure it on the task by using `dependencyUpdates.revision = 'integration'`.
