### ISSUE TITLE
Sorted text report

### ISSUE THREAD

**Issue by ben-manes** [ben-manes/gradle-versions-plugin#165]
This used to be sorted by the coordinates and I'm not sure why it isn't anymore. I keep forgetting to fix it, so adding this reminder.

**Comment by johnjohndoe** [comment]
@ben-manes Looks like the default alphanumerical sorting is broken again. Can you confirm that?

**Comment by johnjohndoe** [comment]
I see. Thanks for the clarification. [It sounded very much as if this was working before.](https://github.com/ben-manes/gradle-versions-plugin/issues/181#issuecomment-368631522)

**Comment by vanniktech** [comment]
It used to work and then broke. Do you want to fix it and create a PR @johnjohndoe ?

**Comment by johnjohndoe** [comment]
@vanniktech Can you point to the version where it was working?
I don't have time in March - I might be able to look into this later.

**Comment by vanniktech** [comment]
Unfortunately not yet. I've also just started working on this plugin.

**Comment by jaredsburrows** [comment]
If anything we should be able to do a sort on the text file outputs and stdout.

**Comment by ben-manes** [comment]
I suspect the problem was when the reporting was generalized to output to multiple formats. The sort order appears to be name-group-version due to the order of fields in [Dependency](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/reporter/result/Dependency.groovy). Moving to group-name-version should fix it. 

Ideally we might also use [VersionComparator](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/VersionComparator.groovy) for multiple versions in a build (as grouped across all projects) to more strictly follow Maven's  semantics. But that's more work, for little gain, than the one-liner moving the field order. 😃

**Comment by jaredsburrows** [comment]
@ben-manes Thanks!
