### ISSUE TITLE
Failed to determine the latest version for some gradle plugins.

### ISSUE THREAD

**Issue by sureshg** [ben-manes/gradle-versions-plugin#166]
### Env
  - Kotlin =1.1.2-2
  - Gradle version plugin =0.15.0
  - Gradle Script Kotlin =4.0-20170523130707+0000

I have following 3 plugins in my Gradle script kotlin plugins block, but the plugin is failed to determine the latest version and throws the following warning message.

```
plugins {
    ...
    id("us.kirchmeier.capsule") version "1.0.2"
    id("com.dorongold.task-tree") version "1.3"
    id("co.riiid.gradle") version "0.4.2"
}
```

```
Failed to determine the latest version for the following dependencies (use --info for details):
 - com.gradle:build-scan-plugin
 - gradle.plugin.co.riiid:gradle-github-plugin
 - gradle.plugin.com.dorongold.plugins:task-tree
```
From the error message, it seems like the plugin name is mentioned incorrectly `gradle.plugin.com.dorongold.plugins:task-tree:+ ` 

```
The exception that is the cause of unresolved state: Could not find any matches for gradle.plugin.com.dorongold.plugins:task-tree:+ as no versions of gradle.plugin.com.dorongold.plugins:task-tree are available.
Searched in the following locations:
    https://repo.gradle.org/gradle/repo/gradle/plugin/com/dorongold/plugins/task-tree/maven-metadata.xml
    https://repo.gradle.org/gradle/repo/gradle/plugin/com/dorongold/plugins/task-tree/
    https://dl.bintray.com/kotlin/kotlinx/gradle/plugin/com/dorongold/plugins/task-tree/maven-metadata.xml
    https://dl.bintray.com/kotlin/kotlinx/gradle/plugin/com/dorongold/plugins/task-tree/
    https://plugins.gradle.org/m2/gradle/plugin/com/dorongold/plugins/task-tree/maven-metadata.xml
    https://plugins.gradle.org/m2/gradle/plugin/com/dorongold/plugins/task-tree/
```

**Comment by ben-manes** [comment]
This is a limitation of the Gradle Plugin Portal which does disallows metadata queries. See #126 for a discussion. I and others have requested it repeatedly on their forum and google group, and now have https://github.com/gradle/gradle/issues/1297 as well. Unfortunately they have always been unresponsive to these requests with no feedback whatsoever. There is nothing we can do on our end.

**Comment by sureshg** [comment]
Thanks! That's unfortunate. Anyway, will track those issues.

**Comment by ben-manes** [comment]
Closing as duplicate.
