### ISSUE TITLE
release option recomends update to alpha version

### ISSUE THREAD

**Issue by imanushin** [ben-manes/gradle-versions-plugin#167]
Script to execute: ```gradle dependencyUpdates -Drevision=release```

And the following text was in the logs:
```
The following dependencies have later release versions:
 - com.android.support.test.espresso:espresso-core [2.2.2 -> 2.3-alpha]
 - com.android.tools.build:gradle [2.3.2 -> 2.5.0-alpha-preview-02]
 - com.android.support:support-v4 [25.3.1 -> 26.0.0-alpha1]
```

From my point of view, it is better to skip all dependencies with words ```alpha```, ```beta```, ```-rc```, etc. in version

**Comment by ben-manes** [comment]
That's because `revision` is a concept in the repository metadata, which do not support these version naming conventions.

Instead you should use a `resolutionStrategy` to filter out version patterns that you don't consider valid. See the readme for an example of that.

**Comment by imanushin** [comment]
@ben-manes , agree. Closing issue
