### ISSUE TITLE
Cannot fetch latest versions of gradle-apt-plugin and gradle-errorprone-plugin

### ISSUE THREAD

**Issue by jbduncan** [ben-manes/gradle-versions-plugin#169]
This issue is a combination of https://github.com/tbroyer/gradle-apt-plugin/issues/56 and https://github.com/tbroyer/gradle-errorprone-plugin/issues/49, which I'm reporting here in case it can be fixed on the gradle-versions-plugin side.

From the (admittedly little) amount of research I've done, it looks like this issue is potentially a duplicate of https://github.com/ben-manes/gradle-versions-plugin/issues/166, so if it is, please let me know and I'd be happy to close it.

# Context
When I apply gradle-versions-plugin to a simple Gradle project which already applies [gradle-apt-plugin](https://github.com/tbroyer/gradle-apt-plugin/) and [gradle-errorprone-plugin](https://github.com/tbroyer/gradle-errorprone-plugin) and then I run `./gradlew dependencyUpdates`, it does not accurately show the latest versions of  both plugins that the project can update to.

It shows the latest version of gradle-errorprone-plugin as 0.6, rather than 0.10 as expected.

Furthermore it completely fails to determine the latest version of gradle-apt-plugin, rather than showing the latest version as 0.10.

From what I can tell, this issue may be related in some way to issue https://github.com/tbroyer/gradle-errorprone-plugin/issues/48.

# How to reproduce
1. Clone https://github.com/jbduncan/dependency-updates-test into a local directory.
2. Run `./gradlew dependencyUpdates` (UNIX) or `gradlew.bat dependencyUpdates` (Windows) at the root of the newly cloned project from the terminal.

# Expected output
```
:dependencyUpdates

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes:gradle-versions-plugin:0.15.0

The following dependencies have later milestone versions:
 - com.google.auto.value:auto-value [1.4 -> 1.4.1]
 - com.google.errorprone:error_prone_core [2.0.19 -> 2.0.21]
 - com.google.guava:guava [21.0 -> 23.0-rc1]
 - net.ltgt.gradle:gradle-apt-plugin [0.9 -> 0.10]
 - net.ltgt.gradle:gradle-errorprone-plugin [0.0.10 -> 0.0.11]

...
```

# Actual output
```bash
$ ./gradlew dependencyUpdates
```
```
:dependencyUpdates

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes:gradle-versions-plugin:0.15.0

The following dependencies exceed the version found at the milestone revision level:
 - net.ltgt.gradle:gradle-errorprone-plugin [0.0.10 <- 0.0.6]

The following dependencies have later milestone versions:
 - com.google.auto.value:auto-value [1.4 -> 1.4.1]
 - com.google.errorprone:error_prone_core [2.0.19 -> 2.0.21]
 - com.google.guava:guava [21.0 -> 23.0-rc1]

Failed to determine the latest version for the following dependencies (use --info for details):
 - net.ltgt.gradle:gradle-apt-plugin

Generated report file C:\Users\Jonathan\dev\Java\IntelliJ Projects\dependency-updates-test\build/dependencyUpdates\report.txt

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed

```

# Gradle version information
```bash
$ ./gradlew --version
```
```
------------------------------------------------------------
Gradle 4.0.2
------------------------------------------------------------

Build time:   2017-07-26 15:04:56 UTC
Revision:     108c593aa7b43852f39045337ee84ee1d87c87fd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 7 6.1 amd64
```

**Comment by ben-manes** [comment]
Yes, this would be due to https://github.com/gradle/gradle/issues/1297. I find it frustrating too, but the only workaround I could do is write a custom resolver and parse the HTML for the plugin portal. The correct solution is to fix the repository and I keep hoping the Gradle team will acknowledge the problem.

**Comment by tbroyer** [comment]
That's a duplicate of #126 (and a few others)

**Comment by jbduncan** [comment]
@ben-manes Urgh, okay. Mildly frustrating, but I'll live. :wink:

@tbroyer Yeah, that's the conclusion I've come to as well. I'll close this issue for now.

Many thanks both for your input!
