### ISSUE TITLE
Cannot resolve external dependency 

### ISSUE THREAD

**Issue by jeusdi** [ben-manes/gradle-versions-plugin#172]
I'm getting this information when I'm trying to get updates:

> The exception that is the cause of unresolved state: Cannot resolve external dependency org.apache.httpcomponents:httpclient:+ because no repositories are defined.

any ideas?

**Comment by ben-manes** [comment]
Can you provide the build.gradle and info log?

**Comment by jeusdi** [comment]
Solved... I missed to set `repositories` closure into gradle script.
