### ISSUE TITLE
Reports of multiple subprojects use the same outputDir and overwrite each others reports

### ISSUE THREAD

**Issue by Adrodoc55** [ben-manes/gradle-versions-plugin#173]
When you have multiple subprojects and run the task dependencyUpdates on all of them, each report will be generated in the location of whichever task was first executed. That means that subsequent reports will overwrite previous ones and you end up with only a single report for the last subproject.
This is because the [DependencyUpdatesTask uses get with default on System.properties](../blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy#L65):
```groovy
String outputDirectory() { System.properties.get('outputDir', outputDir) }
```

This however also modifies the System-Properties when the key is not found:
> [Looks up an item in a Map for the given key and returns the value - unless there is no entry for the given key in which case add the default value to the map and return that.](http://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/Map.html#get(java.lang.Object,%20java.lang.Object))

To avoid this sideeffect I suggest to ALWAYS use something like:
```groovy
System.properties['outputDir'] ?: outputDir
```

**Comment by ben-manes** [comment]
Thanks! I must have thought of this as `Map#getOrDefault` and didn't realize there was a side effect.

Also you can apply the plugin only to the root project for the consolidated report. That's useful if you centralize your dependency definitions (e.g. `compile libraries.guava`). Perhaps that flow is more common so this snuck through unnoticed.

**Comment by Adrodoc55** [comment]
@ben-manes I'm afraid that is not an option for me, because the dependencies in different subprojects are vastly different from one another.
