### ISSUE TITLE
Create a public listing of library to changelog URL mapping

### ISSUE THREAD

**Issue by frmz** [ben-manes/gradle-versions-plugin#177]
Not sure if there is something like this already but it would be great to have changelog together with upgrade suggestion, a quick hack would be to have a mapping between library names and changelogs or use the POM changelog plugin which afaik is not used a lot

**Comment by ben-manes** [comment]
Perhaps see #94

**Comment by frmz** [comment]
Sorry forgot to reply definitely related and sorry for not checking the past issues, not sure what went wrong with the search, lets close this, will subscribe to the other
