### ISSUE TITLE
Sorted output

### ISSUE THREAD

**Issue by aalmiray** [ben-manes/gradle-versions-plugin#180]
It would be great to have an option that enables sorting dependencies in a particular order, for example alphanumerical. Right now the order "appears" to be random.

**Comment by aalmiray** [comment]
Loos like this is a duplicate of #165

**Comment by ben-manes** [comment]
Yep, its the hash right now. Still not sure why it changed from the ascending string order, but keep meaning to fix that.

**Comment by jaredsburrows** [comment]
@ben-manes Is this the same as https://github.com/ben-manes/gradle-versions-plugin/issues/165?

**Comment by ben-manes** [comment]
Yep, closing.
