### ISSUE TITLE
html reports

### ISSUE THREAD

**Issue by mozinrat** [ben-manes/gradle-versions-plugin#184]
Hi Do you support generating html reports for dependencies, something similar to https://gemnasium.com/ or version eye

**Comment by ben-manes** [comment]
No, but contributions are welcome. We can generate text, json, and xml. That should be enough for ad hoc or CI integrations.

**Comment by jaredsburrows** [comment]
Here is example of how I am doing it in a project of mine here: https://github.com/jaredsburrows/gradle-license-plugin/blob/master/src/main/groovy/com/jaredsburrows/license/LicenseReportTask.groovy#L235.

To create the XML, you can use `MarkupBuilder ` from `Groovy` APIs: https://github.com/jaredsburrows/gradle-license-plugin/blob/master/src/main/groovy/com/jaredsburrows/license/internal/report/HtmlReport.groovy.

**Comment by ben-manes** [comment]
Live on JCenter, in sync for the plugin portal. Thanks @jcrokicki!
https://bintray.com/fooberger/maven/com.github.ben-manes%3Agradle-versions-plugin/0.30.0
