### ISSUE TITLE
dependencyUpdates task is up-to-date

### ISSUE THREAD

**Issue by boris-petrov** [ben-manes/gradle-versions-plugin#187]
After the update to 0.16, running just a `gradle dependencyUpdates` gives:

```
BUILD SUCCESSFUL in 0s
1 actionable task: 1 up-to-date
```

It might be a problem in my configuration (although everything was fine in 0.15) but in any case I don't think that this task should *ever* be up-to-date. :) [This](https://github.com/ben-manes/gradle-versions-plugin/commit/3cce551e9ced67e38dc99022018f209fd103bea1) might be responsible?

**Comment by dominicE** [comment]
Same here:

11:56:37: Executing external task 'dependencyUpdates'...
:dependencyUpdates UP-TO-DATE

BUILD SUCCESSFUL

Total time: 0.067 secs
11:56:37: External task execution finished 'dependencyUpdates'.

**Comment by augi** [comment]
Also can confirm this issue.

**Comment by ben-manes** [comment]
Sorry about that! I added the fix and the next release should be pushed out by TravisCI shortly.

**Comment by dominicE** [comment]
0.17 is working, thank you
