### ISSUE TITLE
Fail a task when dependencies have new versions

### ISSUE THREAD

**Issue by grv87** [ben-manes/gradle-versions-plugin#191]
I want to run `dependencyUpdates` task in CI before release.
Could the task fails whenever there are new versions available, so release would be stopped?

**Comment by ben-manes** [comment]
You could use the closure to inspect the result and throw a `GradleException`. Or externally from Gradle by using a script to parse the json/xml report. Note that you would be subject to the gradle cache, unless you use `--refresh-dependencies` or force a check to the repositories.

However, I would not advise that you block a release. Imagine a production issue you are rushing to fix, and a major new version is released that is backwards incompatible. Now the person must learn and debug the restriction to work around it. If your nice you might add a flag to bypass it, but it does add stress unnecessarily. Similarly upgrade may not be possible in the short term, and requires some scheduling.

If you use fixed versions and notify the team of upgrades, then you shouldn't need to force this upon them.

**Comment by grv87** [comment]
This automatic updates checking should be limited for minor and patch versions only. So there should be no backward incompatibility. And, if there is - it is violation of semver, and these versions should be banned by me (so users would never have this problem).

I agree that it may be not useful for everybody and so off by default.
I'll try to make a PR.

**Comment by ben-manes** [comment]
Sorry, but I wouldn’t accept this feature. It’s best to be in your code or an additional plugin.

**Comment by grv87** [comment]
OK, I'll make a fork or switch to https://github.com/4finance/uptodate-gradle-plugin. They have this feature.

BTW, analogue for this plugin in Bundler and Berkshelf is `outdated` command. It sets exit code to 1 if there are updates.

**Comment by ben-manes** [comment]
Setting the exit code is reasonable. But it could be done easily within the build script I think.

My concern with version matching idea is that artifacts do not always follow semver and can differ in odd ways. Trying to infer that type of logic is messy.

I would rather expose enough information to allow scripting of customizations rather than as many features. So if it cannot be done easily due to a limitation, I’d rather fix that underlying problem instead.
