### ISSUE TITLE
Unexpected "The following dependencies exceed the version found at the milestone revision level"

### ISSUE THREAD

**Issue by westonal** [ben-manes/gradle-versions-plugin#196]
I am getting:
```
The following dependencies exceed the version found at the milestone revision level:
 - io.github.novacrypto:BIP39 [0.1.5 <- 0.1.2]
```
After recently publishing a new update.

If I look at the file at: https://jcenter.bintray.com/io/github/novacrypto/BIP39/:maven-metadata.xml

I see:

```
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>io.github.novacrypto</groupId>
  <artifactId>BIP39</artifactId>
  <version>0.1.5</version>
  <versioning>
    <latest>0.1.5</latest>
    <release>0.1.5</release>
    <versions>
      <version>0.1.0</version>
      <version>0.1.1</version>
      <version>0.1.2</version>
      <version>0.1.3</version>
      <version>0.1.5</version>
    </versions>
    <lastUpdated>20171111152639</lastUpdated>
  </versioning>
</metadata>
```

Looks fine, Poms files look OK too: 

https://jcenter.bintray.com/io/github/novacrypto/BIP39/0.1.2/:BIP39-0.1.2.pom
https://jcenter.bintray.com/io/github/novacrypto/BIP39/0.1.5/:BIP39-0.1.5.pom

So is this a local caching issue of `gradle-versions-plugin` that will go away? Is there a cache I can clear to fix? Or is it a problem with my publish?

**Comment by ben-manes** [comment]
Assuming JCenter is in your repository listing, then it would be Gradle's cache. You can force Gradle to recheck repositories using `--refresh-dependencies`.

**Comment by westonal** [comment]
Thanks for that Ben!

**Comment by ianbrandt** [comment]
I get these often, even with `--refresh-dependencies`:

```
13:29:44: Executing 'dependencyUpdates --refresh-dependencies'...
[...]
The following dependencies exceed the version found at the milestone revision level:
 - org.jetbrains.kotlinx:kotlinx-coroutines-core [1.6.0 <- 1.5.2]
     https://github.com/Kotlin/kotlinx.coroutines
 - org.springframework.security:spring-security-config [5.6.1 <- 5.6.0]
     https://spring.io/projects/spring-security
 - org.springframework.security:spring-security-core [5.6.1 <- 5.6.0]
     https://spring.io/projects/spring-security
 - org.springframework.security:spring-security-crypto [5.6.1 <- 5.6.0]
     https://spring.io/projects/spring-security
 - org.springframework.security:spring-security-messaging [5.6.1 <- 5.6.0]
     https://spring.io/projects/spring-security
 - org.springframework.security:spring-security-test [5.6.1 <- 5.6.0]
     https://spring.io/projects/spring-security
 - org.springframework.security:spring-security-web [5.6.1 <- 5.6.0]
     https://spring.io/projects/spring-security
```

**Comment by ben-manes** [comment]
You can see what repositories it is using with `--info`. JCenter was notorious for hosting outdated `maven-metadata.xml` files with stale versions (used by dynamic `+` resolution), but then proxying point queries directly to Maven Central for artifact resolution. Since Central has this dependency, I'd make sure to have `mavenCentral()` in your repository listing (and remove `jcenter()` all together if possible).

**Comment by ianbrandt** [comment]
Thanks, @ben-manes! We are still using a local Nexus proxy of JCenter in our build, so that very well could be it. We're going to eliminate that JCenter proxy from our build soon, so I'll report back on whether that fixes this.
