### ISSUE TITLE
Intermediate versions?

### ISSUE THREAD

**Issue by onacit** [ben-manes/gradle-versions-plugin#199]
Thank you for the great plugin.

Is there any chance to implement intermediate versions not just latest?

Let's say I have a Spring Boot application and, for some reason, I use `1.5.8.RELEASE`.
An I have no plan for any of `2.0.x.RELEASE` (Spring Boot 2).

Is there any way to know there is new `1.5.9.RELEASE` along with latest?

**Comment by ben-manes** [comment]
There are feature requests for showing bread crumbs, e.g. `1.0 => 1.6 => 2.1`, as discussed in #69, #95, #96, and #189. That could be done using additional resolution queries, at the expense of slower execution. It would a nice enhancement for someone to pick up.

You can use a `resolutionStrategy` to restrict the report to certain versions. In your case, you could require that the spring versions must be `1.+`, thereby rejecting new ones. The report will then show `1.5.8.RELEASE => 1.5.9.RELEASE` but not the latest of `2.0.x.RELEASE`.

If anyone does want to take a stab, the approach would be to build on the dynamic version ranges. By splitting on '.' the plugin would query for `1.5.9.+`, `1.5.+`, `1.+`, and `+`. The results would be kept in a set to drop duplicates. The Gradle cache would hopefully make this just a single remote call by keeping the metadata, but its a little too unpredictable to know upfront.

**Comment by vanniktech** [comment]
I'll close this in favor of the other issues that are asking for the same feature request.
