### ISSUE TITLE
resolve versions in parallel

### ISSUE THREAD

**Issue by christophsturm** [ben-manes/gradle-versions-plugin#201]
I have pretty high latency to some of the repos that i use, and since gradle started resolving versions in parallel i thought maybe the versions plugin could be updated to do the same. if that's an easy change i could try to do a pr for this.

**Comment by ben-manes** [comment]
Unfortunately my understanding is that Gradle does not yet support parallel version selection, but will resolve the artifacts in parallel (https://github.com/gradle/gradle/issues/1309#issuecomment-306912668). Perhaps you’re right that we could try resolving in parallel by using multiple configurations and the worker api. You are welcome to give it a shot, just remember to disable the dependency cache when testing.

**Comment by christophsturm** [comment]
where in the gradle api or versions plugin sources would I start such an investigation?

**Comment by ben-manes** [comment]
In the plugin, see [Resolver](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy). You might look at the task too, which calls this per configuration to parallelize that.

In Gradle, see the worker api:
https://guides.gradle.org/using-the-worker-api/

**Comment by ben-manes** [comment]
Merged @rpau's improvement here, which parallelizes the configurations. There is still room for improvement of large configurations, like `compile`, but that's more invasive. Lets revisit if this doesn't suffice.

**Comment by christophsturm** [comment]
oh very cool. sorry for not working on this. is there going to be a release soon?
