### ISSUE TITLE
Single Dependency Updates report for multi-module project

### ISSUE THREAD

**Issue by leinardi** [ben-manes/gradle-versions-plugin#203]
Is there a way to have a single report file containing the reports of all the modules of the project?

It would be helpful because currently is generating a specific report for each module so I need to manually check all the modules report to find if something needs to be updated.

I'm trying to use this plugin with this project where I have 13 submodules: https://github.com/leinardi/androidthings-drivers

**Comment by leinardi** [comment]
Never mind, the global report is generated by applying the plugin also to the root build.gradle.

**Comment by ben-manes** [comment]
Yes. The way I use the plugin is to have it applied only on the root project. It then traverses all children to aggregate the dependencies and display the report. With that, I then update the corresponding versions in a centralized `gradle/dependencies.gradle` manifest.

An example of this usage is in my caching project.
