### ISSUE TITLE
is there a way to do a distance calculation?

### ISSUE THREAD

**Issue by DemianTinkiel** [ben-manes/gradle-versions-plugin#204]
e.g. org.springframework.boot:spring-boot-gradle-plugin [1.5.6.RELEASE -> 1.5.10.RELEASE]
 to give me 0.0.4.RELEASE ?

I'd like to fail on divergence > N

Perhaps if `dependency.version` could have the same components as `dependency.available`

**Comment by ben-manes** [comment]
I think you could leverage the custom report hook, which you might be implying from your last statement. The Gradle api doesn’t give us the version list, so we can’t provide all of the upgrade options easily.

**Comment by jaredsburrows** [comment]
Yes. Unless you a have the current `pom.xml` and the `maven-metadata.xml`, you cannot do this. Also, even if you were to "subtract" them, you may not have individual versions in between.

**Comment by vanniktech** [comment]
Seems like your question got answered. In case it didn't reply either here or create a new issue.
