### ISSUE TITLE
exclude alpha versions

### ISSUE THREAD

**Issue by ligi** [ben-manes/gradle-versions-plugin#210]
really like the plugin just have one problem on android - would love when there is an option so it does not suggest alpha versions like this:

` - com.android.support:appcompat-v7 [27.1.0 -> 28.0.0-alpha1]`

**Comment by ben-manes** [comment]
Yes, this is [supported](https://github.com/ben-manes/gradle-versions-plugin#revisions). Due to not being part of Maven's versioning rules and many ad hoc conventions, Gradle does this using a `resolutionStrategy`. You can specify wide or narrow rules in your configuration.

**Comment by ligi** [comment]
great! thanks
