### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by ben-manes** [ben-manes/gradle-versions-plugin#216]
Just an FYI for when you want to release a new version...
1. Increment version in `build.gradle` and commit
2. Add Github release notes
3. CI will see the new tag and deploy the archive.

**Comment by vanniktech** [comment]
That's need. Anything else that needs to be done?

**Comment by ben-manes** [comment]
I think just a call of when you want to release. There are some nice improvements in master, but also there was interest in working on #69 and #76. Versions are cheap so no harm releasing earlier than later.

**Comment by jaredsburrows** [comment]
Does this work because we are `collaborators`?

**Comment by ben-manes** [comment]
In the sense that you can create tags. @jochenberger set it up in the [TravisCI configuration]( https://github.com/ben-manes/gradle-versions-plugin/blob/master/.travis.yml).

**Comment by ben-manes** [comment]
I think we're in a great state for a release. What do you guys think?

**Comment by vanniktech** [comment]
Sure. Sorry I've not been as active as I'd like to have be.

**Comment by jaredsburrows** [comment]
Since this PR(https://github.com/ben-manes/gradle-versions-plugin/pull/222) got merged, I'd definitely like to have another release.

**Comment by ben-manes** [comment]
Released
