### ISSUE TITLE
Could you describe how (the download mechanism of) this plugin works?

### ISSUE THREAD

**Issue by 030** [ben-manes/gradle-versions-plugin#218]
I now get

```
Failed to determine the latest version for the following dependencies (use --info for details):
```

while normally there is a report. When `updateDependency` task was run, multiple artifacts were downloaded, but the laptop crasht and when I run the same command now it does not show any report. How does the download mechanism work? Is some caching involved? I already ran clean and --refresh-dependencies, but no report can be created.

**Comment by ben-manes** [comment]
The plugin scripts Gradle’s apis, so refresh-dependencies usually works to bypass its cache. You could delete the cache in your ~/.gradle to force a hard refresh.

**Comment by 030** [comment]
Shall I create a PR and extend the readme?

**Comment by ben-manes** [comment]
If you think there is useful and missing information, then definitely.

**Comment by ben-manes** [comment]
That is weird. Do you have a resolution strategy forcing the version? That might interfer with looking up the latest.

**Comment by 030** [comment]
It looks like that it is only applicable to our company packages. If a versions is decreased of a 3rdparty package then the plugin indicates that it could be updated.

`resolution strategy forcing the version`? Do you have some examples? Do you have some suggestions to check whether something like that is enforced in our repository?

**Comment by 030** [comment]
```
package:a:1.2.2
package:a:1.2.2
package:a:1.2.2
package:a:1.2.2
package:a:1.2.2
package:a:1.2.2
package:a:1.2.2
package:a:1.2.2
package:a:1.2.2
```

The following dependencies are using the latest release version:
 - package:a:1.2.2


and when decreased:

```
package:a:1.1.0
package:a:1.1.0
package:a:1.1.0
package:a:1.1.0
package:a:1.1.0
package:a:1.1.0
package:a:1.1.0
package:a:1.1.0
```

The following dependencies are using the latest release version:
 - package:a:1.0.0

**Comment by ben-manes** [comment]
From a prior [sample output](https://github.com/ben-manes/gradle-versions-plugin/issues/195#issuecomment-343362602), it looks like it might be in the debug logs instead.

**Comment by 030** [comment]
it looks to be an issue in our resolution strategy. Thank you for the quick replies
