### ISSUE TITLE
Is it possible to exclude certain versions?

### ISSUE THREAD

**Issue by 030** [ben-manes/gradle-versions-plugin#219]
According to the output the latest version is 1234, but that should be 1.2.3. Is it possible to exclude certain versions?

One attempt was to use the resolutionStrategy that is described in the readme

```
dependencyUpdates.resolutionStrategy = {
  componentSelection { rules ->
    rules.all { ComponentSelection selection ->
      boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier ->
        selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
      }
      if (rejected) {
        selection.reject('Release candidate')
      }
    }
  }
}
```

Once `boolean rejected` was changed to 1234 and the regex and function were modified a little bit the version was excluded but 1.2.3.  could not be found.

**Comment by ben-manes** [comment]
You would probably want to use the check the candidate group, name, version instead of a broader Reyes on just the version.

Usually the missing version is because a repository isn’t included. For example jcenter proxies central for point versions but often returns old metadata for dynamic lookups. So adding central to the repository listing fixes.

**Comment by 030** [comment]
We recently introduced semantic versioning and in this case if 1.2.3 is defined and 1.2.4 is available we would like to see that 1.2.4 is the latest instead of 1234 that is from 2016. Is it possible to omit such old versions?

**Comment by ben-manes** [comment]
```
if (selection.candidate.group == ??? && selection.candidate.version >= '1000') {
  selection.reject('old versioning scheme')
}

**Comment by 030** [comment]
Thank you. When this is used, the log indicates that other artifacts are downloaded from the artifact manager.
