### ISSUE TITLE
Question: Classifier-Support

### ISSUE THREAD

**Issue by MarcDahlem** [ben-manes/gradle-versions-plugin#224]
Hi Ben-Manes,

is there a support for classifiers?

We have some internal libraries which are published only via classifier.
Their versions do not update correctly during the dU-task.

Furthermore, is there a possibility to get the extension provided by the dependency (e.g. '@zip').

Thanks & BR

**Comment by vanniktech** [comment]
@MarcDahlem has the question been answered?

**Comment by MarcDahlem** [comment]
Oh sry, I did not find the time to llok into your code. I wanted to test + submit pull request if the following works:

Instead of

> project.dependencies.create("${dependency.group}:${dependency.name}:+") {
    transitive = false
}

we could use propably

> project.dependencies.create("${dependency.group}:${dependency.name}:+:${dependency.classifier}@${dependency.ext}") {
    transitive = false
}

Of course, the classifier and ext should only be added if they exist in the dependency (dependency.classifier != null or so).

**Comment by ben-manes** [comment]
@MarcDahlem the classifier and extension are not part of the [ExternalDependency](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ExternalDependency.html) api. I don't know how we can query for them.

**Comment by ben-manes** [comment]
Oh, it's in the artifact.

```groovy
dependencies.create("a:b:+:test@jar").artifacts.each { art ->
  println "${art.extension} - ${art.classifier}"
}
```
