### ISSUE TITLE
Consider making `DependencyUpdates.resolutionStrategy` easier to use from kotlin-dsl

### ISSUE THREAD

**Issue by mkobit** [ben-manes/gradle-versions-plugin#227]
It would be useful to `kotlin-dsl` users to have some better type information to configure the `DependenyUpdatesTask`.

https://github.com/ben-manes/gradle-versions-plugin/blob/61405e79ffbad726a7a4ffef75b34c18e6921aef/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy#L38

In the [`kotlin-dsl`](https://github.com/gradle/kotlin-dsl) it might look something look like this:

```kotlin
val dependencyUpdates by tasks.getting(DependencyUpdatesTask::class) {
  val rejectPatterns = listOf("alpha", "beta", "rc", "cr", "m").map { qualifier ->
    Regex("(?i).*[.-]$qualifier[.\\d-]*")
  }
  resolutionStrategy = closureOf<ResolutionStrategy> {
    componentSelection {
      all {
        if (rejectPatterns.any { it.matches(this.candidate.version) }) {
          this.reject("Release candidate")
        }
      }
    }
  }
}
```

Or, if using an external script with Groovy:

`somescript.gradle`
```groovy
ext.dependencyUpdatesResolutionStrategy = {
  componentSelection { rules ->
    rules.all { ComponentSelection selection ->
      boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier ->
        selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
      }
      if (rejected) {
        selection.reject('Release candidate')
      }
    }
  }
}
```

`build.gradle.kts`
```kotlin
val dependencyUpdates by tasks.getting(DependencyUpdatesTask::class) {
  val dependencyUpdatesResolutionStrategy: groovy.lang.Closure<Any?> by project.extra
  resolutionStrategy = dependencyUpdatesResolutionStrategy
}
```

Some possibly ways of improving it that I can think of:

* Make it `Action<? super ResolutionStrategy> resolutionStrategy`. I think from Kotlin you might still need a cast right now so it would still be a little ugly: `resolutionStrategy = Action { }`
* Add a `resolutionStrategy(Action<? super ResolutionStrategy> resolutionStrategy)` method so that `kotlin-dsl` users can do `resolutionStrategy {}` directly on the tasks

**Comment by ben-manes** [comment]
I think adding a method is best. I was trying to get the release out quickly, and made it a field, which is not idiomatic. A method would give us more flexibility with overloads, etc. Want to send a PR?

**Comment by mkobit** [comment]
I will try to send a PR in the next couple days.

**Comment by ben-manes** [comment]
We're looking to put a release out. Is there anything we should do in the immediate term here?

**Comment by mkobit** [comment]
Sorry, totally forgot about this. I'm working on a change set today, will send it tonight or tomorrow (if that isn't too late).

**Comment by ben-manes** [comment]
Sure! We've been long over due and only got a spurt of energy to focus on this, so don't feel rushed. Thanks :)
