### ISSUE TITLE
Identify configurations created by this plugin

### ISSUE THREAD

**Issue by gabrielittner** [ben-manes/gradle-versions-plugin#229]
I've got a resolutionStrategy that I apply like this:

```
configurations.all {
    resolutionStrategy.eachDependency {
        // force version for specific dependencies
    }
}
```

The plugin isn't able to find updates for dependencies where the version is forced because the code above gets also applied to the configurations created by this plugins and overrides the `+` version it sets.

Is there any way to identify configurations created by this plugin? That way I could add an if check in `configurations.all` before applying the resolutionStrategy.

**Comment by gabrielittner** [comment]
Just to be clear, I'm referring to the copies created here https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L111

**Comment by ben-manes** [comment]
The workaround so far has been to check if the plugin will execute using if either the taskGraph or `startParameter.taskNames` The latter works above the strategy, while the former only works inside of it.

**Comment by gabrielittner** [comment]
I didn't know about startParameter, which works for now.
