### ISSUE TITLE
Fatal Error: The prefix "Xlint" for element "Xlint:-unchecked" is not bound.

### ISSUE THREAD

**Issue by cmuchinsky** [ben-manes/gradle-versions-plugin#238]
After upgrading to the much faster 0.18.0 version (thank you!), I am now seeing the following error reported:
```
[Fatal Error] hadoop-project-3.1.0.pom:1787:24: The prefix "Xlint" for element "Xlint:-unchecked" is not bound.
Failed to resolve :foo:compile
```

**Comment by ben-manes** [comment]
Can you put together a sample to debug with?

**Comment by cmuchinsky** [comment]
This should do it:
```
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath group: 'com.github.ben-manes', name: 'gradle-versions-plugin', version: '0.18.0'
  }
}

apply plugin: 'java'
apply plugin: 'com.github.ben-manes.versions'

repositories {
  jcenter()
}

dependencies {
  compile(group: 'org.apache.hadoop', name: 'hadoop-mapreduce-client-core', version: '2.7.6') {
    exclude group: '*'
  }
}
```

**Comment by ben-manes** [comment]
It looks like the XML has an invalid namespace and `XmlSlurper` is (by default) stricter than the build tools when parsing it. I think we need to disable namespace checking (the `false, false` constructor). 

The pom contains this block,
```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <configuration>
    <fork>true</fork>
    <source>${javac.version}</source>
    <target>${javac.version}</target>
    <compilerArguments>
      <Xlint/>
      <Xlint:-unchecked/>
      <Xmaxwarns>9999</Xmaxwarns>
    </compilerArguments>
  </configuration>
</plugin>
```

However, the [plugin documentation](https://maven.apache.org/plugins/maven-compiler-plugin/examples/pass-compiler-arguments.html) states that compiler arguments are actually supposed to be passed like
```xml
<compilerArgs>
  <arg>-verbose</arg>
  <arg>-Xlint:all,-options,-path</arg>
</compilerArgs>
```

The project's pom is adding undeclared namespaces, so the strict checking fails. We only added the XML parsing in 18 to extract out extra details, specifically the project's URL, so we might also catch and ignore any exception thrown for good measure.
