### ISSUE TITLE
Disable gradle version check for non-public wrapper URL

### ISSUE THREAD

**Issue by imanushin** [ben-manes/gradle-versions-plugin#241]
Short idea: fix gradle version check for non-official gradle distributions.

In our company we don't have access to the internet from gradle scripts. 

So, we use custom distribution URL, e.g. our gradle-wrapper.properties file is like this:

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://<intranet-gradle-distribution-site>/org/gradle/binaries/gradle-4.8-all.zip
```

**The main issue:** plugin gets timeout error during the gradle version verification (and it works for a long time).

Possible solutions:
* Add ability to disable gradle updates check from task ```dependencyUpdates```
* Use distribution URL from file for next version lookup (e.g. for version 4.8 we can check 5.0, 4.9, 4.8.1, nothing more, because SemVer has three kinds)

**Comment by ben-manes** [comment]
Does a private distribution url provide the same lookup api that the public one does? Note that for Gradle itself is not in a maven repository but uses a custom REST endpoint.

**Comment by imanushin** [comment]
@ben-manes , unfortunately no. It just supports 404 response for missing resource .

**Comment by ben-manes** [comment]
In that case then I don't think we'd want to create a new ad hoc lookup scheme. For dependencies we let Gradle do the work and for the distribution lookup we use a custom resolver based on the [public API](https://services.gradle.org/versions). The more we customize and diverge, the more painful it is to catch-up as the build tool evolves.

I think your idea of a flag to disable the check is best. It would be nice to use the `distributionUrl` and infer the best approach, but that sounds like it might be more problematic than its worth?

**Comment by imanushin** [comment]
@ben-manes , I agree with disabling gradle updates check. However I don't understand your suggestion.

Do you suggest to use ```distributionUrl``` for API url lookup? In this case right urls will works fine, invalid urls will get server error fast. This is fully ok for me (it is not problem to get error, the initial issue - error is delivered for too long time).

Or possible do you suggest to put flag into gradle/gradle.properties/gradle-wrapper.properties files?

**Comment by ben-manes** [comment]
Sorry, I meant that ideally we might infer from the `distributionUrl` whether to perform the check, how to perform it, etc. But that sounds pretty magical and error-prone, so adding a task-level flag to enable/disable seems like a better idea.

@aaronols contributed this feature so fyi in case you have any thoughts.

**Comment by ben-manes** [comment]
The release will be live after the TravisCI build completes (as it does our releases for us based on new tags). Should take just a few minutes.
