### ISSUE TITLE
Gradle 4.8 is not pulling the pom files everytime after results are cached

### ISSUE THREAD

**Issue by wezley98** [ben-manes/gradle-versions-plugin#243]
Seems as if there is another caching issue, Gradle 4.8 doesn't seem to be pulling the pom files on every run once it has run once. Gradle 4.7 works fine.

**Comment by ben-manes** [comment]
Usually Gradle caches the dependency resolution, by default for 24 hours. I haven't observed any change in this behavior. You can use `--refresh-dependencies` to force a new query when running the task within your caching duration.

**Comment by wezley98** [comment]
Yes, that's works thanks for the info.
