### ISSUE TITLE
Use dependencyUpdates.resolutionStrategy on init.gradle

### ISSUE THREAD

**Issue by nicodeur** [ben-manes/gradle-versions-plugin#245]
Hello,

I would like use dependencyUpdates.resolutionStrategy on a ìnit.gradle` (./gradlew  --init-script init.gradle dependencyUpdates).

But I can't add it on `initscript` or `allprojects`etc.

That's I try to add on my `init.gradle` (I try it on several place `initscript` or `allprojects`etc.) 
```
dependencyUpdates.resolutionStrategy {
  componentSelection { rules ->
    rules.all { ComponentSelection selection ->
      boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier ->
        selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
      }
      if (rejected) {
        selection.reject('Release candidate')
      }
    }
  }
}
```

Thats my `init.gradle` 
```

initscript {
    dependencies {
        classpath "gradle.plugin.com.dvoiss.globalplugins:global-gradle-plugin:1.0"
    }
}

apply plugin: com.dvoiss.globalplugins.GlobalDependencyPlugin

allprojects {

    globalDependencies {
        addAndroid 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.8.2', 'com.getkeepsafe.dexcount'
        addAndroid 'com.github.ben-manes:gradle-versions-plugin:0.17.0', 'com.github.ben-manes.versions'
    }

}
```

**Comment by ben-manes** [comment]
Sorry, I haven't used init scripts in my builds so I am unfamiliar with the workarounds needed. Perhaps StackOverflow will help here?

Perhaps @mkobit's [answer](https://stackoverflow.com/a/48341661/19450) to a more basic version might help?

**Comment by DCKcode** [comment]
After some experimentation I found the following configuration to work in an `init.gradle`:

    allprojects {
      afterEvaluate {
        project.apply plugin: 'com.github.ben-manes.versions'
        project.apply plugin: 'se.patrikerdes.use-latest-versions'

        dependencyUpdates.resolutionStrategy = {
          componentSelection { rules ->
            rules.all { ComponentSelection selection ->
              boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier ->
                selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
              }
              if (rejected) {
                  selection.reject('Not a stable version.')
              }
            }
          }
        }
      }    
    }

**Comment by ben-manes** [comment]
nice, thanks!
