### ISSUE TITLE
Implement "Run at end of build" function

### ISSUE THREAD

**Issue by scphantm** [ben-manes/gradle-versions-plugin#247]
I need to implement a feature like this

https://github.com/nebula-plugins/gradle-lint-plugin/blob/master/src/main/groovy/com/netflix/nebula/lint/plugin/GradleLintPlugin.groovy

This runs the lint at the end of the build.  I have added logic to that so it only runs that check once a day (or after clean).  I would like to do the same with your plugin, i have to put it in your system apparently because im getting a few collisions.  

I am willing to build this into your plugin and submit a merge request for it, if you are interested in the feature.

If the answer is yes, i would need to turn it around quickly.  meaning we would have to get it knocked out in a week or so.

interested?

**Comment by ben-manes** [comment]
This plugin can be slow, so I wouldn't recommend running it as part of a developer build. It will kick in at an inappropriate time, e.g. when fixing a production bug.

Have you considered using a CI job to run the task and report it?

**Comment by scphantm** [comment]
yea, i know its slow.  thats why we add things in to only run once a day.  but i have 1000 developers that like to ignore things.  

I wouldn't recommend turning it on by default, i would disable it by default.  but, in my enterprise quality plugin, i would enable that scan.

CI server doesn't work well because the devs typically only read the logs if there is a problem.  They would likely never know this report was there.

**Comment by ben-manes** [comment]
For the CI server you could email / slack / github issue when updates are detected. The later means it gets into the developer's workflow. For example see [gradle-update-notifier](https://github.com/y-yagi/gradle-update-notifier). In those cases you would have a dedicated job that runs on your schedule, processes the report, and notifies where appropriate.

If that doesn't help and a modification is the only way to do this then I'm okay with a PR. I would think you could do it without modifying the task, though.

**Comment by Vampire** [comment]
You can make the build fail if updates are present if your devs at least look for failed builds.
Something like

```gradle
dependencyUpdates {
    outputFormatter {
        if (it.outdated.count) {
            throw new RuntimeException("Outdated libraries found")
        }
    }
}
```

**Comment by jaredsburrows** [comment]
@Vampire's suggestion works. 

I believe this is not really a feature for this plugin. Ideally you want to upgrade dependencies on separate incremental commits in order to have a track and have a history of dependency upgrades.
