### ISSUE TITLE
Filter out RC versions of Gradle

### ISSUE THREAD

**Issue by sschuberth** [ben-manes/gradle-versions-plugin#248]
I just realized that

    dependencyUpdates.resolutionStrategy = {
        componentSelection { rules ->
            rules.all { ComponentSelection selection ->
                boolean isNonFinalVersion = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier ->
                    selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
                }

                if (isNonFinalVersion) {
                    selection.reject('Release candidate')
                }
            }
        }
    }

does not work to filter out

    Gradle updates:
     - Gradle: [4.8.1 -> 4.9-rc-1]

Which is not that surprising if your think about it, as Gradle itself is not a project dependency. But are there other means to filter out Gradle RC versions? Or maybe a trick to *make* above code snippet actually work for Gradle versions, like injecting Gradle as a "fake" project dependency? If the latter worked, that would probably also solve https://github.com/ben-manes/gradle-versions-plugin/issues/246.

**Comment by ben-manes** [comment]
I think right now it will show (current) -> (next) -> (rc) and skips any if absent in the text report. So you can decide to ignore the rc if undesirable but can’t configure it’s removal. We thought that would be a fair compromise without adding configuration complexity.

**Comment by Mygod** [comment]
@ben-manes Could you also show latest stable releases for dependencies as well?

**Comment by ben-manes** [comment]
@Mygod I think that's #69, but none of us have explored implementing it. We'd do it using (+, x.+, x.y.+) and removing duplicates. Hopefully the Gradle cache would fetch the metadata once rather than make multiple remote lookups.

**Comment by dje1990** [comment]
Hi @sschuberth 

Was the feature you were looking for covered in #273 ? Thanks.

**Comment by sschuberth** [comment]
Yes, @dje1990, indeed it did. Thanks for the reminder!
