### ISSUE TITLE
Resource missing errors - invalid plugin/gradle setup?

### ISSUE THREAD

**Issue by abennet** [ben-manes/gradle-versions-plugin#249]
When I run the dependencyUpdates target in my project I get the following issues:

Resource missing. [HTTP GET: http://private-ivy-repo/raw/master/org.slf4j/log4j-over-slf4j/]
...
 - org.slf4j:log4j-over-slf4j
The exception that is the cause of unresolved state: Could not find any matches for org.slf4j:log4j-over-slf4j:+ as no versions of org.slf4j:log4j-over-slf4j are available.
Searched in the following locations:
    http://private-ivy-repo/raw/master/org.slf4j/log4j-over-slf4j/

These errors appear for all dependencies of the subprojects. The gradle compile build succeeds at resolving the dependencies in the compilation phase.

Are there any pre-requisites around using a private ivy repo or anything specific about the gradle setup that must be met before running the plugin?

**Comment by ben-manes** [comment]
Nope, we're resolving using Gradle's apis just like it should for a dependency. We copy the configuration, tweak to a dynamic version, and compare. Sometimes there are issues where Gradle or plugins don't handle the copies correctly, e.g. hard code to check configuration names.

Unfortunately Ivy repositories are rare in the public, so I don't know if its an ivy issue or not.

Sometimes there are quirks with Gradle due the order of repositories when declared. You might make sure the primary ones are first and then your fallback. I think Gradle no longer queries subsequent repositories if it has a hard failure, like auth issue.
