### ISSUE TITLE
Error resolving plugin

### ISSUE THREAD

**Issue by GeneticSYS** [ben-manes/gradle-versions-plugin#250]
It seems there is a problem with jfrog's artifactory since there is only the pom-file without any corresponding jar-file:

![jfrog](https://user-images.githubusercontent.com/28043700/42770164-a2b23d1c-8924-11e8-91fc-071dae268c4b.PNG)

**Gradle-Error**:

```
Error resolving plugin [id: 'com.github.ben-manes.versions', version: '0.20.0']
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not determine artifacts for com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.20.0
      > Could not get resource 'https://plugins.gradle.org/m2/com/github/ben-manes/versions/com.github.ben-manes.versions.gradle.plugin/0.20.0/com.github.ben-manes.versions.gradle.plugin-0.20.0.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/com/github/ben-manes/versions/com.github.ben-manes.versions.gradle.plugin/0.20.0/com.github.ben-manes.versions.gradle.plugin-0.20.0.jar'.
            > Read timed out
```

**Comment by ben-manes** [comment]
It looks like all versions only have a pom file and no jar. You're right that it must be a repository issue since it goes back to 0.5 when the plugin portal was launched.

**Comment by GeneticSYS** [comment]
Okay, It seems to be fixed by now. Gradle is resolving the plugin correctly again and our CI-System isn't complaining anymore :-)
