### ISSUE TITLE
Support for odd/even version policies like jackrabbit etc ?

### ISSUE THREAD

**Issue by ieugen** [ben-manes/gradle-versions-plugin#253]
Hi, 

Some projects use a version scheme where odd releases are unstable and even releases are stable. 
One example is Apache Jackrabbit - 2.16.x is stable, 2.17.x is unstable. 

While this versioning scheme is falling out of use there are cases where it is used. Also, since some other projects release non-final builds (alpha, rc, dev) it would be great to be able to specify a version policy that eliminates these non-desired candidates from version updates. 

I think having https://github.com/ben-manes/gradle-versions-plugin/issues/69 is a good solution or this issue, allowing developers the option of choosing the version manually.  

Thanks,
Eugen

http://jackrabbit.apache.org/jcr/jackrabbit-roadmap.html

**Comment by ben-manes** [comment]
Could you use a resolution strategy to reject version patterns that you don’t want shown?

**Comment by ieugen** [comment]
Hi,

Thanks for the hint. It worked well. I would like to submit this for documentation. 

How to reject unstable releases for Apache Jackrabbit components:

```
            if (selection.candidate.group.equalsIgnoreCase("org.apache.jackrabbit")) {
                def ver = selection.candidate.version.toString()
                // extract version the numbers
                def nb = ver =~ /^(\d+)\.(\d+)\.(\d+)/
                if (nb.find()) {
                    if (Integer.parseInt(nb.group(2)) % 2 == 1) {
                        println("Rejected unstable jackrabbit version ${selection.candidate} - ${ver}")
                        selection.reject("Rejected unstable version for jackrabbit ${ver}")
                    }
                }
            }
```

**Comment by ben-manes** [comment]
Wonderful, I'm glad it worked for you!
