### ISSUE TITLE
The plugin believes 1.2-groovy-2.5 is older than 1.2-RC3-groovy-2.5

### ISSUE THREAD

**Issue by henrik242** [ben-manes/gradle-versions-plugin#260]
- org.spockframework:spock-spring [1.2-groovy-2.5 -> 1.2-RC3-groovy-2.5]
        http://spockframework.org

**Comment by ben-manes** [comment]
R is after G. There is a version order defined by Maven that many don’t follow, so the comparison order is off. This is what Gradle does and likely Maven would resolve to. At best you could raise it to the Gradle team, but otherwise you could try to exclude it in the resolutionStrategy. I don’t think it’s fixable, unfortunately.

**Comment by Petikoch** [comment]
A similiar issue was https://github.com/ben-manes/gradle-versions-plugin/issues/140 with the fix via https://github.com/gradle/gradle/issues/1378

**Comment by henrik242** [comment]
@ben-manes How about these:

```
The following dependencies exceed the version found at the milestone revision level:
- com.google.guava:guava [30.1.1-jre <- 23.0]
    https://github.com/google/guava
- org.spockframework:spock-core [2.0-groovy-3.0 <- 0.3]
    http://spockframework.org
- org.spockframework:spock-spring [2.0-groovy-3.0 <- 0.3]
    http://spockframework.org
```

Any way of supporting spock @ guava's custom version names?

**Comment by ben-manes** [comment]
@henrik242 you'd have to provide your repository listing, etc. Most likely you filtered out Maven Central and its fetching the metadata from a repository with stale information. Since Gradle performs the resolution, any improvements would go to them for everyone to benefit.

**Comment by henrik242** [comment]
Thanks! You're right, I couldn't replicate it in a dummy project.  I'll close this for now until I figure out exactly what the problem is.
