### ISSUE TITLE
Provide Gradle Kotlin DSL examples in documentation

### ISSUE THREAD

**Issue by eriwen** [ben-manes/gradle-versions-plugin#267]
As a [Gradle Kotlin DSL](https://github.com/gradle/kotlin-dsl) adopter, I'd like to know how to configure this plugin using the Kotlin DSL.

[This plugin was identified](https://github.com/gradle/gradle/issues/6790) as one of the most useful Gradle plugins. With Kotlin DSL 1.0 approaching shortly, it'd be wonderful if the documentation provided Kotlin and Groovy DSL samples. [Blog post with suggestions](https://blog.gradle.org/groovy-kotlin-dsl-samples).

Here are a couple additional resources:

 * [Migrating build logic from Groovy to Kotlin guide](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/)
 * [Exemplar for automated samples testing](https://blog.gradle.org/documentation-samples-testing-exemplar)
 * [Join #kotlin-dsl channel in Gradle Community Slack for personalized help](https://join.slack.com/t/gradle-community/shared_invite/enQtNDE3MzAwNjkxMzY0LTYwMTk0MWUwN2FiMzIzOWM3MzBjYjMxNWYzMDE1NGIwOTJkMTQ2NDEzOGM2OWIzNmU1ZTk5MjVhYjFhMTI3MmE)

Thank you for providing a great Gradle plugin! —The Gradle Team

**Comment by ben-manes** [comment]
Hi @eriwen,

Thank you for the kind words. Does the [kotlin section](https://github.com/ben-manes/gradle-versions-plugin#revisions) of the readme resolve this concern? @mkobit was kind enough to add that DSL snippet (#227 / #237).

**Comment by jmfayard** [comment]
@ben-manes almost fine, I improved it a bit there
https://github.com/ben-manes/gradle-versions-plugin/pull/276

**Comment by jmfayard** [comment]
By the way, my plugin works on Gradle 5.0, so yours too!

**Comment by ben-manes** [comment]
Thanks! 😃

**Comment by fred84** [comment]
@jmfayard Why `plugins { ... }` block do not work with kotlin DSL?

**Comment by jmfayard** [comment]
@fred84 I don't really understand your question
You can check out how the `plugins` block is used here
https://github.com/ben-manes/gradle-versions-plugin/blob/master/examples/kotlin/build.gradle.kts

**Comment by fred84** [comment]
@jmfayard Sorry, I was wrong. Everything works as expected.

**Comment by jmfayard** [comment]
@fred84 never be sorry about asking 
May the developer who is never wrong cast the first stone 😆
