### ISSUE TITLE
Provide path to generated report file

### ISSUE THREAD

**Issue by johnjohndoe** [ben-manes/gradle-versions-plugin#268]
# Current status
- At the end of the console output of the `dependencyUpdates` task the path to the generated report file is printed:

``` bash
...

Gradle updates:
 - Gradle: [4.7 -> 4.10.2]

Generated report file build/dependencyUpdates/report.txt
```
The path **differs** whether the plugin is configured at project root level or within a module.

# Target status
- A task property aka. _run mode_ is passed to only output the path of the report file. Here is an example:

``` bash
$ .gradlew dependencyUpdates -Drunmode=reportpathonly
build/dependencyUpdates/report.txt
```

# Background
- I want to collect the `report.txt` files of multiple projects. Some projects have the plugin configured per module others per project. I want to avoid hardcoding the paths to the `report.txt` for each project.

**Comment by ben-manes** [comment]
Can you use `outputDir` to set a consistent directory? It could be relative to the project using `buildDir`. You could query the task property if you want to know upfront for aggregation.

**Comment by johnjohndoe** [comment]
I think `-DoutputDir=` will resolve my issue. Thank you for the hint.

**Comment by ben-manes** [comment]
Great. You can set it in your build script I think, as a task property.
