### ISSUE TITLE
ResolutionStrategy for configurations is ignored

### ISSUE THREAD

**Issue by jochenberger** [ben-manes/gradle-versions-plugin#28]
See #26.
A new detached configuration is created to resolve the latest dependencies. This will lead to ResolutionStrategy configurations on the original configuration(s) being ignored.

**Comment by ben-manes** [comment]
The fix for #62 would also solve this. We could resolve each configuration, aggregate the result into a combined set, and then generate the report. This should be fast because of Gradle's dependency cache performing the external lookup once.

**Comment by ben-manes** [comment]
Fixed in #62
