### ISSUE TITLE
Allow to configure reporter used to write to console 

### ISSUE THREAD

**Issue by AlexanderZobkov** [ben-manes/gradle-versions-plugin#288]
Currently the dependencyUpdates task outputs a report to stdout by using the PlainTextReporter (in addition to reporter that is used to dump the report to a file and configurable). 
It would be really great to allow specifying a closure or Reporter object to form a custom report that is dumped to stdout.

For example to make a report:
- shorter, 
- or signify this or that information.

**Comment by ben-manes** [comment]
I think you want this?
https://github.com/ben-manes/gradle-versions-plugin#custom-report-format

**Comment by AlexanderZobkov** [comment]
Unfortunately no,
I would like to specify a custom reporter here:

class DependencyUpdatesReporter
 def write() {
    synchronized (MUTEX) {
      PlainTextReporter plainTextReporter = new PlainTextReporter(project, revision)

      plainTextReporter.write(System.out, buildBaseObject())

**Comment by ben-manes** [comment]
I would think that a custom reporter would let you handle whatever your needs are. So I'm not sure why changes in that code location would be needed.

Worst case, you can transform the output like this developer did,
https://github.com/Henkoglobin/gradle-versions-prettify

**Comment by AlexanderZobkov** [comment]
There several reasons:
1/ PlaintTextReporter which is used to dump a report to console is verbose and not possible to turn it off (and verbosity increases with a number of used dependencies).  
2/ When using a custom reporter that dump a report to a file with reduced/eliminated verbosity, it takes extra effort to developers to go to build directory and observe it with cat/less tool 
3/ Takes extra effort to configure archiving of that custom report on a CI system

**Comment by ben-manes** [comment]
Actually, the fix in master seems to be what you're asking for and I'm just being dense. 😄

**Comment by ben-manes** [comment]
Released
