### ISSUE TITLE
Allow access to current dependency descriptor in ResolutionStrategy

### ISSUE THREAD

**Issue by fonix232** [ben-manes/gradle-versions-plugin#290]
I'd like to write a custom ResolutionStrategy that matches the "prerelease"-levelness of the plugin and marks updates accordingly.

E.g. if one is currently using an `-rc01` version of a library, I'd like to alert them to updates on that branch (so RC or anything higher). This would allow for small incremental jumps (`rc01` to `rc02` but not to `alpha03`, `alpha03` to `rc03` or `alpha04`, etc.).

**Comment by ben-manes** [comment]
Unfortunately this is a limitation of the Gradle api, as it’s theirs not ours. You can open an issue in their GitHub.

If you maintain a central manifest, e.g. `dependencies.gradle`, then you could look it up using the group and name.

**Comment by ben-manes** [comment]
@ghus-raba contributed a really nice solution to this problem, so closing. We should look into making another release soon with the improvement.
