### ISSUE TITLE
Instructions to use it globally

### ISSUE THREAD

**Issue by aadrian** [ben-manes/gradle-versions-plugin#294]
Please add instructions on how to use this plug-in globally, (maybe set it in `~/.gradle/init.gradle` ?) to have it for all projects. 

Or are there any issues that prevent a global usage?

Thank you.

**Comment by ben-manes** [comment]
I imagine [answer](https://stackoverflow.com/questions/48332171/how-can-i-apply-the-gradle-versions-plugin-from-an-initscript) might help. Since I don't use init scripts, I'm not the proper resource to answer it.

**Comment by ben-manes** [comment]
@jochenberger added to our README, thanks!
