### ISSUE TITLE
Version 0.21.0 not working for root directory in Arrow's multiproject build

### ISSUE THREAD

**Issue by jrgonzalezg** [ben-manes/gradle-versions-plugin#295]
I have tried to update from 0.20.0 to 0.21.0 in https://github.com/arrow-kt/arrow and for some reason it stops reporting dependency updates when run from the root directory. It works with 0.20.0 but it returns nothing if run with 0.21.0. Any idea of what may be the cause? I have 0.21.0 on other multiproject repositories and it seems to work, so I'm not sure why it doesn't for this one or what changed since 0.20.0 to cause this.

**Comment by ben-manes** [comment]
It might be due to 
https://github.com/gradle/kotlin-dsl/issues/934. It was closed with a weird answer that doesn’t match Gradle’s documentation or behavior, so I’m pretty sure it was disingenuous. Gradle’s default configuration does work properly but the kotlin dsl differs for whatever reason.

**Comment by jrgonzalezg** [comment]
It seems this configuration is also affecting cause if I delete that I get dependency update results again: https://github.com/arrow-kt/arrow/blob/master/build.gradle#L221-L255

But I'm not sure what is the purpose of that or if it is compatible / intended as a possibility when using "Gradle Versions Plugin". Do you have any idea if that kind of setup is supported or how to migrate it to current version 0.21.0?

**Comment by ben-manes** [comment]
Oh, maybe you were negatively impacted by https://github.com/ben-manes/gradle-versions-plugin/issues/254?

**Comment by jrgonzalezg** [comment]
Could be, I'm not sure cause how it works cause I didn't do that part on Arrow. Do you think it can be fixed on our side by changing that block somehow?

**Comment by ben-manes** [comment]
The request in #254 was to not print the console report if a custom `outputFormatter` was defined. In that case the user wanted to write a custom report to the console. In your case, the output formatter is being used as a callback hook to assert a condition and fail, but does not print anything. You might be able to replace that block using a `resolutionStrategy`.

**Comment by ben-manes** [comment]
There could also be value in adding a different callback hook, decoupled from the report, for these types of cases.

**Comment by jrgonzalezg** [comment]
ok, then it is certainly that. But if is just that the report printing does not happen automatically, then maybe I could add a call to the normal version of the report printing? How is that named? Can't I just print that as part of the task with a proper call?

**Comment by ben-manes** [comment]
[PlainTextReporter](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy)

Its called like,
```groovy
def plainTextReporter = new PlainTextReporter(project, revision, gradleReleaseChannel)
plainTextReporter.write(System.out, result)
```
The `revision` and `gradleReleaseChannel` can be pulled from the `dependencyUpdates` task as those are user settings being passed through.

**Comment by jrgonzalezg** [comment]
Thanks!, besides that I needed to add an import for `PlainTextReporter`, but it basically works! 🎉. There seem to be some issues if I change the revision to integration or release (it reports new milestone versions of version `null` but works well with default / milestone, which I think is enough for now :). I may try to further modify that with a resolution strategy as you said later on.

**Comment by jrgonzalezg** [comment]
So I'm closing this since it is an intended behavior change and not an issue although your idea of new hooks could be useful, but that would be separate from this issue I think.

**Comment by ben-manes** [comment]
Great, I'm glad you found a workaround. :)
