### ISSUE TITLE
Failed to determine the latest version of dependency with classifier and extension

### ISSUE THREAD

**Issue by lpicquet** [ben-manes/gradle-versions-plugin#301]
I publish my documentation as an zip archive of asciidoctor documents and I have added them as a dependency to my project

dependencies {
    adocs 'fukoka:f_users_rest:0.15.28:adoc@zip'
}

running the dependenciesUpdateTask, I get the following message in the report:
Failed to determine the latest version for the following dependencies (use --info for details):
 - fukoka:f_users_rest

Can this be added

**Comment by ben-manes** [comment]
I think we resolve the coordinates as `fukoka:f_users_rest:+` but may not match on your case. The info log would hint to why.

**Comment by ben-manes** [comment]
We now query using the classifier and extension if specified. I hope that fixes your issue.
