### ISSUE TITLE
Gradle 5.x + dependencyUpdates = StackOverflowError

### ISSUE THREAD

**Issue by danbar74** [ben-manes/gradle-versions-plugin#306]
Recently tried to migrate Gradle 4.x => 5.x. Unfortunately, running dependencyUpdates with Gradle 5.x results with StackOverflowError(see [stackoverflowerror.txt](https://github.com/ben-manes/gradle-versions-plugin/files/3077910/stackoverflowerror.txt) for more details):
```
> Task :backend:dependencyUpdates FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':backend:dependencyUpdates'.
> java.lang.StackOverflowError (no error message)
```
The same build file (see [build.txt](https://github.com/ben-manes/gradle-versions-plugin/files/3077917/build.txt)) works fine with Gradle 4.x. Tried to replicate the same issue with some other projects with no luck, so it has to be something specific to this particular build.

**Comment by ben-manes** [comment]
Does running with `--no-daemon` let you see the `StackOverflowError` details? In the log it doesn't show that stacktrace, just that it is looping on `org.liquibase:liquibase-core:3.7.0-SNAPSHOT`. Interestingly, I don't see 3.7-SNAPSHOT on the [public repository](https://oss.sonatype.org/content/repositories/snapshots/org/liquibase/liquibase-core/), so you might want to see if the metadata on your private one is not corrupted. I agree nothing jumps out as the cause...

**Comment by danbar74** [comment]
Now it makes sense why I couldn't replicate with my other, non-production project - they use jcenter, not a private repo. There's indeed a snapshot build of liqubase in private repo, deployed by someone manually. Still a bit of a mystery why it works with Gradle 4.x, does not with 5.x.

[stackoverflowerror-no-daemon-gradle-4.10.3.txt.zip](https://github.com/ben-manes/gradle-versions-plugin/files/3078058/stackoverflowerror-no-daemon-gradle-4.10.3.txt.zip)
[stackoverflowerror-no-daemon-gradle-5.3.1.txt.zip](https://github.com/ben-manes/gradle-versions-plugin/files/3078059/stackoverflowerror-no-daemon-gradle-5.3.1.txt.zip)

**Comment by ben-manes** [comment]
There still is no exception logged, so I can't tell where the recursion is coming from. You may need to ask the Gradle folks, as we should mostly be relying on their dependency resolution. What happens in your build using `org.liquibase:liquibase-core:+` as the version? This is basically what the plugin is doing, does your compilation fail similarly?

**Comment by danbar74** [comment]
Hmmm... interesting. Changing the version to `+` results with this:
```
$ ./gradlew dependencyUpdates --stacktrace

> Task :backend:dependencyUpdates
Failed to resolve :backend:-runtime
Failed to resolve :backend:compileClasspath
Failed to resolve :backend:default
Failed to resolve :backend:implementation
Failed to resolve :backend:implementationDependenciesMetadata
Failed to resolve :backend:runtimeClasspath
Failed to resolve :backend:runtimeElements
Failed to resolve :backend:testCompileClasspath
Failed to resolve :backend:testImplementation
Failed to resolve :backend:testImplementationDependenciesMetadata
Failed to resolve :backend:testRuntimeClasspath

------------------------------------------------------------
:backend Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes:gradle-versions-plugin:0.21.0
 - com.integralblue:log4jdbc-spring-boot-starter:1.0.2
 - org.jetbrains.kotlin:kotlin-allopen:1.3.30
 - org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.3.30
 - org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.30
 - org.jetbrains.kotlin:kotlin-noarg:1.3.30
 - org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.3.30

The following dependencies have later milestone versions:
 - com.h2database:h2 [1.4.197 -> 1.4.199]
     http://www.h2database.com
 - org.apache.derby:derby [10.14.2.0 -> 10.15.1.3]
     http://db.apache.org/derby/
 - org.springframework.boot:spring-boot-configuration-processor [2.0.7.RELEASE -> 2.1.4.RELEASE]
     https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-tools/spring-boot-configuration-processor
 - org.springframework.boot:spring-boot-gradle-plugin [2.0.7.RELEASE -> 2.1.4.RELEASE]
     https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-tools/spring-boot-gradle-plugin
 - org.springframework.boot:spring-boot-starter-jetty [2.0.7.RELEASE -> 2.1.4.RELEASE]
     https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-jetty

Gradle release-candidate updates:
 - Gradle: [5.3.1 -> 5.4-rc-1]

Generated report file build/dependencyUpdates/report.txt

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.3.1/userguide/command_line_interface.html#sec:command_line_warnings
```
, however refreshing Gradle project from IDE (JetBrains IDEA) fails with (more details in [full-stacktrace.txt](https://github.com/ben-manes/gradle-versions-plugin/files/3078129/full-stacktrace.txt)):
```
> Task :wrapper

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.3.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed

FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify dependency resolution listener.
> java.lang.StackOverflowError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.3.1/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE FAILED in 3s
Cause: java.lang.StackOverflowError
	at org.apache.ivy.util.XMLHelper.newSAXParser(XMLHelper.java:59)
	at org.apache.ivy.util.XMLHelper.parse(XMLHelper.java:133)
	at org.apache.ivy.util.XMLHelper.parse(XMLHelper.java:122)
```

**Comment by ben-manes** [comment]
Great, you get the stacktrace. I think this is a Gradle issue, can you open it over there?

**Comment by danbar74** [comment]
Consider it done.
Thanks for helping.
