### ISSUE TITLE
Run tool as standalone, without editing Gradle file

### ISSUE THREAD

**Issue by skfd-tt** [ben-manes/gradle-versions-plugin#307]
Would be cool to run this app as a development tool, without changing anything in Gradle file of the project. Is that possible?

**Comment by ben-manes** [comment]
Perhaps using the Gradle tooling API to query the build, and then perform the resolution independently. I suspect that's how IntelliJ's recent built-in support works.

There are other tools like [Dependabot](https://dependabot.com) and [Renovate](https://github.com/CMBStudios/Renovate). Sometimes these types of tools avoid invoking the build and try to parse it instead. That works for simple cases, but Gradle allows for a lot of flexibility that a naive parser cannot account for. They might be good enough for most teams, though.

I really haven't tried or looked at the latest alternatives, though.

**Comment by ben-manes** [comment]
Closing as out of scope, but I hope one of those other tools is useful for this case. 😃
