### ISSUE TITLE
Plugin using deprecated method of ComponentSelectionRules (scheduled for removal in Gradle 6.0)

### ISSUE THREAD

**Issue by gijsleussink** [ben-manes/gradle-versions-plugin#310]
Running Gradle 5.4.1 with the gradle-versions-plugin gives a deprecation warning when using `--warning-mode all`
`The method ComponentSelectionRules.all(Closure) with injection of ComponentMetadata and/or IvyModuleDescriptor has been deprecated. This is scheduled to be removed in Gradle 6.0. Use the new methods on ComponentSelection instead.`

**Comment by ben-manes** [comment]
@Vampire kindly fixed this on master, so we’ll release during the RC if not sooner. Thanks.

**Comment by TWiStErRob** [comment]
Duplicates #270, fixed by #305
