### ISSUE TITLE
Gradle release-candidate is shown regardless of exclusion rules

### ISSUE THREAD

**Issue by johnjohndoe** [ben-manes/gradle-versions-plugin#316]
I have Gradle wrapper version 5.4.1 defined and your plugin [v0.21.0](https://github.com/ben-manes/gradle-versions-plugin/releases/tag/v0.21.0) applied in a project of mine. I also have the latest [`resolutionStrategy` snippet from your README.md](https://github.com/ben-manes/gradle-versions-plugin#revisions) applied in order to filter out release candidates of certain dependencies. When I execute the Gradle `dependencyUpdates` task I however see the following:

```
Gradle release-candidate updates:
 - Gradle: [5.4.1 -> 5.5-rc-1]
```

I would have expected that `5.5-rc-1` is hidden. Is this a special handling for Gradle dependencies or is this a configuration error for the exclude rules?

**Comment by ben-manes** [comment]
Gradle uses a non-standard repository and lookup, so this is custom support. You can change that using `gradleReleaseChannel = 'current'` property, I think.

**Comment by johnjohndoe** [comment]
Where would I specify the property?

**Comment by ben-manes** [comment]
On the task

**Comment by johnjohndoe** [comment]
`./gradlew -PgradleReleaseChannel='current' dependencyUpdates` has no effect. Can you please provide the exact command?

**Comment by ben-manes** [comment]
dependenyUpdates.gradleReleaseChannel = “current”
Or
-DgradleReleaseChannel=current

https://github.com/ben-manes/gradle-versions-plugin/blob/4f0b7ce7b8c76531fcd0808c46a00b0a9b582d65/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy#L89

**Comment by johnjohndoe** [comment]
Thanks! For completeness ... and because I did realized the `-D` vs. `-P`:

```
./gradlew -DgradleReleaseChannel=current dependencyUpdates
```

... works fine.
