### ISSUE TITLE
Causing Gradle Sync Failure

### ISSUE THREAD

**Issue by sreejith-hme** [ben-manes/gradle-versions-plugin#318]
```
Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 2, 2019
JRE: 1.8.0_152-release-1343-b16-5323222 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-154-generic

Gradle Version: 5.1.1
Gradle Build Tool Version: 3.4.1

 min_sdk_version = 17
 target_sdk_version = 28
 compile_sdk_version = 28
 build_tools_version = '28.0.3'
```

Am getting following error when classpath is added in buildScript block, while gradle sync:

> Gradle sync failed: 'Gradle: androidx.test.ext:junit:1.0.0@aar' already disposed: --------------Creation trace: java.lang.Throwable: 1562652246351 at com.intellij.openapi.util.TraceableDisposable. (TraceableDisposable.java:44) at com.intellij.openapi.roots.impl.libraries.LibraryImpl. (LibraryImpl.java:102) at com.intellij.openapi.roots.impl.libraries.LibraryImpl. (LibraryImpl.java:74) at com.intellij.openapi.roots.impl.libraries.LibraryTableBase$LibraryModel.createLibrary(LibraryTableBase.java:298) at com.intellij.openapi.roots.impl.libraries.LibraryTableBase$LibraryModel.createLibrary(LibraryTableBase.java:291) at com.intellij.openapi.roots.impl.libraries.LibraryTableBase$LibraryModel.createLibrary(LibraryTableBase.java:285) at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.createLibrary(AbstractIdeModifiableModelsProvider.java:257) at com.android.tools.idea.gradle.project.sync.setup.module.android.AndroidModuleDependenciesSetup.setUpLibraryDependency(AndroidModuleDependenciesSetup.java:84) at com.android.tools.idea.gradle.project.sync.setup.module.android.DependenciesAndroidModuleSetupStep.updateLibraryDependency(DependenciesAndroidModuleSetupStep.java:151) at com.android.tools.idea.gradle.project.sync.setup.module.android.DependenciesAndroidModuleSetupStep.doSetUpModule(DependenciesAndroidModuleSetupStep.java:87) at com.android.tools.idea.gradle.project.sync.setup.module.android.DependenciesAndroidModuleSetupStep.doSetUpModule(DependenciesAndroidModuleSetupStep.java:62) at com.android.tools.idea.gradle.project.sync.setup.module.ModuleSetupStep.setUpModule(ModuleSetupStep.java:35) at com.android.tools.idea.gradle.project.sync.setup.module.common.BaseSetup.setUpModule(BaseSetup.java:41) at com.android.tools.idea.gradle.project.sync.idea.data.service.AndroidModuleModelDataService.setUpModule(AndroidModuleModelDataService.java:96) at com.android.tools.idea.gradle.project.sync.idea.data.service.AndroidModuleModelDataService.importData(AndroidModuleModelDataService.java:81) at com.android.tools.idea.gradle.project.sync.idea.data.service.ModuleModelDataService$1.run(ModuleModelDataService.java:83) at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:348) at com.intellij.openapi.application.RunResult.run(RunResult.java:35) at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:264) at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1057) at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:263) at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:321) at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220) at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188) at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:323) at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:262) at com.intellij.openapi.command.WriteCommandAction.lambda$execute$0(WriteCommandAction.java:248) at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionAndWait$2(TransactionGuardImpl.java:165) at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88) at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419) at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403) at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762) at java.awt.EventQueue.access$500(EventQueue.java:98) at java.awt.EventQueue$3.run(EventQueue.java:715) at java.awt.EventQueue$3.run(EventQueue.java:709) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) at java.awt.EventQueue.dispatchEvent(EventQueue.java:732) at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:755) at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:704) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391) at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) --------------Kill trace: java.lang.Throwable at com.intellij.openapi.util.TraceableDisposable.kill(TraceableDisposable.java:49) at com.intellij.openapi.roots.impl.libraries.LibraryImpl.dispose(LibraryImpl.java:144) at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48) at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44) at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138) at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107) at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:193) at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107) at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:157) at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129) at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125) at com.intellij.openapi.roots.impl.libraries.LibraryTableBase$LibraryModel.removeLibrary(LibraryTableBase.java:320) at com.intellij.openapi.externalSystem.service.project.manage.LibraryDataService.postProcess(LibraryDataService.java:218) at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.lambda$doImportData$2(ProjectDataManagerImpl.java:325) at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.importData(ProjectDataManagerImpl.java:173) at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.importData(ProjectDataManagerImpl.java:253) at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.importData(ProjectDataManagerImpl.java:260) at com.android.tools.idea.gradle.project.sync.idea.IdeaSyncPopulateProjectTask.doPopulateProject(IdeaSyncPopulateProjectTask.java:121) at com.android.tools.idea.gradle.project.sync.idea.IdeaSyncPopulateProjectTask.populate(IdeaSyncPopulateProjectTask.java:98) at com.android.tools.idea.gradle.project.sync.idea.IdeaSyncPopulateProjectTask.access$000(IdeaSyncPopulateProjectTask.java:40) at com.android.tools.idea.gradle.project.sync.idea.IdeaSyncPopulateProjectTask$1.run(IdeaSyncPopulateProjectTask.java:87) at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151) at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403) at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) -------------Own trace: com.intellij.openapi.util.TraceableDisposable$DisposalException: 1539746852 at com.intellij.openapi.util.TraceableDisposable.getStackTrace(TraceableDisposable.java:136) at com.intellij.openapi.roots.impl.libraries.LibraryImpl.checkDisposed(LibraryImpl.java:149) at com.intellij.openapi.roots.impl.libraries.LibraryImpl.getFiles(LibraryImpl.java:175) at org.jetbrains.kotlin.idea.framework.JavaRuntimeDetectionUtil.getJavaRuntimeVersion(JavaRuntimeDetectionUtil.java:34) at org.jetbrains.kotlin.idea.core.platform.impl.JvmIdePlatformKindTooling$getLibraryVersionProvider$1.invoke(JvmIdePlatformKindTooling.kt:53) at org.jetbrains.kotlin.idea.core.platform.impl.JvmIdePlatformKindTooling$getLibraryVersionProvider$1.invoke(JvmIdePlatformKindTooling.kt:31) at org.jetbrains.kotlin.idea.facet.KotlinVersionInfoProviderByModuleDependencies$getLibraryVersions$1.invoke(KotlinVersionInfoProviderByModuleDependencies.kt:40) at org.jetbrains.kotlin.idea.facet.KotlinVersionInfoProviderByModuleDependencies$getLibraryVersions$1.invoke(KotlinVersionInfoProviderByModuleDependencies.kt:27) at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172) at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132) at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156) at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:702) at kotlin.sequence ...

```

**Comment by ben-manes** [comment]
This plugin is not listed in your stacktrace.
