### ISSUE TITLE
Does this work with multi module projects? How?

### ISSUE THREAD

**Issue by schauder** [ben-manes/gradle-versions-plugin#32]
I tried to use the plugin on a multi module project, but I keep getting the error message 

```
Task 'dependencyUpdates' not found in root project 'degraph'.
```

degraph being the project I'm trying to use it on.

The complete setup is on github: https://github.com/schauder/degraph/tree/versions-plugin-problem

**Comment by sibeliusseraphini** [comment]
@schauder how have u fixed this?

**Comment by schauder** [comment]
Judging from my last commit I forgot the apply statement, for actually pulling in the plug-in.
So I guess I added that.

Maybe it was only in the top level project but not all the sub modules. you might want to look in the referenced repository for commits I made back then.
