### ISSUE TITLE
Gradle plugin interactive as additional tool link

### ISSUE THREAD

**Issue by kevcodez** [ben-manes/gradle-versions-plugin#323]
I recently built https://github.com/kevcodez/gradle-upgrade-interactive - an interactive cli to upgrade gradle dependencies and wrapper. It is building upon this gradle versions plugin. I'd appreciate, if you'd list it as an additional tool, like the other plugins. Before directly sending a PR, I just wanted to check if there are any other requirements and if the tool I built is worthy of listing. Let me know if that's fine and I will send a PR.

**Comment by ben-manes** [comment]
Seems nifty. I don't use any of those tools listed, but obviously the authors found them useful and they were nice enough to share their work. So I see no reason not to list yours too, which seems pretty slick.

For the list's sort order, it is just looking pretty from long names to short so not a jaggad list.

**Comment by kevcodez** [comment]
:beers: Sending a PR when Im home
