### ISSUE TITLE
Still getting "Could not resolve" for all dependencies

### ISSUE THREAD

**Issue by jimshowalter** [ben-manes/gradle-versions-plugin#336]
Running Gradle 5.6.1. Upgraded ben-manes to 0.24.0. Getting same resolution of no dependencies reported in https://github.com/ben-manes/gradle-versions-plugin/issues/331.

**Comment by ben-manes** [comment]
Can you provide your build file, etc to debug with?

**Comment by jimshowalter** [comment]
`buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.github.ben-manes:gradle-versions-plugin:0.24.0'
    }
}

apply plugin: 'idea'
apply plugin: 'java'

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    testImplementation 'org.mockito:mockito-core:3.0.0'
}

apply plugin: 'com.github.ben-manes.versions'
// configure gradle-versions-plugin
dependencyUpdates.resolutionStrategy {
    componentSelection { rules ->
        rules.all {
            def isNonStable = { String version ->
                ['alpha', 'beta', 'rc', 'cr', 'pr', 'm', 'preview', 'b', 'ea'].any { qualifier ->
                    version ==~ /(?i).*[.-]\$qualifier[.\\d-+]*/
                }
            }
            if (isNonStable(candidate.version) && !isNonStable(currentVersion)) {
                selection.reject('Release candidate')
            }
        }
    }
}
// run dependencyUpdates on build
build.finalizedBy dependencyUpdates
`

**Comment by jimshowalter** [comment]
Running ./gradlew dependencyUpdates --info dumps out:
Failed to determine the latest version for the following dependencies (use --info for details):
 - com.github.ben-manes:gradle-versions-plugin
The exception that is the cause of unresolved state: Could not resolve com.github.ben-manes:gradle-versions-plugin:+.
 - org.mockito:mockito-core
The exception that is the cause of unresolved state: Could not resolve org.mockito:mockito-core:+.

Gradle release-candidate updates:
 - Gradle: [5.6.1: UP-TO-DATE]
The exception that is the cause of unresolved state: Could not resolve com.github.ben-manes:gradle-versions-plugin:+.
The exception that is the cause of unresolved state: Could not resolve org.mockito:mockito-core:+.

Generated report file build/dependencyUpdates/report.txt
:dependencyUpdates (Thread[Execution worker for ':',5,main]) completed. Took 0.38 secs.

**Comment by ben-manes** [comment]
There was a typo in the older README. Can you change to something like,

```gradle
dependencyUpdates.resolutionStrategy {
  componentSelection {
    all {
      def isNonStable = { String version -> 
        ['alpha', 'beta', 'rc', 'cr', 'm', 'preview', 'b', 'ea'].any { qualifier ->
          version ==~ /(?i).*[.-]$qualifier[.\d-+]*/
        }
      }

      if (isNonStable(candidate.version) && !isNonStable(currentVersion)) {
        reject('Release candidate')
      }
    }
  }
}
```

**Comment by jimshowalter** [comment]
That was easy. I tried following the threads in the bug reports but got lost.

By the way, we've run into some open-source projects that use "pr" to indicate pre-release, so you might want to add 'pr' to the filter list above.

**Comment by ben-manes** [comment]
haha, so many variations and almost none following Maven's versioning rules...

**Comment by jimshowalter** [comment]
Too true.
