### ISSUE TITLE
Version fetching for dependencies without jarfiles fails successfully

### ISSUE THREAD

**Issue by serebit** [ben-manes/gradle-versions-plugin#342]
This is an odd one. If a dependency is added that links to an artifact with only a POM and `module` file, such as a Kotlin multiplatform metadata artifact (e.g. [this one in jcenter, of which I am the owner](https://dl.bintray.com/bintray/jcenter/com/serebit/logkat/logkat/0.4.7/)), the version fetching will fail successfully. That is, it will correctly fetch the latest version of the artifact, but will still say that the version fetching failed:
```
Failed to determine the latest version for the following dependencies (use --info for details):
 - com.serebit.logkat:logkat
     0.4.7
```
This happens with both jcenter and Maven Central.

**Comment by ben-manes** [comment]
From other discussions, this is most likely due to variant selection of the `.module` metadata. We now copy the attributes over for resolution, but I think there might be a few more gaps to uncover. It sounded like that resolved your issues from the other ticket, so closing for now.
