### ISSUE TITLE
Task execution time is too long

### ISSUE THREAD

**Issue by Yang-yongwen** [ben-manes/gradle-versions-plugin#343]
There are many dependencies in my app ， which cause task execution time so long. I check the dependencyUpdates source code , it use  gradle dependency dynamic version with Configuration#getResolvedConfiguration() to find the latest version of dependencies. I found that Configuration#getResolvedConfiguration() will locates and downloads the file from repository, which may be the reason of long execution time, is there any way we can only locates the latest version of dependencies without download it, like android studio lint suggest dependencies has new version .

**Comment by ben-manes** [comment]
I don't believe the task downloads the dependency artifact, but does fetch the metadata xml files. Unfortunately Gradle does not parallelize this, so it performs the work sequentially and against every repository that you have configured. A fix has to come from Gradle.

I have experienced this being very slow when using Sonatype's snapshot repository, which rate limits. Otherwise in my experience it has been slow but usable, and some defer to a scheduled CI task to hide this entirely.

A recent improvement, [matching repositories to dependencies](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec::matching_repositories_to_dependencies), could be beneficial to you. This would avoid resolving all of your dependencies against a slow custom repository which you use for an explicit artifact.

**Comment by Yang-yongwen** [comment]
Thanks for your suggestion. The comment of Configuration#getResolvedConfiguration() as below:

        /**
         * Resolves this configuration. This locates and downloads the files which make up this configuration, and returns
         * a {@link ResolvedConfiguration} that may be used to determine information about the resolve (including errors).
         *
         * @return The ResolvedConfiguration object
         */
        ResolvedConfiguration getResolvedConfiguration();

maybe it works as you said that just fetch the metadata xml files without downloading dependency artifact. I will try matching repositories to dependencies. thanks again.

**Comment by boris-petrov** [comment]
@ben-manes - this started happening to me also in the past few weeks. Not sure what changed but now `gradle dependencyUpdates` takes more than 30 minutes to complete. Any ideas?

**Comment by ben-manes** [comment]
Have you added new repositories or changed your version timeouts (`cacheDynamicVersionsFor`)? You can use `--info` to see what gradle is doing during the analysis, e.g. maybe it is rejecting many versions which is sequentially traverses?

**Comment by boris-petrov** [comment]
@ben-manes - sorry for the late reply. I see this when running with `--info`:

```
Resource missing. [HTTP HEAD: https://nodejs.org/dist/v15.8.0/tomcat-annotations-api.jar]
Selection of org.apache.tomcat:tomcat-annotations-api:15.8.0 rejected by component selection rule: Release candidate
Resource missing. [HTTP HEAD: https://nodejs.org/dist/v15.7.0/tomcat-annotations-api.jar]
Selection of org.apache.tomcat:tomcat-annotations-api:15.7.0 rejected by component selection rule: Release candidate
...
```

This happens for *every* version of `node.js` and for some (a lot? all?) artifacts. I use [gradle-node-plugin](https://github.com/node-gradle/gradle-node-plugin) and I remember recently updating it from a stable version 2.2.4 to 3.0-RC. Do you think that this could be the issue? Is it on their side or something in `gradle-versions-plugin`?

**Comment by ben-manes** [comment]
Yeah, that's definitely the culprit. Maybe ask them to add the repository with [content filtering](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:supported_metadata_sources). This way the repository could be annotated as not supporting Maven / Ivy / Gradle metadata, allowing for faster resolution when Gradle knows it can be skipped. There might also be a regex pattern to avoid Maven-style coordinates as well.

In your build, you could exclude the repository when generating the dependency report. This will remove it so a full build might fail, but if only running our task then it should allow you to skip the evaluation safely. Something like,
```gradle
tasks.dependencyUpdates.doFirst {
    project.repositories.removeAll { it.url == '...' }
}
```

I think them refining their repository handling would be nice all around improvement, and the stop-gap of the local build change should make it fast without much headaches.

**Comment by boris-petrov** [comment]
@ben-manes - thank you for the great support as always! I've pinged them and I'll try the workaround. Thanks again!
