### ISSUE TITLE
Support Android buildToolsVersion

### ISSUE THREAD

**Issue by johnjohndoe** [ben-manes/gradle-versions-plugin#345]
# Context

Android projects can configure the `buildToolsVersion` as follows:

``` gradle
android {
    buildToolsVersion "29.0.2"
    ...
}
```

Typically developers download the different version via the built-in _SDK Manager_ of Android Studio as shown in the following screenshot:

![SDK Manager of Android Studio](https://user-images.githubusercontent.com/144518/65815462-127b9380-e1f0-11e9-81b4-0e05fc3e2a4f.png)

# Feature request

- It would be great to have the plugin also report versions of the build tools.

# To be answered
- Where (maven repository?) can the plugin look-up available versions of the build-tools?

# Related
- [SDK Build Tools release notes](https://developer.android.com/studio/releases/build-tools)

**Comment by jmfayard** [comment]
I thought it was not necessary anymore to specify the buildToolsVersions in recent releases of AGP

**Comment by johnjohndoe** [comment]
That is correct. But you can.

**Comment by jmfayard** [comment]
Note that you can put all those Android versions in the Gradle properties, it's pretty handy
https://dev.to/jmfayard/configuring-gradle-with-gradle-properties-211k

**Comment by johnjohndoe** [comment]
Thank you. Yes, I am aware of this. I prefer to use the `buildSrc` folder to manage dependencies. - It would be the responsibility of this plugin to resolve the version from all these locations.

**Comment by jmfayard** [comment]
So first step would be to find out wherever you can find the dependency that correspond to the build tools in the man repository `google()`

Then you just need to add the dependency to your build, not add as a `implementation` dependency, but something else that is not used. The Gradle versions plug-in should then be able to find available updates
@johnjohndoe

**Comment by johnjohndoe** [comment]
I could not find the build tools at http://maven.google.com. @jmfayard, do you have a clue where they serve it?

**Comment by gabrielittner** [comment]
It's not a maven dependency. It's part of the sdkmanager. The source for that is this XML file http://dl.google.com/android/repository/repository2-1.xml

Personally I wouldn't bother with adding support for it. Most of the things in build-tools isn't used at all by Gradle builds anymore because the Android Gradle Plugin just includes these tools directly. The two main things still in use are aidl and renderscript.

**Comment by jaredsburrows** [comment]
@johnjohndoe Since the Android Gradle Plugin  does not require `buildToolsVersion` anymore and it auto downloads the build tools, what value does this bring to the plugin? Can we close this?

**Comment by johnjohndoe** [comment]
Yes, I think we can close this. The amount of projects which still define the specific version should be very low. Thanks for the cleanup.
