### ISSUE TITLE
Resolve versions in a java-platfom project

### ISSUE THREAD

**Issue by anuraaga** [ben-manes/gradle-versions-plugin#350]
I usually manage dependency versions in a repo with many Gradle projects by having one `java-platform` project that uses `dependencies.constraints` to force versions in other projects. Currently, I usually run `dependencyUpdates` on the entire repo, meaning for all the subprojects, but it would be convenient to be able to just run `:project-bom:dependencyUpdates` to resolve updates to the constraint dependencies. Is this a feature that's appropriate for this plugin?

**Comment by ben-manes** [comment]
You can apply the plugin only to the bom project if you prefer. Does that work?

**Comment by anuraaga** [comment]
Since enforcing versions in a bom project uses `dependencies.constraints` instead of `dependencies`, I don't think the plugin is able to pick up the dependencies to process. I suspect it's a pretty small change to look at `constraints` when it's present, wanted to confirm it makes sense as a change :)

**Comment by jmfayard** [comment]
If I remember correctly, the Gradle team suggested to refactor the plug-in to have one dependency task per project and then merge their results at the end? Is that correct @ben-manes
If so, what you propose would be really welcome, but also maybe non trivial

**Comment by ben-manes** [comment]
@jmfayard yes, though I think the ask is to look at another property as well for a configuration to evaluate. The per project task is different in that they are changing best practices from 1.x days to improve parallelism and caching. Here I think it’s just applying to a sub project and evaluating dependencies differently.

@anuraaga you can give it a shot. Gradle changes so much that I don’t know anymore what is good or bad practices. It would seem like a potentially confusing addition in other cases, so I don’t know if it’s a good or bad addition.
