### ISSUE TITLE
Revert wrong regex changes

### ISSUE THREAD

**Issue by Vampire** [ben-manes/gradle-versions-plugin#354]
The commit 1e6591bd3a91a53e60b33f40ee90807f3bc8f490 should be reverted, or at least the added backslashes removed.

- A dot within a character class (`[.]`) looses its special meaning and is just a dot
- A dash as first or last element of a character class (`[abc-]`, `[-abc]`) looses its special meaning and is just a dash

Escaping them in Kotlin (readme and example) is just superfluous and noise for the reader.
`"^[0-9,.v-]+$".toRegex()` and `"^[0-9,\\.v\\-]+$".toRegex()` result in the exact same matches, as the second compiles to the regex `"^[0-9,\.v\-]+$` and as the dot and dash have no special meaning the backslashes are simply ignored.

In Groovy the problem is even worse, as within a slashy string `/.../` backslashes loose their special meaning except for one case, which is escaping a slash that would end the slashy string. Due to that these slashy strings are often used for regexes as you don't need to double the backslashes.

This means in Groovy `~/^[0-9,\\.v\\-]+(-r)?$/` compiles to the regex `^[0-9,\\.v\\-]+(-r)?$`, which means that the backslash is an allowed character in the version string. The correct escaping for the Groovy example and readme would be `~/^[0-9,\.v\-]+(-r)?$/` to have the same effect as in the Kotlin examples, but then again the backslashes are ignored, as they escape characters that have no special meaning anyway.

So for correctness and easier readability, those backslashes should be removed again from the examples and readme.

cc @floscher

**Comment by ben-manes** [comment]
Perhaps we should keep the `-r` which seems to be what @floscher originally intended, and then misunderstood to think that the escaping was needed?

**Comment by Vampire** [comment]
I have no strong feelings about the `-r`, especially as it is just an example people can modify.
That's why I said "at least remove the backslashes", while I recognized the `-r` being added too. :-)
