### ISSUE TITLE
skip includeBuild when running dependencyUpdates

### ISSUE THREAD

**Issue by memelet** [ben-manes/gradle-versions-plugin#356]
I'm trying to find a way to _not_ run includeBuild when running the dependencyUpdates tasks. 

If the local builds are included I get their SNAPSHOT versions and dependencyCheck never even reports against the actual version that will be seen during CI build.

```
if (!?????) {
	if (startParameter.searchUpwards) {
	  if (file('../spring-metrics').exists()) {
	    includeBuild '../spring-metrics'
	  }
	  if (file('../gradle-java').exists()) {
	    includeBuild '../gradle-java'
	  }
	}
}
```

**Comment by memelet** [comment]
I can achieve this, but only by explicitly passing a -PskipIncludeBuilds=true and using a conditional like `!startParameter.projectProperties.hasProperty('skipIncludeBuild')`

But it would be cleaner if I could just detect if dependencyUpdates was the only task running.

**Comment by ben-manes** [comment]
You could use `gradle.startParameter.taskNames` to detect (or maybe `gradle.taskGraph.hasTask(tasks.dependencyUpdates)` but it is at the end of the lifecycle). I haven't worked with composite builds and my Gradle knowledge is rusty.

**Comment by memelet** [comment]
I when down checking the graph and it seemed it was not resolved at the time includeBuild is run. 

As it turns out, I need to skip for some other tasks as well. So the -P in saved intellij run configs is gonna have to do it. 

It's not a problem during CI build the the relative projects don't exist. 

Thanks!!
