### ISSUE TITLE
Gradle-versions-plugin's version resolution is interfered by resolutionStrategy

### ISSUE THREAD

**Issue by suztomo** [ben-manes/gradle-versions-plugin#361]
I'm troubleshooting [BEAM-8654](https://issues.apache.org/jira/projects/BEAM/issues/) where BEAM's dependency update check does not see newer versions available in Maven Central.

By trimming irrelevant components, I managed to create minimum code to reproduce the problem:

My build.gradle"
```
plugins {
    id 'java'
    id "com.github.ben-manes.versions" version "0.27.0"
}

group 'suztomo'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile "com.google.cloud.bigtable:bigtable-client-core:1.8.0"
}

// This resolutionStrategy is not intended for Gradle versions plugin, but to
// prefer Beam project's recommended versions to Gradle's default reoslution
// algorithm
configurations.compile.resolutionStrategy {
    force(["com.google.cloud.bigtable:bigtable-client-core:1.8.0"])
}
```

This shows:

```
> Task :dependencyUpdates

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.27.0
 - com.google.cloud.bigtable:bigtable-client-core:1.8.0
...
```

However, `com.google.cloud.bigtable:bigtable-client-core` has newer version 1.12.1 in Maven Central.

The `resolutionStrategy` statement is not for Gradle versions plugin. This has been added to Beam's build.gradle to pick up Beam's preferred library versions rather than Gradle's default dependency resolution algorithm([as per the comment in BeamModulePlugin](https://github.com/apache/beam/blob/master/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L1227)). Unfortunately this `resolutionStrategy` is interfering Gradle versions plugin and prevents it from reporting the latest versions of its libraries.

Do you know good way to avoid this interference?

**Comment by ben-manes** [comment]
We honor the original resolutionStrategy as some users expressed wanting that in complex builds. There didn't seem to be a right answer other than honor their build and add conditioning.

Something like the following tends to work.
```groovy
gradle.taskGraph.whenReady { taskGraph ->
  if (!taskGraph.hasTask(dependencyUpdates)) {
    configurations.compile.resolutionStrategy {
      force(["com.google.cloud.bigtable:bigtable-client-core:1.8.0"])
    }
  }
}
```

**Comment by suztomo** [comment]
Thank you for quick response! I'll need to learn more about Gradle by myself. I just got

```
Failed to notify task execution graph listener.
> Cannot change strategy of configuration ':sdks:java:extensions:sql:fmppTemplates' after it has been resolved.
> Cannot change strategy of configuration ':sdks:java:extensions:sql:jdbc:shadowTestRuntimeClasspath' after it has been resolved.

```

Closing this.

**Comment by ben-manes** [comment]
Gradle changes quite a bit so maybe that trick doesn't work anymore.

You can also try `gradle.startParameter.taskName`,
```groovy
if (!gradle.startParameter.taskNames.contains('dependencyUpdates')) { ... }
```

**Comment by suztomo** [comment]
`Gradle.startParameter.taskName` worked for me. Thank you.

**Comment by calvarez-ov** [comment]
I seem to have discovered an issue with this workaround 
```gradle
if (!gradle.startParameter.taskNames.contains('dependencyUpdates')) { ... }
```

It seems that this causes ben-manes to not know what versions of the project we're currently using.

I just noticed today, with this scenario:
* Android gradle plugin 7.0.0, which wants to use jacoco `0.8.3`
* I use a `resolutionStrategy` to force jacoco `0.8.7`.  I see this works by running the `./gradlew :module:dependencies` task
* If I run ben-manes, though, it complains that I'm on the old jacoco, presumably because my resolution strategy isn't applied 🤔 :
    ```
    The following dependencies have later release versions:
     - org.jacoco:org.jacoco.ant [0.8.3 -> 0.8.7]
         http://jacoco.org
    ```
