### ISSUE TITLE
Release revision still shows alpha version for slf4j-simple

### ISSUE THREAD

**Issue by Xerus2000** [ben-manes/gradle-versions-plugin#373]
Using version 0.27.0

For slf4j-simple, even when specifying the `-Drevision=release` flag, it shows me the alpha-version:
```
 - org.slf4j:slf4j-simple [1.7.26 -> 2.0.0-alpha1]
     http://www.slf4j.org
```

**Comment by Xerus2000** [comment]
Seems to be because of how slf4j publishes its versions: https://jira.qos.ch/browse/SLF4J-484?jql=

But isn't there already some way of filtering that uses keywords such as alpha and beta?

**Comment by ben-manes** [comment]
Yes, the revision is an Apache Ivy concept would a bit different. You can use a selection rule to filter
https://github.com/ben-manes/gradle-versions-plugin#revisions
