### ISSUE TITLE
False update report for library which hasn't been released yet

### ISSUE THREAD

**Issue by Nimrodda** [ben-manes/gradle-versions-plugin#376]
It seems the plugin is reporting a new version for libraries that haven't been released yet. For example, one gradle plugin I'm using, has updated its changelog with a new version but hasn't yet tagged the new release nor published. It seems your plugin is reading changelogs as well? :D

**Comment by ben-manes** [comment]
We just call the Gradle dependency apis, so it must be in one of your repositories (local? jitpack?).

**Comment by Nimrodda** [comment]
Oh yes that might be for one of the cases. Another case was for Android arch libraries. It was showing there's version 2.2.0 but there are no such.

**Comment by ben-manes** [comment]
Gradle queries each repository which will have a `maven-metadata.xml` if the dependency is hosted there. See this [example](https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/) on Maven Central. Someone had to have deployed a release to one of your repositories. We don't actually do anything ourselves and just ask Gradle what version `abc:xyz:+` resolves to.
