### ISSUE TITLE
Task useLatestVersions, support dependencies -> implementation enforcedPlatform(...)

### ISSUE THREAD

**Issue by SchulteMarkus** [ben-manes/gradle-versions-plugin#379]
I got a dependency definition

```gradle
dependencies {
  implementation enforcedPlatform("io.quarkus:quarkus-universe-bom:1.2.1.Final")
```

Running ```gradle useLatestVersions``` does not update this dependency, although it should be for time being.

**Feature request**: An enforcedPlatform in dependencies -> implementation is getting updated, too.

**Comment by ben-manes** [comment]
We don’t provide the `useLatestVersions` task. That’s from
https://github.com/patrikerdes/gradle-use-latest-versions-plugin

**Comment by SchulteMarkus** [comment]
Oh, äh, thanks for feedback!
I created https://github.com/patrikerdes/gradle-use-latest-versions-plugin/issues/40
