### ISSUE TITLE
Ignore local libraries(*.aar)

### ISSUE THREAD

**Issue by nuhkoca** [ben-manes/gradle-versions-plugin#380]
Hello,

I have several Android libraries in libs folder.

I want to ignore manually imported .aar libraries for checking. Is there any way?

Thanks,

**Comment by ben-manes** [comment]
I believe they would be listed as unresolvable. You can either ignore that in the console report or write a custom output formatter which excludes those results. For example, pass the results into the text formatter after scrubbing the results of the aar cases.

**Comment by nuhkoca** [comment]
Yes, this is possible but the task takes a long time to end up because of these libraries. I just wondered whether or not completely ignore such libs. Having a custom output formatter is the only solution?

**Comment by ben-manes** [comment]
The cleanest would be to declare the inclusive / exclusive repository content. This will instruct Gradle to not search all of your repositories for a given dependency, which should speed up the task.

https://docs.gradle.org/6.2/userguide/declaring_repositories.html#sec:repository-content-filtering

**Comment by nuhkoca** [comment]
Thanks for your time. I will try it out. I hope I will have a satisfied result.
