### ISSUE TITLE
Refresh the dependencies info

### ISSUE THREAD

**Issue by benckx** [ben-manes/gradle-versions-plugin#384]
I pushed some new versions of my libs on the company Nexus, but the plugin doesn't seem to see it. Is there a way to refresh the dependencies info or clean the cache or something?

I tried deleting all the `com.github.ben-manes` items in `/.gradle` but it didn't work.

```
The following dependencies exceed the version found at the milestone revision level:
 - com.mycompany:my-super-lib [1.0.13 <- 1.0.12]
```

**Comment by ben-manes** [comment]
Can you try —refresh-dependencies? This will bypass the Gradle cache and make a remote lookup.

**Comment by benckx** [comment]
Yes, that works, thanks. Maybe it should be added to the README.

**Comment by ben-manes** [comment]
Feel free to send a PR with suggested wording 😀
