### ISSUE TITLE
Unresolved dependencies when hosted in an internal binary repo

### ISSUE THREAD

**Issue by RoRoche** [ben-manes/gradle-versions-plugin#391]
Is there a way to add repository where to find unresolved dependencies?

**Comment by ben-manes** [comment]
To your repositories block? We resolve using Gradle’s apis.

**Comment by RoRoche** [comment]
I don't know if my repository blocks anything 😥
Do you have an example showing how you solve it using Gradle's API ?

**Comment by ben-manes** [comment]
If you add —info then you’ll see our log messages. Likely there is a configuration issue that is too strict. If you want to see our logic it is in the Resolver class.

**Comment by RoRoche** [comment]
OK thanks.

**Comment by RoRoche** [comment]
OK thanks. 
The search location are OK.
The message is:

```
The exception that is the cause of unresolved state: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find any version that matches myorg.myproj:mylib:+.
Versions rejected by component selection rules:
  - 1.0.0-SNAPSHOT
```

**Comment by ben-manes** [comment]
Do you have any releases? The default revision is milestones, which disallows snapshots. If you release a version or change to integration then it should resolve
