### ISSUE TITLE
Check updates for desugar_jdk_libs?

### ISSUE THREAD

**Issue by Mygod** [ben-manes/gradle-versions-plugin#393]
The plugin does not seem to prompt updates for the following library: https://github.com/google/desugar_jdk_libs

**Comment by ben-manes** [comment]
Google's repository and publishing do not follow the requirements of a maven repository. They disallow directory listing of the artifact and return 404, which is how Gradle determines if it is a Maven or Ivy repository to query the metadata for. The metadata and jar is available by point query, but their overly restrictive security settings make it invalid from a Maven standard perspective. Good luck getting them to fix this.

**Comment by Mygod** [comment]
mvnrepository.com seems to somehow get around that issue but I'm not sure: https://mvnrepository.com/artifact/com.android.tools/desugar_jdk_libs

**Comment by Mygod** [comment]
Actually I think this is a separate issue.

I don't think the plugin is even aware of this dependency as it is included via a special command like `coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:1.0.5"`.

**Comment by ben-manes** [comment]
oh? We do look at all configurations. Do you see it in `--dependencies`? We let Gradle resolve using a `+` version to compare against.

**Comment by Mygod** [comment]
Yep but only under one task.

```
coreLibraryDesugaring - Configuration to desugar libraries
\--- com.android.tools:desugar_jdk_libs:1.0.5
     \--- com.android.tools:desugar_jdk_libs_configuration:0.11.1
```

Thanks for the timely response btw!

**Comment by Mygod** [comment]
I am suspecting that this is the issue as the plugin does not seem to report `desugar_jdk_libs` is up to date either in `report.txt`.

**Comment by ben-manes** [comment]
It looks like this is due to how their configuration is setup. Gradle added concepts that disallow resolving some configurations. We used to hack around this, but their platform feature made it incompatible (e.g. resolving kotlin multi-platform dependencies would break). If you use `0.27.0` then our prior hacks to let this be resolved.

```
 - com.android.tools:desugar_jdk_libs [1.0.4 -> 1.0.5]
     https://github.com/google/desugar_jdk_libs
```

The condition that we added in the last release is filtering this configuration out.

https://github.com/ben-manes/gradle-versions-plugin/blob/a1e4bf3993292ed8f6d60e3f6b8e7cadaae72786/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy#L71-L72

**Comment by ben-manes** [comment]
You could ask the Android plugin authors to enable canBeConsumed. It's a bit confusing...
https://docs.gradle.org/current/userguide/declaring_dependencies.html

**Comment by Mygod** [comment]
Could you make an issue at Google's bug tracker? Sounds like you know more about this than I do. :)

**Comment by Mygod** [comment]
It seems like Google's lint can correctly identify when this library is out of date though: https://451-116107171-gh.circle-artifacts.com/0/reports/lint-results.html#GradleDependency

**Comment by ben-manes** [comment]
Google's lint is a hard coded lookup for common Android dependencies. For some reason they didn't resolve through Gradle, like we do, but instead just hacked a few http calls to check for specific versions.

If you can use lint as a backup, that's a nice solution for now.

**Comment by gm-vm** [comment]
I noticed the same problem when I updated AGP to the latest stable version, given that it was not compatible with the version of `desugar_jdk_libs` I was using. I solved the problem with a custom configuration:

```groovy
configurations {
    dependencyUpdatesConfig {
        canBeResolved = false
        canBeConsumed = true
    }
}

dependencies {
    dependencyUpdatesConfig "com.android.tools:desugar_jdk_libs:xxx"
}
```
