### ISSUE TITLE
org.jetbrains.kotlin:kotlin-stdlib-jdk8 [1.3.72 <- 1.3.71] Why?

### ISSUE THREAD

**Issue by frist008** [ben-manes/gradle-versions-plugin#395]
Sorry, I don’t understand why this is happening.
```
The following dependencies exceed the version found at the milestone revision level:
 - org.jetbrains.kotlin:kotlin-allopen [1.3.72 <- 1.3.71]
     https://kotlinlang.org/
 - org.jetbrains.kotlin:kotlin-android-extensions [1.3.72 <- 1.3.71]
     https://kotlinlang.org/
 - org.jetbrains.kotlin:kotlin-android-extensions-runtime [1.3.72 <- 1.3.71]
     https://kotlinlang.org/
 - org.jetbrains.kotlin:kotlin-annotation-processing-gradle [1.3.72 <- 1.3.71]
     https://kotlinlang.org/
 - org.jetbrains.kotlin:kotlin-gradle-plugin [1.3.72 <- 1.3.71]
     https://kotlinlang.org/
 - org.jetbrains.kotlin:kotlin-stdlib-jdk8 [1.3.72 <- 1.3.71]
     https://kotlinlang.org/
```

Android studio 2.6.3 
com.android.tools.build:gradle:3.6.3
com.github.ben-manes:gradle-versions-plugin:0.28.0

```
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
    }
```

**Comment by ben-manes** [comment]
Please add `mavenCentral()` to your list.

JCenter proxies explicit versions to Central to cache them. However dynamic version queries, `+`, are not proxied and they often contain stale information. This means you can download the version and build fine, but a query to find the latest is given old versions. See their [listing](https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-android-extensions-runtime) for your dependency which is stale.

**Comment by frist008** [comment]
Yes, that solved the problem! Thank.

Hmm, maybe you should add this solution to README?

**Comment by ben-manes** [comment]
Sure, PRs are welcome 😉

**Comment by frist008** [comment]
I think the Readme update for a non-native speaker is fraught with errors and this is not a good idea=) Therefore, I will refrain.
