### ISSUE TITLE
gradle update check fails for mirrored or in-house distributions

### ISSUE THREAD

**Issue by childnode** [ben-manes/gradle-versions-plugin#397]
https://github.com/ben-manes/gradle-versions-plugin/blob/4ef630704cc7db03462dcb04076f83841946dd4e/src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateChecker.groovy#L21
+
https://github.com/ben-manes/gradle-versions-plugin/blob/4ef630704cc7db03462dcb04076f83841946dd4e/src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateChecker.groovy#L37

fails with 
```
[ERROR] [release channel: current] Unable to process url: https://services.gradle.org/versions/current
```

relates to #396

**Comment by ben-manes** [comment]
In that case you would disable using the `checkForGradleUpdate` settings.

**Comment by ben-manes** [comment]
Closing, as I don't think anyone mirrors the update api, so disabling is the only option.
