### ISSUE TITLE
Support for Java Platform plugin?

### ISSUE THREAD

**Issue by rdehuyss** [ben-manes/gradle-versions-plugin#399]
I'm on the latest version of Gradle (6.4.1) and your plugin (0.28).

I'm using the JavaPlatform plugin. For a lot of the dependencies, I see `none` as version. If it is `none`, it also does not show that there is a possible upgrade.

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest release version:
 - com.fasterxml.jackson.core:jackson-databind:none
 - com.fasterxml.jackson.datatype:jackson-datatype-jsr310:none
 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.28.0
 - com.google.cloud.sql:postgres-socket-factory:none
 - com.google.cloud.tools.jib:com.google.cloud.tools.jib.gradle.plugin:2.3.0
 - com.google.code.gson:gson:none
 - com.h2database:h2:none
 - com.jfrog.bintray:com.jfrog.bintray.gradle.plugin:1.8.5
 - com.mchange:c3p0:none
 - com.microsoft.sqlserver:mssql-jdbc:none
 - com.oracle.ojdbc:ojdbc8_g:none
 - com.zaxxer:HikariCP:none
 - mysql:mysql-connector-java:none
 - net.javacrumbs.json-unit:json-unit-assertj:2.17.0
 - org.apache.commons:commons-dbcp2:none
 - org.apache.tomcat:tomcat-jdbc:none
 - org.assertj:assertj-core:none
 - org.awaitility:awaitility:4.0.3
 - org.jobrunr:jobrunr:0.9.7
 - org.junit.jupiter:junit-jupiter:none
 - org.mariadb.jdbc:mariadb-java-client:none
 - org.mockito:mockito-core:3.3.3
 - org.mockito:mockito-junit-jupiter:3.3.3
 - org.mongodb:mongo-java-driver:none
 - org.ow2.asm:asm:8.0.1
 - org.ow2.asm:asm-util:8.0.1
 - org.postgresql:postgresql:none
 - org.sonarqube:org.sonarqube.gradle.plugin:2.8
 - org.testcontainers:jdbc:1.14.2
 - org.testcontainers:junit-jupiter:1.14.2
 - org.testcontainers:mariadb:1.14.2
 - org.testcontainers:mssqlserver:1.14.2
 - org.testcontainers:mysql:1.14.2
 - org.testcontainers:oracle-xe:1.14.2
 - org.testcontainers:postgresql:1.14.2
 - org.testcontainers:testcontainers:1.14.2
 - org.xerial:sqlite-jdbc:none
 - redis.clients:jedis:none

The following dependencies have later release versions:
 - com.microsoft.sqlserver:mssql-jdbc [8.2.2.jre8 -> 8.3.0.jre14-preview]
     https://github.com/Microsoft/mssql-jdbc
 - org.apache.tomcat:tomcat-jdbc [9.0.34 -> 10.0.0-M5]
     https://tomcat.apache.org/
 - org.junit.jupiter:junit-jupiter [5.6.2 -> 5.7.0-M1]
     https://junit.org/junit5/
 - org.slf4j:slf4j-api [1.7.30 -> 2.0.0-alpha1]
     http://www.slf4j.org
 - org.slf4j:slf4j-simple [1.7.30 -> 2.0.0-alpha1]
     http://www.slf4j.org

Gradle release-candidate updates:
 - Gradle: [6.4.1 -> 6.5-rc-1]

Is this something that will be supported?

**Comment by ben-manes** [comment]
`none` is when no version could be resolved, such as a file dependency. For BOMs style syntax it typically corrects to `+` to dynamically resolve. Either the API changed to be detected as a local file artifact or the resolution failed to give us a version number.

Most likely the place to debug is to print out the results here,
https://github.com/ben-manes/gradle-versions-plugin/blob/4ef630704cc7db03462dcb04076f83841946dd4e/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L141-L153

A small, repeatable example would be helpful for investigating and adding a test case.

PRs are welcome if you would like this fixed promptly.

**Comment by anuraaga** [comment]
I've been using this plugin with a platform and it works quite well for me. To confirm, did you add `checkConstraints` to the configuration?

https://github.com/curioswitch/curiostack/blob/master/tools/curiostack-bom/build.gradle.kts#L392

**Comment by napstr** [comment]
I'd like to stress the awesomeness of the previous answer by @anuraaga and add some context where it applied to our build :)

For some reason, with Gradle 6, our project-internally-BOM-versioned dependencies were still evaluated, but with Gradle 7 all the versions became `none` and it was missing showing outdated dependencies.
Adding `checkConstraints = true` did the trick here.

**Comment by jaredsburrows** [comment]
@anuraaga is using this plugin and provided a link. @rdehuyss Feel free to open if you are still having problems.
