### ISSUE TITLE
Custom outputFormatter issue

### ISSUE THREAD

**Issue by Vacxe** [ben-manes/gradle-versions-plugin#403]
I overrode ```outputFormatter``` in ```dependencyUpdates {``` configuration. 
After I trying to call `gradle dependencyUpdates -Drevision=release`
But look like it's using plain text format.

Could you please provide example of how to use  ```outputFormatter``` closure with proper way?

**Comment by ben-manes** [comment]
Does the readme's example help?
https://github.com/ben-manes/gradle-versions-plugin#custom-report-format

**Comment by Vacxe** [comment]
@ben-manes I did it as how in example presented. After I calling `gradle dependencyUpdates -Drevision=release` and results still in plain text format

**Comment by ben-manes** [comment]
hmm, I tried and it printed html to the console.

**Comment by ben-manes** [comment]
For your two issues, I plopped the changes into Caffeine's root build file (a multi-module project) and ran the command...

**Comment by Vacxe** [comment]
@ben-manes solved. Should be configured in 
```
allprojects {
```
section
