### ISSUE TITLE
Multi module project issue

### ISSUE THREAD

**Issue by Vacxe** [ben-manes/gradle-versions-plugin#404]
I'm trying to configure this lib for the multi-module project with Gradle wrapper

```
allprojects {
    ....
    apply plugin: com.github.benmanes.gradle.versions.VersionsPlugin
    dependencyUpdates {
        outputDir = "reports/${project.name}/dependencyUpdates"
    }
}
```

In build log, I can see that 
```
Generated report file reports/<module 1>/dependencyUpdates/report.json
..
Generated report file reports/<module 2>/dependencyUpdates/report.json
...
Generated report file reports/<module 3>/dependencyUpdates/report.json
...
Generated report file reports/<module 4>/dependencyUpdates/report.json
....
```
But in `reports/` directory I can find only one report

**Comment by ben-manes** [comment]
Most likely you will only want to apply the plugin at the root, as it will evaluate all subprojects into a single report.

I tried against all projects and did get multiple reports. The file is at the subproject's `build` dir, e.g. `simulator/build/dependencyUpdates/report.txt`

**Comment by Vacxe** [comment]
@ben-manes cheers mate
