### ISSUE TITLE
Leakcanary new version not found

### ISSUE THREAD

**Issue by benjdero** [ben-manes/gradle-versions-plugin#405]
I have the following dependency in my android project:
`com.squareup.leakcanary:leakcanary-android:2.3`

For unknown reason this plugin does not see there is an updated version (2.4) available.

**Comment by ben-manes** [comment]
It sounds like you are using `jcenter` as your repository. That proxies point queries to Maven Central, but not dynamic queries. This is why Gradle can resolve `2.4` but is told outdated information when using `+`. Their [leakcanary](https://bintray.com/bintray/jcenter/com.squareup.leakcanary%3Aleakcanary-object-watcher-android-support-fragments) artifact is on `2.3` as you observe.

Please include `mavenCentral` in your repository listing.

**Comment by benjdero** [comment]
Yes I only use `jcenter` and `google` as sources because I thought `mavenCentral` wasn't needed as `jcenter` superset it.

So there is no chance your plugin can handle this automatically ?

**Comment by ben-manes** [comment]
We use the repositories in your project's list. This is the most obvious and avoids complaints from those who have internal-only restrictions on their repositories.

JCenter has a lot of quirks and you're better off just including Central for improved reliability.
