### ISSUE TITLE
Lazy task configuration

### ISSUE THREAD

**Issue by MyDogTom** [ben-manes/gradle-versions-plugin#407]
Readme [recommends](https://github.com/ben-manes/gradle-versions-plugin#using-a-gradle-init-script) to configure `dependecyUpdates` task like that:
```
allprojects {
  apply plugin: com.github.benmanes.gradle.versions.VersionsPlugin

  dependencyUpdates {
    // configure the task, for example wrt. resolution strategies
  }
}
```
this enforces task creation during configuration phase regardless that task [was registered lazily](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/VersionsPlugin.groovy#L37).

I suggest to use [`named` method to access task lazily](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskCollection.html#named-java.lang.String-)

```
allprojects {
  apply plugin: com.github.benmanes.gradle.versions.VersionsPlugin

  tasks.named("dependencyUpdates").configure {
    // configure the task, for example wrt. resolution strategies
  }
}
```

Do you have anything against this approach? Should I open a PR with readme changes?

**Comment by ben-manes** [comment]
PRs are very welcome!
(cc @jochenberger)
