### ISSUE TITLE
Only one written .txt report for a multi-project build.

### ISSUE THREAD

**Issue by romacafe** [ben-manes/gradle-versions-plugin#41]
Run dependencyUpdate task from the root of a multi-project build, where the plugin is applied to both the root and all sub projects.

The console output correctly captures all projects, however each project writes to `build/dependencyUpdates/report.txt`, and when I look at that file, it only contains the report for the root project, none of the subs.

I am running with `org.gradle.parallel=true`

**Comment by jochenberger** [comment]
I'll change that so the `outputDir` is resolved within the project.
