### ISSUE TITLE
Modifying `rejectVersionIf` rules shouldn't re-run network calls

### ISSUE THREAD

**Issue by ZakTaccardi** [ben-manes/gradle-versions-plugin#411]
If I modify `rejectVersionIf` rules, then the network call to fetch dependency versions runs again. This causes a long turnaround time when modifying these rules.

Is there a way versions per module can be cached so the download doesn't have to run again?

**Comment by ben-manes** [comment]
We delegate to Gradle, so this is the responsibility of their [dependency resolution cache](https://docs.gradle.org/current/userguide/dependency_resolution.html#sec:dependency_cache).

**Comment by ZakTaccardi** [comment]
Gotcha. I think what was happening is that I changed the version download rules, so "the latest version" changed, which is what gets fetched serially.
