### ISSUE TITLE
Parallelize version fetching

### ISSUE THREAD

**Issue by ZakTaccardi** [ben-manes/gradle-versions-plugin#412]
Each module should execute network quests in parallel for its version, rather than going 1 by 1

**Comment by ben-manes** [comment]
This is a Gradle limitation https://github.com/gradle/gradle/issues/1309 ([GRADLE-2582](https://issues.gradle.org/browse/GRADLE-2582)). They do not support this and required that we requested that we remove parallel workarounds in our code.
