### ISSUE TITLE
Improve reject version speed

### ISSUE THREAD

**Issue by ZakTaccardi** [ben-manes/gradle-versions-plugin#413]
I'm seeing:

```
Selection of org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20-dev-2342 rejected by component selection rule: Rejected by rejectVersionIf
Selection of org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20-dev-2286 rejected by component selection rule: Rejected by rejectVersionIf
Selection of org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20-dev-2250 rejected by component selection rule: Rejected by rejectVersionIf
Selection of org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20-dev-2193 rejected by component selection rule: Rejected by rejectVersionIf
```

With a super long delay between versions. After `15m45s` I've only made it as far as:

```
Selection of org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20-dev-350-225 rejected by component selection rule: Rejected by rejectVersionIf
```

Is there a way to speed this up?

**Comment by ZakTaccardi** [comment]
note: my `rejectVersionIf` logic is as follows:

```groovy
tasks.named("dependencyUpdates").configure {
    def isNonStable = { String version ->
        List<String> unstableKeywords = ['dev-', 'alpha-', 'beta-', "rc-"]

        Boolean isNonStable = unstableKeywords
                .any { String keyword ->
                    version
                            .toLowerCase()
                            .contains(keyword)
                }
        return isNonStable
    }

    rejectVersionIf {
        isNonStable(it.candidate.version)
    }
}
```

**Comment by ben-manes** [comment]
We delegate to Gradle for dependency resolution. They resolve versions sequentially and do not allow for any parallelization within the plugin itself. They would need to optimize handling of dynamic versions.

**Comment by ZakTaccardi** [comment]
So basically, the issue is that this plugin tells Gradle to fetch:

```groovy
org.jetbrains.kotlin:kotlin-gradle-plugin:+
```

So given the following latest version:

```
org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20-dev-2342
```

Is there a way to inform Gradle itself that a version containing `dev` should be rejected without Gradle having to first resolve it?

**Comment by ben-manes** [comment]
Typically Gradle would download the `maven-metadata.xml` file and quickly scan through the version list to find matches. I'm not sure if the new gradle metadata changes that, which is created as a per version artifact.

If Kotlin had used a development repository, similar in spirit to Maven's snapshot repo, then it would isolate versions. Perhaps by using [Repository content filtering](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering) could help, but I'm not really sure.

**Comment by ben-manes** [comment]
If the above is true, then setting that repository's [metadata sources](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:supported_metadata_sources) to be just the pom might help.
