### ISSUE TITLE
Custom respositories for update check

### ISSUE THREAD

**Issue by Vampire** [ben-manes/gradle-versions-plugin#415]
If possible it would be nice if you could specify custom repositories for the update checks.
If you use an internal repository where only the version you are used are put to,
then you always have to modify the build script to add Maven Central, JCenter, ..., so that those are checked for updates as in the internal repository there will never be updates.
So it would be handy if you could tell the plugin to add arbitrary repositories to be used for checking for updated versions.

**Comment by ben-manes** [comment]
Does the solution in #98 work for you?

**Comment by Vampire** [comment]
Ah, sorry, missed that issue. That will probably work. Didn't think you could change the repositories that way at execution time.
