### ISSUE TITLE
Unresolved dependencies when using exclusiveContent

### ISSUE THREAD

**Issue by wdziemia** [ben-manes/gradle-versions-plugin#428]
My team have some artfiacts hosted on artifactory internally. We use `exclusiveContent` in order to point associate those dependencies directly to our internal artifactory repo. 

Im seeing the following errors when running `dependencyUpdates`

For artifacts defined in `allprojects.repositories`
```text
The exception that is the cause of unresolved state: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find any matches for com.my.company:artifact:+ as no versions ofcom.my.company:artifact are available.
Required by:
    project :module-name
```

For artifacts defined in `buildscript.repositories`
```
The exception that is the cause of unresolved state: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find any matches for com.my.company.gradle:gradle_artifact:+ as no versions of com.my.company.gradle:gradle_artifact are available.
Required by:
    project :
```

The strange bit is that if I define the artifactory repo without `exclusiveContent` then everything works as intended. It is as if the repos wrapped in `exclusiveContent` aren't taken into account at all. In order to run the task and have everything resolve, I am passing in argument for executing the task which is used in a conditional which either defines the repos or wraps them in `exclusiveContent`.

```bash
./gradlew dependencyUpdates -Pignore_exclusive
```

```groovy
def ignoreExclusiveInternalRepos = project.hasProperty("ignore_exclusive")

repositories {
    google()
    if (ignoreExclusiveInternalRepos){
         maven {
                url = 'www.abc.com'
         }
    } else {
        exclusiveContent {
            ...
        }
    }
}

```

Whats even stranger is that not all artifacts are affected by being wrapped in exclusiveContent. Im guessing this is some sort of limitation w/ Artifactory? Any insight would be appreciated!

**Comment by ben-manes** [comment]
Can you provide a minimal build that reproduces this problem?

**Comment by ben-manes** [comment]
Also please verify this is with v33. If so, please try v30 to check if it’s a regression.

**Comment by wdziemia** [comment]
Unfortunately Im unable to provide a build since I can only repro with our internal artifactory. I can confirm this is on v33, using Gradle 6.6.1 in a multi module Android project. Running with `--info` only shows references to the artifacts in those errors.

**Comment by ben-manes** [comment]
What about v30, in case this was a regression?

**Comment by ben-manes** [comment]
Actually, I might have too readily assumed in thinking this was a regression.

From trying to reproduce, I think the error is that it can't resolve the metadata. The dynamic version, +, requires finding the `maven-metadata.xml` or equivalent (e.g. Ivy). If that request fails then it will say the URL it searched but was not found. This can happen when the metadata isn't published, the path is restricted, or the directory listing is not allowed. I have seen it occur with JCenter which only sometimes will proxy to Central, but is flaky of when it decides to, so can return a 404 instead.

You should be able to reproduce this error outside of the plugin by setting an internal module version to `+` instead of an explicit release. If so, it does indicate an error with your Artifactory settings and unrelated to this plugin. Maybe that will offer more insight into the root cause.

**Comment by wdziemia** [comment]
` Could not find any matches for com.my.company:lib:+ as no versions of com.my.company:lib are available.` 

Looking at the artifactory instance, it looks like `mave-metadata` is published at the version level, but doesn't exist at the module level. Could that be the culprit here?

**Comment by wdziemia** [comment]
As, I dont think it's a regerssion either, I was on v27 and it only happened once we started leveraging `exclusiveContent` for these repos

**Comment by ben-manes** [comment]
Yes, it should be at the module level. See this [example](https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine) on Maven Central. It should have a similar structure and files for those artifacts.

**Comment by wdziemia** [comment]
Ah great, let me see if I can jiggle some handles and get that file generates. Closing for now, thanks for you help :)
