### ISSUE TITLE
androidTestUtil support

### ISSUE THREAD

**Issue by PaulWoitaschek** [ben-manes/gradle-versions-plugin#429]
I just noticed that my instrumentation tests don run on Android 11 when run from android studio 4.1-beta3.
This is because I was using an old version of the test orchestrator.
The dependency update task did not report that the dependency was outdated.

It would great if you could support the androidTestUtil as well, so that for
`androidTestUtil("androidx.test:orchestrator:1.2.0")`  an update to `1.3.0` would be suggested.

**Comment by ben-manes** [comment]
We perform a dynamic version query so this relies on the repository metadata,

https://dl.google.com/android/maven2/androidx/test/orchestrator/maven-metadata.xml

**Comment by jaredsburrows** [comment]
I can confirm that this does work:
```
The following dependencies have later milestone versions:
 - androidx.test:orchestrator [1.2.0 -> 1.4.1]
     https://developer.android.com/testing
```
