### ISSUE TITLE
Rejecting current version causes older versions to be checked

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [ben-manes/gradle-versions-plugin#430]
We have the following resolution strategy:

```
project.dependencyUpdates.resolutionStrategy {
   componentSelection { rules ->
     rules.all { ComponentSelection selection ->
       if (selection.candidate.group != 'com.blackbaud') {
         selection.reject('Not a blackbaud dependency')
       }
       else if (shouldSkipBlackbaudDependency(selection.candidate.moduleIdentifier.name)) {
         selection.reject('Explicitly skipped in the extension')
       }
    }
  }
}

private boolean shouldSkipBlackbaudDependency(String dependency) {
  if (pluginExtension.skippedDependencies.size() == 0) {
    return false
  }
  LocalDate today = LocalDate.now()
  LocalDate skipUntil = LocalDate.parse(pluginExtension.skipUntil)
  String[] skippedDependencies = pluginExtension.skippedDependencies
  return skippedDependencies.contains(dependency) && skipUntil.isAfter(today)
}
```

If it's not our dependency we skip it. If it is our dependency, we allow projects to skip specific dependencies (perhaps they're not ready to upgrade).

If I configure a dependency to be skipped - say common-deployable -- the plugin will skip the latest version but then it'll go on to check the older versions as well. I'll see output like:

:dependencyUpdates > Resolve dependencies of :compile > common-deployable-0.20201001.62456.pom

and the version number of the package will decrement -- 0.20200930.53525.pom -> 0.20200918.78302.pom and so on.

Are we configuring something wrong? Is there a way to make it only look at the latest version of a dependency?

**Comment by ben-manes** [comment]
Gradle's resolutionStrategy will fetch all of the versions (e.g. see [maven-metadata.xml](https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/maven-metadata.xml)) and evaluate each from latest until accepted or not resolvable. This works well when versions are pre-releases, e.g. `1.4.0-beta1`.

We enhanced Gradle's apis to also provide the `currentVersion`. You might check if the candidate matches and then accept that, which would then be placed in the up-to-date section of the report.

**Comment by Blackbaud-JasonBodnar** [comment]
Is there an `accept()` method like `reject()`? Or does not `reject()`ing count as accepting?

**Comment by ben-manes** [comment]
Only `reject` and implicit accept. The Gradle docs and api are a good reference

https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:component_selection_rules
https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ComponentSelection.html

**Comment by Blackbaud-JasonBodnar** [comment]
That worked. Thanks, Ben!
