### ISSUE TITLE
Configuration option to fail build if stuff is out of date

### ISSUE THREAD

**Issue by binkley** [ben-manes/gradle-versions-plugin#431]
(Please see sister issue for the Maven versions plugin: https://github.com/mojohaus/versions-maven-plugin/issues/387)

I'm working on an article on "Modern Java/JVM Build Practices", and this plugin is one of the recommendations for Gradle.

I'd like to offer advice on failing the build if plugins/dependencies are out of date -- with an eye to helping teams that want explicit version exclusions when needed.

What do you suggest?

**Comment by ben-manes** [comment]
This can be done by specifying an [output formatter](https://github.com/ben-manes/gradle-versions-plugin#custom-report-format). This allows for evaluating the report programmatically and failing the build of desired. See this user’s [build](https://github.com/Vampire/setup-wsl/blob/e7457fb9ddea9c5a874c4a79e39a4961cb874c52/buildSrc/src/main/kotlin/net/kautler/versions.gradle.kts#L125) as an example.

**Comment by binkley** [comment]
@ben-manes Thank you!

I'm working on [an article](https://github.com/binkley/modern-java-practices) on Gradle and Maven builds.  This is just the kind of "how to" link I was looking for.

**Comment by jaredsburrows** [comment]
Closing this as it is a question.
