### ISSUE TITLE
Missing dependency updates

### ISSUE THREAD

**Issue by mmoayyed** [ben-manes/gradle-versions-plugin#439]
## Overview

- Gradle `6.7`, JDK `11.0.9`, Plugin version: `0.34.0`

- Plugin configuration:

```groovy
apply plugin: "com.github.ben-manes.versions"

def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
    def regex = /^[0-9,.v-]+(-r)?$/
    return !stableKeyword && !(version ==~ regex)
}

dependencyUpdates {
    rejectVersionIf {
        isNonStable(it.candidate.version)
    }
}
```

## Problem

- Running via Github Actions:

```bash
./gradlew --build-cache --configure-on-demand --no-daemon --parallel -x test -x javadoc \
   dependencyUpdates -Drevision=release -DgradleReleaseChannel=current
```

Report indicates:

```
The following dependen***es are using the latest release version:
...
...

2020-11-03T07:44:53.2681454Z  - io.micrometer:micrometer-core:1.5.1
2020-11-03T07:44:53.2682363Z  - io.micrometer:micrometer-registry-atlas:1.5.1
2020-11-03T07:44:53.2683198Z  - io.micrometer:micrometer-registry-cloudwatch:1.5.1
2020-11-03T07:44:53.2684049Z  - io.micrometer:micrometer-registry-ganglia:1.5.1
2020-11-03T07:44:53.2685024Z  - io.micrometer:micrometer-registry-graphite:1.5.1
2020-11-03T07:44:53.2686155Z  - io.micrometer:micrometer-registry-influx:1.5.1
2020-11-03T07:44:53.2687129Z  - io.micrometer:micrometer-registry-jmx:1.5.1
2020-11-03T07:44:53.2687934Z  - io.micrometer:micrometer-registry-new-relic:1.5.1
2020-11-03T07:44:53.2688932Z  - io.micrometer:micrometer-registry-prometheus:1.5.1
2020-11-03T07:44:53.2689719Z  - io.micrometer:micrometer-registry-signalfx:1.5.1
2020-11-03T07:44:53.2690510Z  - io.micrometer:micrometer-registry-statsd:1.5.1
2020-11-03T07:44:53.2691281Z  - io.micrometer:micrometer-registry-wavefront:1.5.1
```

However, the latest available version is: [1.6.0](https://search.maven.org/artifact/io.micrometer/micrometer-core/1.6.0/jar).

Is this an issue with the plugin that it's missing dependency updates, or could there be something wrong with the plugin configuration or the way it's run?

**Comment by ben-manes** [comment]
You might be missing Maven Central in your repositories. If you only have jcenter then it usually gives stale results and is unreliable.

**Comment by mmoayyed** [comment]
Thanks much for the quick reply :) 

`mavenCentral()` was only missing from the buildscript section of the build. For everything else, there exists:

```groovy
allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
    }
```

Shall I take out `jcenter()` altogether?

**Comment by ben-manes** [comment]
Nope, it’s fine to be there as a backup.

Another reason is if you have a resolution strategy that is forcing a version, e.g. to enforce a bom. We honor your configuration so this can be in conflict with our dynamic queries.

**Comment by mmoayyed** [comment]
That makes good sense and I believe is the root cause. What might be a good way to resolve this? For example, should I add a custom check to disable resolution strategies and pass a special flag to do so and activate that check when dependency updates are being calculated? or, is there something in the plugin I can configure to more or less do the same (and if not, I'd be happy to send a PR if you consider it a good idea)?

**Comment by ben-manes** [comment]
You can use either the taskGraph or startParameter as conditions to check and skip your enforcement logic. This is in our issues a few times, e.g. see examples in https://github.com/ben-manes/gradle-versions-plugin/issues/361

**Comment by mmoayyed** [comment]
`startParameter.taskName` seems like a good solution. Thanks very much!
