### ISSUE TITLE
Discover buildscript dependency versions

### ISSUE THREAD

**Issue by mttmllns** [ben-manes/gradle-versions-plugin#46]
I just switched our Android project over to Gradle and have been learning the ropes.  We define a few gradle plugins in our buildscript dependencies:

```gradle
buildscript {
	repositories {
		jcenter()
	}
	dependencies {
		classpath 'com.android.tools.build:gradle:1.0.0'
		classpath 'com.github.jcandksolutions.gradle:android-unit-test:2.1.1'
		classpath 'com.github.ben-manes:gradle-versions-plugin:0.7'
		classpath 'com.jakewharton.sdkmanager:gradle-plugin:0.12.0'
	}
}
```
It would be super cool if this plugin could discover updates for these dependencies in addition to the module dependencies.  Is this possible?

**Comment by ben-manes** [comment]
And it is super cool that it does that already =)

Its pretty fun when a new version is released and the plugin lists itself as an update. Try downgrading and you'll see for yourself.

This plugin aggregates all dependencies and repositories from the project & its subprojects configurations & buildscripts. It then asks Gradle to resolve that bundle of the dependencies to reuse the same dependency management built in (ivy, maven, etc), and generates out a report of the differences. In a sense, we get to take credit for the awesome work that the Gradleware folks did ;-)

**Comment by mttmllns** [comment]
Ahhh wasn't working because I was applying the plugin in the wrong script. Android's project structure:

```
build.gradle
settings.gradle
app/
    build.gradle
```

I had to put the apply in the top-level build.gradle, not app/build.gradle.  Thanks!
