### ISSUE TITLE
buildscript in parent

### ISSUE THREAD

**Issue by vertti** [ben-manes/gradle-versions-plugin#47]
I have several gradle projects. They all contain this snippet in their `build.gradle` file:

```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.github.ben-manes:gradle-versions-plugin:0.7'
    }
}

apply plugin: 'com.github.ben-manes.versions'
```
This works as expected but I don't like the duplication. They all share a parent project. Now if I move this snippet to the parent project build.gradle and put it inside
```
subprojects {
}
```
and then run `./gradlew dependencyUpdates` from the subproject, I get an error message:
```
> Failed to apply plugin [id 'com.github.ben-manes.versions']
   > Plugin with id 'com.github.ben-manes.versions' not found.
```

What am I doing wrong or is this an issue with the versions plugin?

**Comment by ben-manes** [comment]
I don't think that a `buildscript` works properly within a `subproject` or `allproject` block, which is run during configuration time (not init). You can include all plugin dependencies at the parent's buildscript and then use a `subproject` to apply them downwards. For example, you can see one of my [projects](https://github.com/ben-manes/caffeine/blob/master/build.gradle) doing this with the `semantic-versioning` plugin. Please confirm if this solves your problem.

Personally I prefer applying this plugin at the root and centralizing the dependency versions at `${rootDir}/gradle/dependencies.gradle`. I then run the plugin at the root project, which automatically aggregates all of the subprojects, and update the versions accordingly. For large multi-module company repositories, it works well. Of course others have different usage patterns, but I like to advocate this style.

**Comment by vertti** [comment]
Alright, gradle documentation says:
```
For multi-project builds, the dependencies declared in the a project's build script, are available to the build scripts of all sub-projects. 
```

so moving the `buildscript` to parent root instead of `subprojects` block fixed it.
