### ISSUE TITLE
Android | Execution failed for task ':clean'.

### ISSUE THREAD

**Issue by mablejohn** [ben-manes/gradle-versions-plugin#472]
This is an Android project, I am using Gradle 6.8.1 and latest macOS Big Sur.
Gradle task, CLEAN failed with the following error message.

* What went wrong:
Execution failed for task ':clean'.
> java.io.IOException: Unable to delete directory '/.../build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - /.../build/dependencyUpdates/report.html
    - /.../build/dependencyUpdates

**Comment by ben-manes** [comment]
You could try `gradlew status —stop`. I don’t know how this plugin could be directly responsible.

**Comment by ben-manes** [comment]
I think this is the bug. It accidentally creates a writer twice, closing only one automatically.

https://github.com/ben-manes/gradle-versions-plugin/blob/e89d7cc92d42ba9752e54ca6ac9e80c7a5c16ec7/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy#L116
