### ISSUE TITLE
JCenter to be sunset on 2020-05-01

### ISSUE THREAD

**Issue by petedoyle** [ben-manes/gradle-versions-plugin#473]
Hi! Just a heads up- JCenter will no longer be available after 2020-05-01:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Just a note in case it makes sense to publish releases somewhere new (Maven Central, etc.)

Best,
Pete

**Comment by petedoyle** [comment]
Just saw it's already available on the Gradle plugins repository. :) Closing.

**Comment by ben-manes** [comment]
I'm not sure. The original approach for the plugin portal was to deploy to jcenter and sync. Only much later could you deploy directly to the portal, which is a JCenter repository, rather than go through this sync process. So we may still have to redo this since this plugin is very old and uses the original setup

**Comment by petedoyle** [comment]
Ok, feel free to reopen if helpful. Just reaching out proactively to all our dependencies. :) It's crazy to see JCenter go away, especially in such a short timeframe!

Also, thank you for your work on this, it's been super helpful. 🙏 😁

**Comment by ben-manes** [comment]
appreciate it. What a mess...

**Comment by jaredsburrows** [comment]
We should publish to Maven Central. See https://github.com/jaredsburrows/gradle-license-plugin/pull/147.

**Comment by ben-manes** [comment]
I thought you can publish directly to the portal now instead of going through a sync process like it originally worked?

**Comment by jaredsburrows** [comment]
I believe you can do that but we still show the "jcenter" buttom in the README.md. Maybe we should just publish to MavenCentral and Plugin repository?

**Comment by ben-manes** [comment]
For central, the [publish](https://github.com/gradle-nexus/publish-plugin) plugin is quite nice. I have e2e github [release](https://github.com/ben-manes/caffeine/blob/master/.github/workflows/release.yml) working in caffeine. You might like it for general cases.

**Comment by ben-manes** [comment]
I reclaimed the plugin on the portal, generated a new key, and added the secrets (GRADLE_PUBLISH_KEY, GRADLE_PUBLISH_SECRET). We should be able to switch over by following these [steps](https://plugins.gradle.org/docs/submit). I'll look at that over the weekend unless someone beats me to it.
