### ISSUE TITLE
Show "reason" in dependency report

### ISSUE THREAD

**Issue by alkamo** [ben-manes/gradle-versions-plugin#477]
### Feature Request

Since 4.6, Gradle has supported the ability to populate a "reason" attribute for a dependency. This would be useful to display in the dependency update report, since it may offer a justification for using an older version and hint at when it might become updateable.

### Proposed functionality

In response to the following configuration:
```
dependencies {
    implementation 'net.java.dev.jna:jna:3.2.7' {
        reason "Versions above 3.2.7 will not work on RHEL6"
    }
}
```

The dependency update task would display:
```
The following dependencies have later release versions:
 - net.java.dev.jna:jna [3.2.7 -> 5.7.0]
     Versions above 3.2.7 will not work on RHEL6
     https://github.com/java-native-access/jna
```

### Implementation Notes

The "reason" is set using the "becauseOf" method and fetched using the "reason" method.

**Comment by alkamo** [comment]
I've looked into implementing this, but it's not nearly as straightforward as I had hoped.

- `Coordinates` is the only class that gets data populated from Gradle's `Dependency` object. Adding `reason` to that is easy enough (excluding it from `@EqualsAndHashCode`). However, this strikes me as a little weird, since it involves adding non-key data to a class that's intended to be a key.
- Since the set of `Coordinates` is translated into a `Map<Map<String, String>, String>` when it's passed to `DependencyUpdatesReporter`, there doesn't seem to be any good way to pass any additional data to `DependencyUpdatesReporter` under the current design.
- The most obvious thing to do seems to be to change the data passed to `DependencyUpdatesReporter` to `Map<Map<String, String>, Coordinate>`, but that's a pretty big change, which would have other downstream affects (plus, it seems to subvert the intention of the design of `DependencyUpdatesReporter`).

**Comment by ben-manes** [comment]
Yeah, it got messy and the strings were an adapter between the two chunks of code which evolved a bit independently. It has needed a refactoring to clean that up for a while now. I’m okay if you want to take a stab at it, there was just no good reason before.

In your case, I think that I’ve used `force` to ensure no upgrades which is a bit heavy handed.

**Comment by ben-manes** [comment]
Thanks!
