### ISSUE TITLE
v0.37.0 not released to https://plugins.gradle.org/

### ISSUE THREAD

**Issue by natros** [ben-manes/gradle-versions-plugin#480]
The last version is 0.36.0
https://plugins.gradle.org/search?term=com.github.ben-manes.versions

**Comment by ben-manes** [comment]
I guess jcenter broke its sync to the plugin portal? I haven’t migrated off yet and  we use the original setup.

**Comment by natros** [comment]
I don't know if the plugin portal (https://plugins.gradle.org/m2) is related to jcenter, but the portal lists plugins with today's date (https://plugins.gradle.org/)

FYI, March 31 2021 jcenter will no longer receive updates.
(https://blog.gradle.org/jcenter-shutdown)

Thank you.

**Comment by ben-manes** [comment]
The portal used to not allow direct publication and required projects use jcenter. We were on Central at the time, and switched to jcenter for the new portal experience. We need to migrate, but it’s weird how quickly they decided to break things.

**Comment by ben-manes** [comment]
Seems that there is a bug on Gradle's side, where the portal knows of 0.37 but doesn't show it. I tried to publish manually after setting up the direct publication, but it failed as an existing version. The simplest answer might be to release 0.38 to get it sync'd up. See https://github.com/gradle/plugin-portal-requests/issues/84

```
Execution failed for task ':publishPlugins'.
> Failed to post to server.
  Server responded with:
  Plugin: 'com.github.ben-manes.versions', version: '0.37.0' exists already. It was created: 2021-02-23 04:08:49.119
```

**Comment by eygraber** [comment]
It's not showing up in jcenter either:

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.ben-manes:gradle-versions-plugin:0.37.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/ben-manes/gradle-versions-plugin/0.37.0/gradle-versions-plugin-0.37.0.pom
       - https://jcenter.bintray.com/com/github/ben-manes/gradle-versions-plugin/0.37.0/gradle-versions-plugin-0.37.0.pom
       - https://plugins.gradle.org/m2/com/github/ben-manes/gradle-versions-plugin/0.37.0/gradle-versions-plugin-0.37.0.pom
       - http://oss.sonatype.org/content/repositories/snapshots/com/github/ben-manes/gradle-versions-plugin/0.37.0/gradle-versions-plugin-0.37.0.pom
```

**Comment by ben-manes** [comment]
That’s link is a mirror of Maven Central, so it hosts very old versions. I guess the [jcenter](https://bintray.com/fooberger/maven/com.github.ben-manes%3Agradle-versions-plugin/_latestVersion) one is no longer automatically resolved.

**Comment by ben-manes** [comment]
Releasing 0.38 as the simplest fix for this issue.

The root problem seems to be due to us having switched from the legacy maven plugin to bintray's during the TravisCI migration. Somehow that pushed the `maven-metatadata.xml` and jar, but not the pom file and resulted in an invalid resource. We probably should have gone straight to direct publishing, but it was a bit of a scramble. That went out nice and clean, so let's just pretend this never happened. 🙂
