### ISSUE TITLE
Does not create the dependency report properly when depending on other tasks

### ISSUE THREAD

**Issue by nyca183** [ben-manes/gradle-versions-plugin#484]
I am trying to create a new dependency report everytime i am building my root project, so i've set a dependency to the build tasks (build.dependsOn(dependencyUpdates)).
The console says that a new report was created, but the modification date of the old report does not change.
Everytime i am manually executing the dependencyUpdates, everything works fine, so this only happens when I am trying to automate the execution of the task.

Thanks for help!

**Comment by ben-manes** [comment]
I won’t get a chance to look at this immediately, but the simplest workaround is probably to delete the report first. That could be done using doFirst on the update task. Hopefully that unblock you until I get a chance to reproduce.

**Comment by nyca183** [comment]
This just deleted the report. Even though it said that it created a new one, it actually did not. 
Thanks for the the quick reply anyways.
Waiting for further solutions
Kind regards

**Comment by nyca183** [comment]
Found the solution:
I had to set the outputDir.
I thought the default path would be applied to the task like when executing it manually, but that is not the case.
