### ISSUE TITLE
JCenter was deprecated

### ISSUE THREAD

**Issue by sergeykad** [ben-manes/gradle-versions-plugin#486]
JCenter is going to shut down and its usage is deprecated in Gradle 7.  However, the latest plugin versions seem to be available on JCenter only.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
https://docs.gradle.org/7.0-milestone-2/userguide/upgrading_version_6.html#jcenter_deprecation

**Comment by ben-manes** [comment]
We switched to publishing directly to the Gradle Plugin Portal. The latest version, 0.38, only resides there. Previously we published through JCenter and used its portal sync capability. Simply replace `jcenter()` with `gradlePluginPortal()` and you should be set.

**Comment by xenomachina** [comment]
Perhaps I'm doing something wrong, but it looks like there's still a dependency on jcenter somewhere.

Here's what I did:

1. Wiped out `~/.gradle/init.d/` to avoid possible red-herrings.
1. Created an empty project with only this `build.gradle` file:

   ``` groovy
   apply plugin: "com.github.ben-manes.versions"

   buildscript {
     repositories {
       gradlePluginPortal()
     }

     dependencies {
       classpath "com.github.ben-manes:gradle-versions-plugin:0.38.0"
     }
   }
   ```
1. Installed gradle wrapper 6.8.3.
1. Disabled access to `jcenter.bintray.com` by adding this line to `/etc/hosts`:
   ``` config
   0.0.0.0	jcenter.bintray.com
   ```
1. Ran the command:
   ``` sh
   ./gradlew --refresh-dependencies dependencyUpdates
   ```

The output is:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'minimal'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.ben-manes:gradle-versions-plugin:0.38.0.
     Required by:
         project :
      > Could not resolve com.github.ben-manes:gradle-versions-plugin:0.38.0.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/ben-manes/gradle-versions-plugin/0.38.0/gradle-versions-plugin-0.38.0.module'.
            > Could not GET 'https://jcenter.bintray.com/com/github/ben-manes/gradle-versions-plugin/0.38.0/gradle-versions-plugin-0.38.0.module'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/0.0.0.0] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
```

It's trying to get `https://jcenter.bintray.com/com/github/ben-manes/gradle-versions-plugin/0.38.0/gradle-versions-plugin-0.38.0.module`.

**Comment by ben-manes** [comment]
The gradle plugin portal has implicit redirects to JCenter. I believe it was originally hosted on it, but nowadays merely redirects on a 404. You can see this mentioned during discussions of JCenter being shut down. (e.g. https://github.com/gradle/gradle/issues/15406).

**Comment by xenomachina** [comment]
So if/when the plugin portal stops redirecting to jcenter, it'll become possible to use gradle-versions-plugin without jcenter connectivity?

Do you happen to know if Gradle has published plans to migrate the plugin portal off of jcenter? The linked issue hints at it in the last comment, but other than that I haven't been able to find any mention of it from Gradle.

**Comment by ben-manes** [comment]
They have a [blog post](https://blog.gradle.org/jcenter-shutdown) where they say,

> The Gradle Plugin Portal implicitly mirrors JCenter currently. If you’re using the Plugin Portal (via gradlePluginPortal() or the URL plugins.gradle.org/m2) to resolve your application’s dependencies, you may be relying on JCenter. You should avoid using the Plugin Portal as a repository, except for Gradle plugin projects.

You might want to read the section `Impact to Gradle plugins`. That seems to be extent of their communication on this.

You might be able to use repository [content filtering](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering) to ban the gradle metadata, which is not currently generated when publishing a plugin. That seems to be the source of the redirect you are seeing.

If you want to strictly ban jcenter, your best bet is to set up an alternative plugin repository. That way the implicit redirect does not happen. Or alternatively, you can use it to have a cache of anything that might be in your build and only on jcenter, so it is resolvable when the shutdown occurs.

Until JCenter is offline then I am afraid there might be hidden usages throughout the ecosystem which we cannot predict. The portal's usage is likely going to cause a lot of build breaks when it stops mirroring.

**Comment by xenomachina** [comment]
Thanks for your help and advice.

My concern is that [JFrog's blog post](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) said they'll be turning off JCenter+bintray in May, and there'll be brownouts starting in less than a week. I see they've updated that page to say:

> To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021.

...so hopefully that means that the Gradle Plugin Portal will have a chance to migrate off of it before things change in a way that will break Gradle plugins.

**Comment by androideveloper** [comment]
There is a new update from jcenter:
> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
