### ISSUE TITLE
Disable console output option

### ISSUE THREAD

**Issue by olliefreeman** [ben-manes/gradle-versions-plugin#50]
It would be nice to be able to disable the console output when saving results to a file, this is especially useful for CI systems which are also scanning the console output for warnings and we don't want to confuse the output.

**Comment by ben-manes** [comment]
I would expect the CI to run this task as part of an independent step, while a normal build task includes a check for warnings and skipped test. The dependency updates task would be part of a post-build action where there may be other ad hoc console output like SSH for deployments, etc.

Personally I wouldn't make the CI generate this report on every build, but rather as a nightly job which might include other ad hoc tasks.

I agree disabling console output isn't hard, but I'm not sure if its the right solution for your problem.

**Comment by jochenberger** [comment]
Seconded. I wouldn't run the `dU` task as part of a CI build either. And I also agree that an option to disable console output would make a nice addition.

**Comment by olliefreeman** [comment]
Yeah we don't run it as part of CI anymore just an occasional job but would be nice to not have the console output.

**Comment by ben-manes** [comment]
Do you consider `gradle --quiet` flag a proper fix for this?

**Comment by ben-manes** [comment]
Closing as quiet flag should be sufficient.
