### ISSUE TITLE
Task added into wrong module

### ISSUE THREAD

**Issue by OleksandrKucherenko** [ben-manes/gradle-versions-plugin#51]
I develop library and use plugin inside it. 

I found that plugin add task into hierarchy into wrong location. Take a look on image.

![Wrong Hierarchy](https://dl.dropboxusercontent.com/s/ccegdzbysefvuw5/wrong-task.png)

```:samples``` - is a sub-directory, it does not have any active tasks. Why plugin add own task into it?
```bindint-tc``` - is a root of the project, I also believe that ```dependecyUpdates``` should not be there.

So is it possible to fix?

**Comment by ben-manes** [comment]
The task should only be available on the projects that the plugin is applied to. Are you sure that you don't have it applied in a `subprojects` or `allprojects` block?

**Comment by ben-manes** [comment]
I see in your [meters project](https://github.com/OleksandrKucherenko/meter/blob/master/build.gradle#L97) this is exactly what is happening. As your `settings.gradle` includes the sample, it is considered a subproject. The root project is includes in an `allproject` configuration block.

I'm closing this as it appears to be a simple mistake in your build file. If you disagree, feel free to reopen.

**Comment by OleksandrKucherenko** [comment]
ok. Thanks! I will try to apply it on each project separately. Give me several minutes for confirmation....

**Comment by OleksandrKucherenko** [comment]
ok. confirming.

It's actually a bug inside Android Studio. Gradle tree in it shows dependecyUpdate tasks in wrong place. Gradle command line shows tasks correctly.
