### ISSUE TITLE
[Feature Request] Possibility to use both custom reporter and built in reporter, instead of only one or the other.

### ISSUE THREAD

**Issue by aaulia** [ben-manes/gradle-versions-plugin#513]
CMIIW, currently we can only set `outputFormatter` to either using built in formatter (`plain`, `html`, etc) or using custom made formatter using `closure` or implementing `Reporter`.  

Can we have both? I have use-case where I want to generate dependency table for my project(s) in markdown format, but I still want to have the built in report.

**Comment by ben-manes** [comment]
You could instantiate and call a built-in reporter from the custom output formatter, and thereby do both.

**Comment by aaulia** [comment]
Ah, didn't think of that. Nice.
