### ISSUE TITLE
Unable to add plugin using unspecified version

### ISSUE THREAD

**Issue by lucianocheng** [ben-manes/gradle-versions-plugin#514]
Just a heads up that I wasn't able to add this plugin using the instructions on the README. This was true both for the `plugin` block as well as the `buildscript` block.

I had to specify the version to make it work. IE:

```
plugins {
    id "com.github.ben-manes.versions" version "0.38.0"
}
```

I got this code block from the gradle plugins website:
https://plugins.gradle.org/plugin/com.github.ben-manes.versions

**Comment by ben-manes** [comment]
The "$version" string is meant to indicate that is user supplied, as `$` is property replacement in Groovy. Only built-in plugins, like `java`, do not need a version specified. Sorry for the confusion, but this was to avoid accidental version skew / old versions in the README by not being updated on a release.

**Comment by lucianocheng** [comment]
Got it. In case someone googles in the future, this is the gradle error I was getting.

```
Could not find com.github.ben-manes:gradle-versions-plugin:unspecified
```
