### ISSUE TITLE
Is it possible to create a rule that search for other beta if I already use beta version of a lib?

### ISSUE THREAD

**Issue by benjdero** [ben-manes/gradle-versions-plugin#526]
I use this plugin since months with the rule that only check for stable releases, and its working great.

But in today Android world we are pushed to use unstable version or at least try it before they become stable, a lot of libraries use the following suffix: alpha -> beta -> rc -> no suffix (stable). 

So it would be nice to have a rule that allow to check if there is an update with current suffix "or better" (for example if we use "beta", search for an more up to date "beta", "rc", or stable, but no "alpha" version.

Is it possible to do that using that plugin? I tried it myself but got no luck so far.

**Comment by ben-manes** [comment]
You can define the rules yourself and it is very flexible. You simply define your `rejectVersionIf` to behave however you want. In the following example, an update from a stable version will only show new stable versions and an update from an unstable version will show regardless. You can fine tune the `isNonStable` function and `rejectVersionIf` rule to match your use-case.

```gradle
def isNonStable = { String version ->
  def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
  def regex = /^[0-9,.v-]+(-r)?$/
  return !stableKeyword && !(version ==~ regex)
}

dependencyUpdates {
  rejectVersionIf {
    isNonStable(it.candidate.version) && !isNonStable(it.currentVersion)
  }
}
```

**Comment by ben-manes** [comment]
Actually, it sounds like you want to show unstable by default so you can remove `rejectVersionIf`. This will likely show the alpha -> beta -> rc correctly by default as Gradle has a version sort order and the external release metadata will say what is the latest version available. Generally that will works out of the box as desired.

**Comment by benjdero** [comment]
I was thinking about something like this:

```groovy
def getStabilityLevel = { version ->
    def v = version.toUpperCase()
    if (v.contains('ALPHA'))
        return 0
    else if (v.contains('BETA'))
        return 1
    else if (v.contains('RC'))
        return 2
    else
        return 3
}

dependencyUpdates {
    rejectVersionIf {
        getStabilityLevel(it.candidate.version) < getStabilityLevel(it.currentVersion)
    }
}
```

This should work with any library that respect the same naming convention as Google do for its Android libraries. 

Thank you for your help and for this library, the new syntax is very concise and clear. In the past I used this old syntax below and never managed to customize it to my needs:

```groovy
dependencyUpdates.resolutionStrategy {
    componentSelection { rules ->
        rules.all { ComponentSelection selection ->
            boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm', 'preview', 'b', 'ea'].any { qualifier ->
                selection.candidate.version ==~ /(?i).*[.-]$qualifier[.\d-+]*/
            }
            if (rejected) {
                selection.reject('Release candidate')
            }
        }
    }
}
```

**Comment by ben-manes** [comment]
That’s great. @jmfayard contributed the succinct notation. 🙂
