### ISSUE TITLE
New versions of one particular Gradle plugin are not reported

### ISSUE THREAD

**Issue by BoD** [ben-manes/gradle-versions-plugin#527]
Hi!

Not sure why, but new versions of the [Android cache fix Gradle plugin](https://github.com/gradle/android-cache-fix-gradle-plugin) (from the official Gradle team) don't appear in the reports. 

To my knowledge, it's the only dependency we use in our project that has this problem.

Let me know if I can help investigate in any way.

**Comment by ben-manes** [comment]
I tried adding it to the `examples/groovy` build and saw,

```
 - org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin [2.3.0 -> 2.3.2]
```

Some configurations like buildSrc, `settings.gradle`, subproject buildscript blocks are hidden from us due to Gradle api limitations. Maybe you set it up in one of those?

**Comment by BoD** [comment]
Yeah indeed that's the case.  I guess that's the culprit then :( Sorry for the noise!
