### ISSUE TITLE
Jetpack Compose: Failed to determine the latest version for the following dependencies 

### ISSUE THREAD

**Issue by ColtonIdle** [ben-manes/gradle-versions-plugin#536]
```
Failed to determine the latest version for the following dependencies (use --info for details):
 - androidx.activity:activity-compose
 - androidx.compose.compiler:compiler
 - androidx.compose.ui:ui-tooling
 - androidx.navigation:navigation-compose
```

Interesting that it's just compose. I tried using --info but I got a huge log of information but I figured since this affects just compose I'd bring it up.

**Comment by ben-manes** [comment]
Can you provide a build to debug against? If open-source that's fine,or else a minimal reproduction.

**Comment by ColtonIdle** [comment]
Will try to get a minimal repro. Currently this is in a large project.

**Comment by ColtonIdle** [comment]
User error. Closing. 😓
