### ISSUE TITLE
androidx.core:core not being detected as stable?

### ISSUE THREAD

**Issue by ColtonIdle** [ben-manes/gradle-versions-plugin#538]
As per this discussion https://github.com/ben-manes/gradle-versions-plugin/discussions/537 I added these lines

```
tasks.withType<DependencyUpdatesTask> {
    rejectVersionIf {
        isNonStable(candidate.version) && !isNonStable(currentVersion)
    }
}

fun isNonStable(version: String): Boolean {
    val stableKeyword = listOf("RELEASE", "FINAL", "GA").any { version.toUpperCase().contains(it) }
    val regex = "^[0-9,.v-]+(-r)?$".toRegex()
    val isStable = stableKeyword || regex.matches(version)
    return isStable.not()
}
```

This works great as it stripped out like 20 dependencies that wanted to use alpha versions... except for androidx core. Curious if I'm doing something wrong here.

```
The following dependencies have later milestone versions:
 - androidx.core:core [1.6.0 -> 1.7.0-alpha01]
     https://developer.android.com/jetpack/androidx/releases/core#1.6.0
```

**Comment by ben-manes** [comment]
That seems correct. Gradle should log (at info) during the resolution or you might add your own prints. It doesn’t look like it should pass, but somehow Gradle decided it did

**Comment by ColtonIdle** [comment]
Okay. That works for me. I will just ignore it for now. Thanks
