### ISSUE TITLE
Reports in Jenkins/Sonar

### ISSUE THREAD

**Issue by moleksyuk** [ben-manes/gradle-versions-plugin#54]
Hi @ben-manes 

Are there any examples/docs how to configure Jenkins or Sonar to use reports?

Thanks a lot.

**Comment by ben-manes** [comment]
I have not tried and the xml / json reports were community contributions. I simply run the text report periodically, such as when I upgrade Gradle versions. I'd be happy to accept contributions if there is any integration changes needed.

**Comment by davidjohansson** [comment]
@moleksyuk : I went for a very simplistic approach when integrating with Jenkins, using it's TextFinder plugin (https://wiki.jenkins-ci.org/display/JENKINS/Text-finder+Plugin) to check the json output file (after some parsing) for stuff I'm interested in

**Comment by ben-manes** [comment]
@y-yagi wrote [gradle-update-notifier](https://github.com/y-yagi/gradle-update-notifier) that creates GitHub issue from the json results.

**Comment by jaredsburrows** [comment]
@moleksyuk Since this is just a question, I am closing for now.
@ben-manes
