### ISSUE TITLE
Cannot fetch the plugin 0.39.0 in circleci 

### ISSUE THREAD

**Issue by charlesng** [ben-manes/gradle-versions-plugin#541]
### Description

Ytd i kept getting the following error in circleci, i cant figure it out what is `xstream` dependency. It works as normal before but have no idea suddenly I got this error. I haven't changed any lib version and plugin recently. It just happen suddenly

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.ben-manes.gradle-versions-plugin:xstream:0.39.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://repo.maven.apache.org/maven2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://jitpack.io/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://plugins.gradle.org/m2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
     Required by:
         project : > com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.39.0 > com.github.ben-manes:gradle-versions-plugin:0.39.0 > com.github.ben-manes.gradle-versions-plugin:gradle-versions-plugin:0.39.0
```

Does anyone have any idea about this?

**Comment by ben-manes** [comment]
Those query resolutions don't make any sense. You'll notice that the artifacts are all prefixed with this project and our version number. The actual dependency is `com.thoughtworks.xstream:xstream:1.4.17` ([pom](https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.17/xstream-1.4.17.pom)).

**Comment by ercan** [comment]
I am getting exactly the same error on GitLabCI

```
Could not find com.github.ben-manes.gradle-versions-plugin:xstream:0.39.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://jcenter.bintray.com/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://repo.maven.apache.org/maven2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://jitpack.io/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://plugins.gradle.org/m2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://nexus.protein.tech/repository/maven-snapshots/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://nexus.protein.tech/repository/maven-releases/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://nexus.protein.tech/repository/external-snapshots/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://nexus.protein.tech/repository/external-releases/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
```

**Comment by ercan** [comment]
I am getting exactly the same error on GitLabCI

```
Could not find com.github.ben-manes.gradle-versions-plugin:xstream:0.39.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://jcenter.bintray.com/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://repo.maven.apache.org/maven2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://jitpack.io/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://plugins.gradle.org/m2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
```

**Comment by harry248** [comment]
Same on App Center too.

A problem occurred configuring root project 's'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.ben-manes.gradle-versions-plugin:xstream:0.39.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://jcenter.bintray.com/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://jitpack.io/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
       - https://plugins.gradle.org/m2/com/github/ben-manes/gradle-versions-plugin/xstream/0.39.0/xstream-0.39.0.pom
     Required by:
         project : > com.github.ben-manes:gradle-versions-plugin:0.39.0 > com.github.ben-manes.gradle-versions-plugin:gradle-versions-plugin:0.39.0

**Comment by ben-manes** [comment]
The plugin's [pom](https://plugins.gradle.org/m2/com/github/ben-manes/gradle-versions-plugin/0.39.0/gradle-versions-plugin-0.39.0.pom) merely has,
```xml
<dependencies>
  <dependency>
    <groupId>com.thoughtworks.xstream</groupId>
    <artifactId>xstream</artifactId>
    <version>1.4.17</version>
    <scope>runtime</scope>
  </dependency>
</dependencies>
```

Similarly, the gradle metadata [module](https://plugins.gradle.org/m2/com/github/ben-manes/gradle-versions-plugin/0.39.0/gradle-versions-plugin-0.39.0.module) has,
```json
"dependencies": [
  {
    "group": "com.thoughtworks.xstream",
    "module": "xstream",
    "version": {
      "requires": "1.4.17"
    }
  }
],
```

This sounds like an unrelated problem. What gradle version do you have? Can you provide a reproducer?

**Comment by acarlsen** [comment]
I have exactly the same issue with 0.39.0. Reverting to 0.38.0 works perfectly.
Gradle version 7.1.1.

**Comment by ben-manes** [comment]
I cannot reproduce using 7.1.1. Can you find this plugin in your build cache and check the metadata? Is there some other repository that is hosting a corrupted version? We deploy to the plugin portal only and that metadata is correct. I have tried a clean cache and everything works locally. It seems like a gradle or repository problem.

**Comment by artour-bakiev** [comment]
We're getting a similar issue:
```
* What went wrong:
Could not apply requested plugin [id: 'com.github.ben-manes.versions', version: '0.39.0'] as it does not provide a plugin with id 'com.github.ben-manes.versions'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'com.github.ben-manes.versions' not found.
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.plugins.InvalidPluginException: Could not apply requested plugin [id: 'com.github.ben-manes.versions', version: '0.39.0'] as it does not provide a plugin with id 'com.github.ben-manes.versions'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
```
Last Friday (9 July 2021) everything was just OK - now we get the `Could not apply requested plugin` error on the Bamboo CI with v 0.39.0

Has to revert back to 0.36.0.

**Comment by ben-manes** [comment]
Please provide more details, e.g. attach the downloaded plugin in `~.gradle` and verify the checksum, pom, etc against the plugin portal.

These comments are not providing enough information to investigate as 0.39 works fine for me and has been released for a while. Those experiencing this need to offer more assistance.

**Comment by charlesng** [comment]
I tried few time this morning with the existing project I faced this issue few days ago and the new project that haven't setup with this tool yet. I cannot reproduce this issue again. 🤦

**Comment by harry248** [comment]
Downgrading to 0.38.0 worked for us or rather App Center too. Really strange because 0.39.0 worked fine until thursday and then suddenly stopped. App Center now also shows a warning "Gradle Task failures may be related to JFrog Bintray Shutdown/Brownouts" with a link to https://blog.gradle.org/jcenter-shutdown. Maybe related?

**Comment by artour-bakiev** [comment]
> These comments are not providing enough information to investigate as 0.39 works fine for me and has been released for a while. Those experiencing this need to offer more assistance.

Yeah, sorry and I understand the information is too little but it's what we have at the moment :(.  Locally I have no issues with 0.39.0 and would be happy to help with the investigation. But since the issue happens on CI it's kind of painful. Just a random thought - is there a chance it is related to the way 0.39.0 is distributed? For example, the fact that JCenter is being shut down.

**Comment by ben-manes** [comment]
@artour-bakiev The plugin is distributed via the Gradle Plugin Portal. You should remove jcenter from your build files. Similarly, I would be hesitant to have jitpack as a plugin repository. If you need either, you might use repository content filtering to restrict it only to the plugins you need from there.

**Comment by ben-manes** [comment]
Hi all,

Your problem is jitpack. Somehow they have invalid metadata on their repository. See the following urls
https://jitpack.io/com/github/ben-manes/gradle-versions-plugin/gradle-versions-plugin/0.39.0/
https://jitpack.io/com/github/ben-manes/gradle-versions-plugin/gradle-versions-plugin/0.39.0/gradle-versions-plugin-0.39.0.pom
https://jitpack.io/com/github/ben-manes/gradle-versions-plugin/gradle-versions-plugin/0.39.0/gradle-versions-plugin-0.39.0.module

Since this is built externally and does not match our own build definition, I cannot say why or how this might have occurred. You should be weary of jitpack due to being an easier attack vector and use content filtering to restrict its usage. Please use the plugin portal for this dependency.

**Comment by skjolber** [comment]
Resolution for artifactory: 

 * added gradle plugins as a new remote: https://plugins.gradle.org/m2
 * jitpack remote:
   * exclude `com/github/ben-manes/**`, 
   * moved it to the bottom of the remote repositories (in my virtual repository)
  
Then nukes all local caches (gradle caches in project folder, home folder, android folder) and built again.
