### ISSUE TITLE
JUnit Jupiter milestones returned with -Drevision=release

### ISSUE THREAD

**Issue by Thunderforge** [ben-manes/gradle-versions-plugin#549]
When running `gradlew dependencyUpdates -Drevision=release`, JUnit Jupiter milestones are included (e.g. [5.8.0-M1](https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api/5.8.0-M1)). According to [this section of the docs](https://github.com/ben-manes/gradle-versions-plugin#revisions), this should only be shown when `-Drevision=milestone`.

## Expected Behavior

* `gradlew dependencyUpdates -Drevision=release` results in  `org.junit.jupiter:junit-jupiter-api [5.6.0 -> 5.7.2]`
* `gradlew dependencyUpdates -Drevision=milestone` results in  `org.junit.jupiter:junit-jupiter-api [5.6.0 -> 5.8.0-M1]`

## Actual Behavior

* `gradlew dependencyUpdates -Drevision=release` results in  `org.junit.jupiter:junit-jupiter-api [5.6.0 -> 5.8.0-M1]`
* `gradlew dependencyUpdates -Drevision=milestone` results in  `org.junit.jupiter:junit-jupiter-api [5.6.0 -> 5.8.0-M1]`

**Comment by ben-manes** [comment]
This looks to be the same as #550. That versioning strategy does not match Ivy / Maven conventions, which are much more brittle. The docs are correct and push towards a resolution strategy for these cases.

**Comment by Thunderforge** [comment]
I had created two issues because it seemed that they were two different versioning conventions for two libraries, but if you think they're the same issue, I guess we'll track it in #550.
