### ISSUE TITLE
version 0.8 does not work with Gradle 1.x

### ISSUE THREAD

**Issue by yoavain** [ben-manes/gradle-versions-plugin#55]
Running with:
dependencies {
	classpath 'com.github.ben-manes:gradle-versions-plugin:0.8'
	classpath 'org.codehaus.groovy:groovy-backports-compat23:2.3.5'
}

Results with:
* What went wrong:
Execution failed for task ':dependencyUpdates'.
> java.lang.ClassNotFoundException: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.StaticVersionComparator

(StaticVersionComparator does not exist in Gradle 1.x)

Downgrading to 0.7 it works fine.

**Comment by ben-manes** [comment]
Thanks. Which gradle version in the 1.x family are you using?

**Comment by yoavain** [comment]
I'm using 1.11 but I also tried with 1.12.

Thanks!

**Comment by ben-manes** [comment]
Yep, there's a mistake in the regex pattern because I jumped from 1.9 -> 2.x and forgot about the 1.1x releases. I'll fix this for the next release because I think 2.4 will be incompatible too.

**Comment by yoavain** [comment]
Thanks!
