### ISSUE TITLE
Filter dependencies that must be updated.

### ISSUE THREAD

**Issue by CharlesMoreira1** [ben-manes/gradle-versions-plugin#557]
Hi!

I have a question, but I don't know if this is the right place for it. If you can help me.

My project has a lot of outdated dependencies, however I just want to report some specific ones. How can I do this?

**Comment by ben-manes** [comment]
You can use rejectVersionIf to force the version to the current one for anything you don’t care about. Then it will group those into the updated section

**Comment by CharlesMoreira1** [comment]
How would I do this? Could you give me an example?

Because the ones in the readme don't show what it would be like for a specific dependency.

**Comment by ben-manes** [comment]
For example, have the list of dependency groups that you care about. Any dependency not in those groups should ignore later versions and Gradle should resolve the current version as the latest. Otherwise if whitelisted, the latest is allowed to be reported. Since this plugin scripts Gradle's resolution with a dynamic `+` version, we can simply script its resolution process as below.

```groovy
dependencyUpdates.rejectVersionIf {
  def updatable = [ 'foo', 'bar' ]
  return !updatable.contains(it.candidate.group) && (it.candidate.version != it.currentVersion)
}
```

**Comment by CharlesMoreira1** [comment]
It worked. Thank you very much!
I just couldn't get it to show only release version.

What did I do wrong here?

```
def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
    def regex = /^[0-9,.v-]+(-r)?$/
    return !stableKeyword && !(version ==~ regex)
}

dependencyUpdates.rejectVersionIf {
    def updatable = ['io.coil-kt', 'androidx.compose.ui']
    return !updatable.contains(it.candidate.group) && (it.candidate.version != it.currentVersion) && isNonStable(it.candidate.version)
}
```

**Comment by ben-manes** [comment]
I think you need to use it as an OR condition.

**Comment by CharlesMoreira1** [comment]
Good. It worked!

A question just to close, I didn't see it anywhere in the readme.

But would I be able to list only the libs that should be updated in the .txt?
 It would hide the:

`The following dependencies are using the latest milestone version:`

and

`Failed to determine the latest version for the following dependencies:`

**Comment by ben-manes** [comment]
In that case, you could use a custom report to control the output. See that section under [report format](https://github.com/ben-manes/gradle-versions-plugin#report-format).

**Comment by CharlesMoreira1** [comment]
I managed to print in the log, but it's not generating a .txt file.

Do I have to specify something?

```
dependencyUpdates {
    checkForGradleUpdate = true

    rejectVersionIf {
        !allowedDroupList.contains(it.candidate.group) && (it.candidate.version != it.currentVersion) || isNonStable(it.candidate.version)
    }

    outputFormatter = { result ->
        result.outdated.dependencies.forEach {
            println "${it.group}:${it.name}:${it.version} -> ${it.available.release ?: it.available.milestone}"
        }
    }
}
```

**Comment by ben-manes** [comment]
Sure, there are lots of ways to do file I/O. For example,

```groovy
File outputFile = project.file(filename)
outputFile.withPrintWriter { PrintWriter printer ->
  printer.println 'blah'
}
```

**Comment by CharlesMoreira1** [comment]
Thanks! It's working very well.

Working around with groovy/gradlew is a new thing for me.

You said you have several options to create a file. But how would I go about creating a temporary file in the build folder?

Because I tried to point to the build folder when it doesn't exist, and it fails because it isn't found.

```
outputFormatter = { result ->
        File outputFile = project.file('build/dependencyUpdates/reportLaterRelease.txt')

        outputFile.withPrintWriter { PrintWriter printer ->
            def title = "The following dependencies have later release versions:\n"
            printer.println title
            println title

            result.outdated.dependencies.forEach {
                def resultDependencies = " - ${it.group}:${it.name}:${it.version} -> ${it.available.release ?: it.available.milestone}"
                printer.println resultDependencies
                println resultDependencies
            }
        }
    }
```

**Comment by ben-manes** [comment]
See the `File.mkdirs` method. I would guess off-hand `outputFile.parent().mkdirs()`. You can also use `$buildDir` to make the path a little more flexible.

**Comment by CharlesMoreira1** [comment]
Sorry, but can you help me with an example?

I even looked for some, but it didn't work.

Currently I tried it like this:

```
outputFormatter = { result ->

        File outputFile = file("$buildDir/dependencyUpdates/reportLaterRelease.txt")

        outputFile.withPrintWriter { PrintWriter printer ->
            def title = "The following dependencies have later release versions:\n"
            printer.println title
            println title

            result.outdated.dependencies.forEach {
                def resultDependencies = " - ${it.group}:${it.name}:${it.version} -> ${it.available.release ?: it.available.milestone}"
                printer.println resultDependencies
                println resultDependencies
            }
        }
    }
```
`> java.io.FileNotFoundException: /features/home/build/dependencyUpdates/reportLaterRelease.txt (No such file or directory)
`

**Comment by ben-manes** [comment]
Add this line:
`outputFile.parentFile.mkdirs()`

**Comment by CharlesMoreira1** [comment]
Thanks, Ben Manes! 

Mainly through patience, I managed to get the result I wanted.

**Comment by ben-manes** [comment]
congrats!
