### ISSUE TITLE
Report includes transitive dependencies

### ISSUE THREAD

**Issue by giangpham96** [ben-manes/gradle-versions-plugin#562]
When running `./gradlew clean dependencyUpdates -Drevision=release -DoutputFormatter=json,plain --info`, the output file includes some dependencies that aren't directly used by the project. For example, `org.jacoco:org.jacoco.ant [0.8.3 -> 0.8.7]`.
Is there a way to exclude such dependencies from the report?
Notes: Not all transitive dependencies are included, which is weird

**Comment by ben-manes** [comment]
I suspect you are on Android and ran into https://github.com/ben-manes/gradle-versions-plugin/issues/534#issuecomment-897234445. Their Jacoco plugin adds the dependency to your project, so our scanning picks it up appropriately. The native Gradle plugin [adds](https://github.com/gradle/gradle/blob/cfe5908c9b7aeeaec4912b14471aa4e7448c282d/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java#L136) this as a default dependency, so it remains hidden until resolution and we can scrub out as not in the declared listing. The comment includes a workaround for your report, or else you can try to have the Android team improve how they author plugins.
