### ISSUE TITLE
[Question] Is it possible to use a custom formatter to generate a file while also keeping the standard console output?

### ISSUE THREAD

**Issue by leinardi** [ben-manes/gradle-versions-plugin#566]
As per title, I would like to know if there is an easy way to keep the standard console text output while also using the `outputFormatter` to set a Closure that saves a custom report format to a file.

I know that in theory I could re-implement the text formatter inside the closure but I was hoping to, somehow, reuse the existing one that is already doing what is needed.

The use case is that the custom report saved to a file is need for CI, while the console output one is more convenient for Devs to run on demand locally.

**Comment by ben-manes** [comment]
You could either set the output formatted only if a CI build or have yours directly invoke the PlainTextReporter. I think the former is a bit nicer as you might have other customizations in your build. Usually it’s just checking if `System.env.’CI’` is true.

**Comment by leinardi** [comment]
Hey thanks! Yeah, the CI one makes sense, but I also like the idea of having an HTML file inside the build folder with the result, if I would ever need it for some reason.

For now I'll go with calling the `PlainTextRenderer`, it works like a charm!
```groovy
tasks.named("dependencyUpdates").configure {
    gradleReleaseChannel = 'current'
    rejectVersionIf {
        isNonStable(it.candidate.version) && !isNonStable(it.currentVersion)
    }
    outputFormatter = { result ->
         [...]
        PlainTextReporter plainTextReporter = new PlainTextReporter(project, revision, gradleReleaseChannel)
        plainTextReporter.write(System.out, result)
    }
}
```

**Comment by ben-manes** [comment]
Also fwiw you might be able to use `outputFormatter=plain,html` if the built in outputs are acceptable.
