### ISSUE TITLE
Gradle 2.4 Compatibility

### ISSUE THREAD

**Issue by marcoRS** [ben-manes/gradle-versions-plugin#57]
The plugin appears to be incompatible with Gradle 2.4. When I run "gradle dU" I get the following output: 

* What went wrong:
Execution failed for task ':app:dependencyUpdates'.
> java.lang.String cannot be cast to org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.Version

**Comment by ben-manes** [comment]
Have you updated to v0.9?

**Comment by marcoRS** [comment]
Hi @ben-manes, yeah I was running version v0.9 against Gradle 2.4 final release.

**Comment by ben-manes** [comment]
I ran it locally on a my [project](https://github.com/ben-manes/caffeine) without any issue. Its not likely that the final release made a major change here based on the claimed bug fixes since rc-1.

Can you reproduce this in a project that I can checkout?

**Comment by ben-manes** [comment]
Works on a private project too.

**Comment by jochenberger** [comment]
This looks very much like #56. Are you sure, you're using 0.9?

**Comment by ben-manes** [comment]
@marcoRS Can you confirm again that you used v0.9? Otherwise I'll wait a few days and close as not reproducible if I don't hear an update.

**Comment by marcoRS** [comment]
Hi @ben-manes you are correct. Not sure how I messed up the versions. I verified and 0.9 works with Gradle 2.4 :+1:
