### ISSUE TITLE
Several of my dependencies are not resolving to the latest version

### ISSUE THREAD

**Issue by eygraber** [ben-manes/gradle-versions-plugin#574]
After running `dependencyUpdates` multiple times (including running `--refresh-dependencies`) there are a few of my dependencies that are being reported as up to date, but they are not.

https://github.com/MichaelRocks/libphonenumber-android is being reported as version 8.12.21 but the latest is 8.12.39
https://github.com/Kotlin/kotlinx.coroutines is being reported as 1.5.1 but the latest is 1.6.0-RC2

**Comment by eygraber** [comment]
Ah just realized this is because I have a resolution strategy for those dependencies. Is there any way to disable that when running dependencyUpdate?

**Comment by eygraber** [comment]
I wrapped my resolution strategy in `if("dependencyUpdate" !in gradle.startParameter.taskNames)`

**Comment by ben-manes** [comment]
nice, that's one of the common approaches that I was trying to dig up. The other is to use

```gradle
gradle.taskGraph.whenReady { taskGraph ->
  if (!taskGraph.hasTask(dependencyUpdates)) { ... }
}
```
