### ISSUE TITLE
build.gradle files Could not find com.github.bumptech.glide:glide:4.12.0

### ISSUE THREAD

**Issue by princekhanggh** [ben-manes/gradle-versions-plugin#575]
Please help me How to solv this problem 

build.gradle files  Could not find com.github.bumptech.glide:glide:4.12.0
![Uploading IMG20211220174726.jpg…]()

**Comment by ben-manes** [comment]
Please add mavenCentral() to your repository listings. You are probably using jcenter or the plugin portal which proxy point versions but hold old metadata for dynamic range lookup.
