### ISSUE TITLE
Transitive dependency update detected

### ISSUE THREAD

**Issue by Goooler** [ben-manes/gradle-versions-plugin#579]
I run `dependencyUpdates` in android projects, `jacoco` updates detected, but I haven't depended on  directly, seems it was needed by AGP 7.0+ ? 
Is this a bug? You can test it in my [demo](https://github.com/Goooler/AndroidUiDemo).

```gradle
def isNonStable = { String version ->
  def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
  def regex = /^[0-9,.v-]+(-r)?$/
  return !stableKeyword && !(version ==~ regex)
}

tasks.named("dependencyUpdates").configure {
  rejectVersionIf {
    isNonStable(it.candidate.version)
  }
}
```
```txt
 - org.jacoco:org.jacoco.ant [0.8.3 -> 0.8.7]
     http://jacoco.org
```

**Comment by ben-manes** [comment]
Oh see #562 or #534. The android plugin adds an explicit dependency so it is picked up by our scan. The built-in Gradle plugin uses a "default dependency" so it is added silently and we can scrub it out. You could open a ticket for the Android team as its their usage mistake.

**Comment by Goooler** [comment]
Thx.
