### ISSUE TITLE
apache commons-codec reported as out of date

### ISSUE THREAD

**Issue by pwragg** [ben-manes/gradle-versions-plugin#583]
With the following dependency in your build.gradle file:

`implementation 'commons-codec:commons-codec:1.15'`

running the `dependencyUpdates` target reports that a newer version is available:

```
The following dependencies have later milestone versions:
 - commons-codec:commons-codec [1.15 -> 20041127.091804]
```
Looking at [maven central](https://mvnrepository.com/artifact/commons-codec/commons-codec) that version is from Nov 2005 and 1.15 is the current version at the time of raising this issue.
Thanks.

**Comment by ben-manes** [comment]
Maven Central is actually this link:
https://search.maven.org/search?q=g:commons-codec%20AND%20a:commons-codec

That shows the same bad version. Unfortunately the maven / gradle resolve versions based on the metadata and versioning rules. The latest version by Maven's rule has the largest number, as you might bug fix an old version but not consider it the latest. Sadly that means that clients must exclude this version as invalid or they need to adopt this larger format, which they did not do.

In my build I have the following, which you could adapt from.

```gradle
def isNonStable = { String version ->
  def stableKeyword = ['RELEASE', 'FINAL', 'GA', 'JRE'].any { version.toUpperCase().contains(it) }
  def unstableKeyword = ['PREVIEW'].any { version.toUpperCase().contains(it) }
  def regex = /^[0-9,.v-]+(-r)?$/
  return (!stableKeyword || unstableKeyword) && !(version ==~ regex)
}

dependencyUpdates.rejectVersionIf {
  (isNonStable(it.candidate.version) && !isNonStable(it.currentVersion)) ||
  (it.candidate.module == 'commons-io' && it.candidate.version.startsWith('2003')) ||
  (it.candidate.module == 'commons-net' && it.candidate.version.startsWith('2003'))
}
```

**Comment by ben-manes** [comment]
Maven's [Version Order Specification](https://maven.apache.org/pom.html#Version_Order_Specification). We resolve through Gradle which implements this.

**Comment by pwragg** [comment]
@ben-manes Thanks very much for the thorough explanation. I can add the additional lines to the rejectVersionIf in my gradle file as suggested. Thanks again.
