### ISSUE TITLE
how to ignore: Failed to determine the latest version for the following dependencies

### ISSUE THREAD

**Issue by jonathanlermitage** [ben-manes/gradle-versions-plugin#587]
I am not sure that's an issue with gradle-versions-plugin or Gradle itself, but I'm working on an IntelliJ plugin and the `dependencyUpdates` task fails to determine the latest version for the following dependencies (third-party IntelliJ plugins):  
```
> Task :dependencyUpdates
...
Failed to determine the latest version for the following dependencies (use --info for details):
 - unzipped.com.jetbrains.plugins:AngularJS
 - unzipped.com.jetbrains.plugins:CSS
 - unzipped.com.jetbrains.plugins:JavaScriptLanguage
 - unzipped.com.jetbrains.plugins:platform-images
...
BUILD SUCCESSFUL in 1s
```
The [full output with --info on pastebin](https://pastebin.com/A6xG2u4N).
The [gradle build file](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/ide203/build.gradle.kts). 
Is there a way to hide these messages? Thx!

**Comment by ben-manes** [comment]
You could use a [custom report](https://github.com/ben-manes/gradle-versions-plugin#report-format). A simple approach would be to use our [PlainTextReporter](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy) and clear out the unresolvable dependencies, e.g.

```gradle
import com.github.benmanes.gradle.versions.reporter.PlainTextReporter

dependencyUpdates {
  outputFormatter = { result ->
    result.unresolved.dependencies.clear()
    def plainTextReporter = new PlainTextReporter(project, revision, gradleReleaseChannel)
    plainTextReporter.write(System.out, result)
  }
}
```

**Comment by jonathanlermitage** [comment]
Thank you v. much 👍 , it works fine.
