### ISSUE TITLE
[Feature Request] Determine version of plugins added in settings.gradle

### ISSUE THREAD

**Issue by jaredsburrows** [ben-manes/gradle-versions-plugin#588]
Is there a way to determine the latest version of plugins added in `settings.gradle(.kts)`?

```
plugins {
  id("com.gradle.enterprise") version "3.8.1"
}

gradleEnterprise {
  buildScan {
    termsOfServiceUrl = "https://gradle.com/terms-of-service"
    termsOfServiceAgree = "yes"
    publishAlways()
  }
}
```

See: https://plugins.gradle.org/plugin/com.gradle.enterprise

**Comment by ben-manes** [comment]
I looked into that briefly for #367 to find the API we'd need to use,

> I suppose we would need to use [Settings](https://docs.gradle.org/current/javadoc/org/gradle/api/initialization/Settings.html) and evaluate both `getBuildscript()` and `getPluginManagement()`.

**Comment by jaredsburrows** [comment]
@ben-manes Should we close this in favor or #367 ?
