### ISSUE TITLE
Stable releases with google cloud dependencies

### ISSUE THREAD

**Issue by knyttl** [ben-manes/gradle-versions-plugin#589]
Consider following [`build.gradle.kts`](https://gist.github.com/knyttl/6c849f82bf9bac3653e080989359f0ca).

Note there is check for non-stable updates I found in [documentation](https://github.com/ben-manes/gradle-versions-plugin).

The problem is that the google dependencies match to be "non-stable" and so it goes through ALL OF THEM which takes a very long time and in the end it completely fails.

I guess it would be great if the rule could be something like:

- if the dependency "looks" stable, than search ONLY for stable dependencies
- if the dependency "does not look" stable, than search also for non-stable dependencies

Or maybe:

 - if there is no newer stable dependency, then don't search among older dependencies.

The same also applies for dependencies like:

https://mvnrepository.com/artifact/com.google.apis/google-api-services-youtube

For instance, my current version is `com.google.apis:google-api-services-youtube:v3-rev20210915-1.32.1`: and the log for searching for newer one looks like this: https://gist.github.com/knyttl/f3b29e61b03dc4b5dff7bf4440c28dad

**Comment by knyttl** [comment]
Note that this is all causes by the "select stable":

```kotlin
// select only stable versions for dependency updates with `gradle dependencyUpdates`
fun isNonStable(version: String): Boolean {
    val stableKeyword = listOf("RELEASE", "FINAL", "GA").any { version.toUpperCase().contains(it) }
    val regex = "^[0-9,.v-]+(-r)?$".toRegex()
    val isStable = stableKeyword || regex.matches(version)
    return isStable.not()
}

tasks.withType<DependencyUpdatesTask> {
    rejectVersionIf {
        isNonStable(candidate.version)
    }
}
```

**Comment by ben-manes** [comment]
Isn't that what Example 2 shows?

> Example 2: disallow release candidates as upgradable versions from stable versions
>
> ```groovy
> // https://github.com/ben-manes/gradle-versions-plugin
> tasks.named("dependencyUpdates").configure {
>  rejectVersionIf {
>    isNonStable(it.candidate.version) && !isNonStable(it.currentVersion)
>  }
>}
>```

Unfortunately there is little consistency in version patterns, as few follow Maven's [version format](https://octopus.com/blog/maven-versioning-explained). The examples are suggestions but we don't build in any hard rules because it is too error prone.

**Comment by ben-manes** [comment]
Have you tried my suggestion?

In your build it rejects all versions so Gradle selects the next candidate. We don’t short circuit that so it queries until exhausted of options. I’m sure we could add a short circuit as that does seem nice, but the second case should also solve it directly.

**Comment by knyttl** [comment]
> Have you tried my suggestion?

🤦 okay, I am an idiot, I missed the `&& !isNonStable(currentVersion)` part.

Sorry and thanks for suggestion.

**Comment by ben-manes** [comment]
haha, no worries. 🙂
