### ISSUE TITLE
CVEs for xstream 1.4.17

### ISSUE THREAD

**Issue by ghgrgr** [ben-manes/gradle-versions-plugin#594]
Thank you for this great plugin!

xstream 1.4.17 has a number of [CVEs](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&isCpeNameSearch=false&cpe_vendor=cpe%3A%2F%3Axstream_project&cpe_product=cpe%3A%2F%3A%3Axstream&cpe_version=cpe%3A%2F%3Axstream_project%3Axstream%3A1.4.17), which have been fixed in 1.4.19.

I am not sure if the plugin is affected by the CVEs (it was not by a [previous xstream CVE](https://github.com/ben-manes/gradle-versions-plugin/issues/506#issuecomment-839888350)). Even if not, it would probably make people sleep better at night if the xstream version could be increased to 1.4.19 or the dependency completely removed.

By the way: There are gradle plugins such as [Gradle License Report](https://github.com/jk1/Gradle-License-Report) that automate finding known CVEs in your dependencies.

**Comment by ben-manes** [comment]
Thanks. It's not really a problem due to the nature of how the plugin is used, Gradle's classloader isolation, and build systems being internal tools. It's certainly good to keep dependencies up to date, though.
