### ISSUE TITLE
Version 0.9 is in no repository

### ISSUE THREAD

**Issue by Steffeng5** [ben-manes/gradle-versions-plugin#60]
Hi,

I wanted to install version 0.9 as shown in your README. But I only can find 0.4 in Maven Central and no package in jcenter repository

**Comment by ben-manes** [comment]
Here is the [JCenter artifact](https://bintray.com/fooberger/maven/com.github.ben-manes%3Agradle-versions-plugin) at 0.9. If you follow the example in the README it should download.

As proof, you can take a look at my [caching project](https://github.com/ben-manes/caffeine) and run `gradle dU`.

**Comment by Steffeng5** [comment]
Ah i just ran into the same issue as discussed here: https://github.com/ben-manes/gradle-versions-plugin/issues/47
