### ISSUE TITLE
Publish to Mavencentral again

### ISSUE THREAD

**Issue by jaredsburrows** [ben-manes/gradle-versions-plugin#603]
Official:
https://search.maven.org/search?q=a:gradle-versions-plugin

Mirror:
https://mvnrepository.com/artifact/com.github.ben-manes/gradle-versions-plugin

@ben-manes What do you think? We can use @vanniktech's https://github.com/vanniktech/gradle-maven-publish-plugin.

**Comment by ben-manes** [comment]
Since the plugin portal became the defacto, is there a good reason? Those old versions are prior to the portal and this hasn't been an issue. The only recent concern is jitpack creating corrupted builds that some people are pulling in.

**Comment by jaredsburrows** [comment]
It seems that the Gradle repo only stores the `jar` and `POM` file, see https://plugins.gradle.org/m2/com/github/ben-manes/gradle-versions-plugin/0.42.0/.

At least with Maven, we can store more artifacts. However, since this is a plugin, we do not need the `javadoc`, `report` or `sources` jars.

**Comment by ben-manes** [comment]
yeah, I think we should favor removing those tasks instead of returning to Central

**Comment by jaredsburrows** [comment]
I just wish there was support for plugin snaphots or maybe we can start publishing snapshots per build with `-SNAPSHOT`.

**Comment by ben-manes** [comment]
I think that jitpack.io works okay for this most of the time
