### ISSUE TITLE
Ignore snapshot?

### ISSUE THREAD

**Issue by henrik242** [ben-manes/gradle-versions-plugin#61]
Is there a way to get the plugin to ignore snapshot dependencies?

**Comment by ben-manes** [comment]
Gradle supports revision tags as part of its resolution strategy when querying a dependency. The plugin should ignore snapshots by default and you can toggle the revision tag that is queries with. From the readme,

***

>The revision task property controls the resolution strategy of determining what constitutes the latest version of a dependency. The following strategies are supported:

>* release: selects the latest release
>* milestone: select the latest version being either a milestone or a release (default)
>* integration: selects the latest revision of the dependency module (such as SNAPSHOT)
The strategy can be specified either on the task or as a system property for ad hoc usage:

> `gradle dependencyUpdates -Drevision=release`

**Comment by ben-manes** [comment]
Closing as no followup indicating this is a bug.

**Comment by henrik242** [comment]
But I still see stuff like this when doing `gradle dependencyUpdates` (without any arguments):

Download http://mavenproxy.finntech.no/finntech-snapshot/org/apache/camel/camel-core/2.16-SNAPSHOT/camel-core-2.16-20150618.032519-96.pom
Download http://mavenproxy.finntech.no/finntech-snapshot/org/apache/camel/camel-parent/2.16-SNAPSHOT/camel-parent-2.16-20150618.033018-91.pom

Is that normal?  It can be quite a lot of them.

**Comment by ben-manes** [comment]
Nope, that's a problem. The snapshots should be filtered by Gradle since it does the resolution for us.

Can you put a test sample together? I'd need to know the repositories, dependencies, and Gradle version to replicate.

**Comment by henrik242** [comment]
Reproduce by running `gradle dependencyUpdates` with the following build.gradle:

    plugins {
      id "com.github.ben-manes.versions" version "0.9"
    }

    apply plugin: 'java'

    repositories {
      maven { url "https://repository.apache.org/content/repositories/snapshots/" }
      maven { url "https://repository.apache.org/content/repositories/releases/" }
    }

    dependencies {
      compile(
        "org.apache.camel:camel-core:2.13"
      )
    }

**Comment by ben-manes** [comment]
Thanks! I'll try to take a look at this over the weekend.

**Comment by ben-manes** [comment]
Oh, which Gradle version?

**Comment by henrik242** [comment]
2.4

**Comment by ben-manes** [comment]
```bash
$ gradle dU
:dependencyUpdates

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes:gradle-versions-plugin:0.10.1

The following dependencies have later milestone versions:
 - org.apache.camel:camel-core [2.13 -> 2.15.2]

Generated report file build/dependencyUpdates/report.txt

```

The process does take a while because Gradle downloads all snapshot versions for some reason,

**Comment by ben-manes** [comment]
Oh, I misunderstood your issue. Its not that the report is incorrect, but that it downloads the snapshot metadata excessively making the task slow. 

Unfortunately this is a bug in Gradle and cannot be resolved by this plugin without duplicating the built-in dependency handling. There are two issues that you can pursue with the Gradle folks. First is that it unnecessarily downloads all of the snapshot versions, rather than just inspecting the latest defined in `maven-metadata.xml`. The second that dependencies are downloaded using sequential http requests instead of being parallel ([GRADLE-2582](https://issues.gradle.org/browse/GRADLE-2582)).

The downloading will diminish after the first run, due to the Gradle cache. This makes the plugin unnecessarily slow, but is outside of our control. A fix would improve the experience for all Gradle users.

**Comment by ben-manes** [comment]
I found this occurs due to JCenter, but I have no idea why. Posted a [bug](https://discuss.gradle.org/t/excessive-downloads-during-resolution/10193) on the Gradle forum.

**Comment by henrik242** [comment]
OK, thanks for investigating.  Maybe you should consider some duplication of the dependency resolution?  It could solve issues #25 and #53 as well, but I realize it's a lot of work...

**Comment by ben-manes** [comment]
Unfortunately that could be quite error prone if naively handled.

First there's emulating the repository http calls, which could require auth and passing through an http proxy. Then both Maven and Ivy repository types need to be handled which requires URL munging, consuming the xml formats, and features like Ivy dynamic resolve mode. We'd need to perform dependency rewrites by Gradle's dependency resolve rules, module replacement, and component rules. Finally the comparator needs to follow the Maven/Ivy versioning rules. We also need to track Gradle to emulate new dependency features and API changes, in a backward compatible way. And then we can add our enhancements of parallel http and custom versioning rules to that!

The naive way of just doing the http and supporting Maven only will cover the majority of users, but leave an uncrossable chasm for user's expecting their customizations to be honored. Its more elegant to delegate all that work to Gradle, but we're stuck waiting for a few usability improvements to be addressed.
