### ISSUE TITLE
Unable to hide some rc/cr/beta versions

### ISSUE THREAD

**Issue by henrik242** [ben-manes/gradle-versions-plugin#64]
With version 0.11.1 I still get a report that suggests beta/cr/rc versions:

> The following dependencies have later milestone versions:
>  - com.fasterxml.jackson.jaxrs:jackson-jaxrs-providers [2.5.3 -> 2.6.0-rc2]
>  - com.fasterxml.jackson.module:jackson-module-jaxb-annotations [2.5.3 -> 2.6.0-rc2]
>  - org.hibernate:hibernate-validator [5.1.3.Final -> 5.2.0.CR1]
>  - org.mockito:mockito-core [1.10.19 -> 2.0.20-beta]
>  - org.restlet.jee:org.restlet [2.3.0 -> 3.0-M1]

Here's my suppressions config:

    configurations {
      all {
        resolutionStrategy {
            componentSelection {
                all { ComponentSelection selection ->
                    boolean rejected = ['alpha', 'beta', 'rc1','rc2', 'cr1', 'cr2', 'm1', 'm2'].any { qualifier ->
                        selection.candidate.version.contains(qualifier)
                    }
                    if (rejected) {
                        selection.reject('Release candidate')
                    }
                }
            }
        }
      }
    }

**Comment by ben-manes** [comment]
Can you try putting that configuration into an `allprojects` block? If you have a multi-module project then those suppressions may only occur at the root project.

I have a unit test that passes, so I'm hoping this is just a doc fix.

**Comment by henrik242** [comment]
Thanks, that worked!  It still didn't skip dependencies marked CR1 and M1, but I guess it's case sensitive?

I'll try again with correct case, but it'll take a while.  It seems `dependencyUpdates` has grown *much* slower:

    Total time: 1 hrs 25 mins 16.35 secs

**Comment by jochenberger** [comment]
Yes, that's a know issue in 0.11.1, it will be fixed in 0.11.2 which I'm going to release shortly.
As for CR1 and M1, yes, as you use `String#contains`, that's case sensitive. You should probably add a `toLowerCase(Locale.US)` or something.

**Comment by henrik242** [comment]
Good to know! Here's what I use now:

    configurations { all { resolutionStrategy { componentSelection { all {
        // Used by gradle-versions-plugin:
        ComponentSelection selection ->
            boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier ->
                selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
            }
            if (rejected) {
                selection.reject('Release candidate')
            }
    }}}}}

Looking forward to the speed improvement :)
