### ISSUE TITLE
Confusing report if different versions of a library are used in root and subproject

### ISSUE THREAD

**Issue by jochenberger** [ben-manes/gradle-versions-plugin#65]
Extracting from #63.
I have a project with a subproject. The root project depends on version 0.1.2 of a library and the subproject depends on 0.3.0, which is the latest version. The versions plugin is applied to the root project only.
0.11.3 lists the version as upgradeable [0.3.0->0.3.0], 0.10.x listed it as up-to-date (0.3.0).

**Comment by jochenberger** [comment]
The library is added to the VersionMapping twice.

**Comment by ben-manes** [comment]
It should be shown twice (#62), but one listed as upgradable and the other as up-to-date. Obviously that's not always working, though I swore my test listed them correctly.

**Comment by ben-manes** [comment]
Please test and reopen if this is still broken. I made the tests explicit instead of simply checking the counts.

**Comment by ben-manes** [comment]
Reopening after visual inspecting the report, which is screwy.

**Comment by ben-manes** [comment]
Okay, now looks right after tweaking the reporter. That area needs a lot of cleanup, which I'll do after things settle down in the resolution logic.

**Comment by jochenberger** [comment]
I'm afraid it's not entirely fixed. Meanwhile, version 0.4.0 of the library is available. The root project is still at 0.1.2 and the subproject is at 0.3.0. Not, the plugin says `[0.3.0 -> 0.4.0]` for both the root and the subproject.

**Comment by ben-manes** [comment]
Could you put a simple build file example that I can test with?

I'm tweaking the below script with different versions. If the dependency maps to different groups then I see it listed individually as desired. If they fit in the same group, e.g. upgrade 15, 16-rc-1 --> 18, then only one is listed. That indicates that the analysis / version mapping is correct, but there is probably a map in the reporter that needs to be replaced with a multi-map.

```gradle
apply plugin: 'com.github.ben-manes.versions'

buildscript {
  repositories {
    jcenter()
    mavenLocal()
  }

  dependencies {
    classpath 'com.github.ben-manes:gradle-versions-plugin:+'
    classpath 'com.google.guava:guava:15.0'
  }
}

configurations {
  upgradesFound
}

dependencies {
  upgradesFound 'com.google.guava:guava:16.0-rc1'
}
```

**Comment by ben-manes** [comment]
I updated the example's [build.gradle](https://github.com/ben-manes/gradle-versions-plugin/blob/master/examples/build.gradle) to experiment with. I think my changes fix this.

**Comment by jochenberger** [comment]
Yes, it works as expected now, thanks.
