### ISSUE TITLE
Download .pom files for analysis in parallel so it's faster

### ISSUE THREAD

**Issue by jimshowalter** [ben-manes/gradle-versions-plugin#664]
We're seeing 5-10 minutes added to each stage in our Jenkins pipelines due to running dependencyUpdates.

The time is all due to dependencyUpdates.resolutionStrategy.componenSelection needing to download and then analyze poms, the bulk if which it filters out.

For example:

`...
18:48:23  Selection of org.springframework.boot:spring-boot-starter-test:2.1.0.BUILD-SNAPSHOT rejected by component selection rule: Component status integration rejected by revision milestone
...
18:48:48  Downloading https://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-test/2.4.0-M4/spring-boot-starter-test-2.4.0-M4.module to /home/container_jenkins/.gradle/.tmp/gradle_download15183509978219558052bin
18:48:48  Selection of org.springframework.boot:spring-boot-starter-test:2.4.0-M4 rejected by component selection rule: Release candidate
...`

If the fetches were done by threads in a big pool (with tunable size), this would drop from minutes to seconds.

We did something similar for a custom Gradle plugin that verifies signatures. It used to take 2-4 minutes because it was downloading the signatures one at a time. When we added 300 threads, it dropped to 2-3 seconds.

**Comment by jimshowalter** [comment]
That's unfortunate--wonder why the Gradle folks hate threads so much. They also only support running one daemon at a time, and there are lock problems.

We're already limiting which repos are searched.

**Comment by ben-manes** [comment]
You can nag them on https://github.com/gradle/gradle/issues/15071. Long term it seems they are going to defer dependency updates to an in development GitHub service (https://github.com/gradle/github-dependency-extractor).
