### ISSUE TITLE
Suppressing qualifier from dependencyUpdates also makes it unavailable for build

### ISSUE THREAD

**Issue by henrik242** [ben-manes/gradle-versions-plugin#68]
I don't want to show beta versions (such as `10.1-b28`) when using `dependencyUpdates`, so I have this configuration:

    allprojects {
      configurations { all { resolutionStrategy { componentSelection { all {
        ComponentSelection selection ->
            boolean rejected = ['b'].any { qualifier ->
                selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
            }
            if (rejected) {
                selection.reject('Release candidate')
            }
      }}}}}
    }

That works, but it also stops `./gradlew build` from using transitive dependencies from dependencies that I actually use:

    > Could not find org.glassfish.hk2:hk2-api:2.4.0-b12.
      Searched in the following locations:
          http://mavenproxy.xxx.no/xxx-snapshot/org/glassfish/hk2/hk2-api/2.4.0-b12/hk2-api-2.4.0-b12.pom
      Required by:
          no.xxx.yyy:zzz-api:1.0.0-SNAPSHOT > org.glassfish.jersey.core:jersey-client:2.18

`org.glassfish.jersey.core:jersey-client:2.18` dependes on `org.glassfish.hk2:hk2-api:2.4.0-b12`, but isn't allowed to use it.

Is it possible to make the `resolutionStrategy` only apply to `dependencyUpdates`?

**Comment by ben-manes** [comment]
As a hack you could wrap a conditional to apply the constraint only if `dependencyUpdates` is being run, e.g.
```gradle
if (gradle.taskGraph.hasTask(dependenyUpdates)) { ... }
```

There might be cleaner alternatives, but I'd have to play around for a while to see what our options are. The `componentSelection` takes a configuration name, so you might be able to isolate the constraints that way instead of using `all`. However the task copies the configuration, so the name becomes originalCopy and can't be defined on only the task's copied configuration. 

I've tried to avoid adding a configuration extension because it makes it too attractive to throw in a lot of random flags instead of relying on the Gradle API. This might be a case where an extension to apply a `resolutionStrategy` only on the dependencyUpdate's copy of the configuration makes sense. I think the desired effect if the latest dependency couldn't be resolved with that selection rule would be to list it as up to date.

**Comment by henrik242** [comment]
I tried adding that before *allprojects*, before *configurations*, and before *boolean rejected*.  The build just fails (even when I fixed the typo in "dependenyUpdates" :) )

**Comment by ben-manes** [comment]
How about trying`tasks.'dependencyUpdates'.doFirst { ... }`?

**Comment by henrik242** [comment]
Yup, that works. Thanks!

Lots of curly brackets, though :)

    tasks.'dependencyUpdates'.doFirst {
      allprojects { configurations { all { resolutionStrategy { componentSelection { all {
        ComponentSelection selection ->
            if (gradle.taskGraph.hasTask(dependencyUpdates)) {
                boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm', 'b'].any { qualifier ->
                    selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
                }
                if (rejected) {
                    selection.reject('Release candidate')
                }
      }}}}}}}
    }

**Comment by henrik242** [comment]
I get a bunch of deprecation warnings now, by the way. They look like this:

    Attempting to change configuration ':some-project:someTarget' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0

**Comment by ben-manes** [comment]
Its not a proper fix, obviously. When Gradle becomes rules based the configuration can't be changed dynamically,

**Comment by henrik242** [comment]
Any updates on this?  3.0 is coming closer :)

**Comment by ben-manes** [comment]
Sorry that I haven't been actively working on this project. I know it probably frustrates @jochenberger, too. I was unsuccessful in handing it off to the Gradle team, who want the feature but lack the resources. Its more a lack of motivation than difficulty as there's always more to do. Either contributors, a new owner, or a big kick in the butt are needed to get through this backlog.

**Comment by jochenberger** [comment]
I'm not frustrated. I'm also working on many different projects and have to let people wait sometimes. Maybe you can outline a preferred solution on some of the issues to give potential contributors some idea how to fix them.

**Comment by ben-manes** [comment]
The verbose version of this feature (explicit rule) is now supported. You can define it to be scoped only on the task by using,

```gradle
dependencyUpdates.resolutionStrategy = {
  componentSelection { rules ->
    rules.all { ComponentSelection selection ->
      boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier ->
        selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
      }
      if (rejected) {
        selection.reject('Release candidate')
      }
    }
  }
}
```

We should probably add a pattern based property to make it a one liner, but I think this is okay for now.

**Comment by ben-manes** [comment]
@jochenberger I resolved all of the outstanding bugs. Unless your interested in tackling one of the enhancements, I'm satisfied declaring master as `0.12.0`. When releasing we should update the README with the above `resolutionStrategy` example.

**Comment by jochenberger** [comment]
@ben-manes Thanks, you're the hero of the day. :-) I'll create a 0.12.0 release right away.

**Comment by henrik242** [comment]
Fantastic work!

**Comment by henrik242** [comment]
Holding my breath while refreshing plugins.gradle.org :D

**Comment by ben-manes** [comment]
Its live on bintray, thanks to @jochenberger :-)
