### ISSUE TITLE
Update build.gradle (write to file)

### ISSUE THREAD

**Issue by wafisher** [ben-manes/gradle-versions-plugin#683]
I must be missing something since I can't find a single issue on this topic but does this plugin not have a mode where it updates `build.gradle` for you?

Thanks!

**Comment by ben-manes** [comment]
Nope, that is out of scope. This plugin only reports the upgrades and lets you decide how to manage dependency versions, what to upgrade, etc. There are [extensions](https://github.com/ben-manes/gradle-versions-plugin#related-plugins) that offer that functionality.

Gradle does not dictate an approach towards version management, so many try to perform string replacements in build files. That doesn't work for the common [dependencies.gradle](https://github.com/ben-manes/caffeine/blob/master/gradle/dependencies.gradle) and other programatic approaches. The newer Version Catalogs is an an attempt to define an blessed solution and there is an [plugin](https://github.com/littlerobots/version-catalog-update-plugin) for updating those.

**Comment by wafisher** [comment]
OK thank you for the info. Very helpful!
