### ISSUE TITLE
can the readme give details of how to add this plugin in kotlin dsl project

### ISSUE THREAD

**Issue by nagkumar** [ben-manes/gradle-versions-plugin#685]
I want to upgrade dependencies in build.gradle.kts, can you pl. let me know how to add this plugin in .kts file

**Comment by ben-manes** [comment]
The README includes kotlin code samples and there is an [example](https://github.com/ben-manes/gradle-versions-plugin/blob/master/examples/kotlin/build.gradle.kts) kotlin build. You could also search github for this plugin in kotlin build files for how others have used it.

**Comment by nagkumar** [comment]
Readme usage has only for gradle, not for kotlin..

![image](https://user-images.githubusercontent.com/332234/181419998-9b686b20-779b-4063-9446-7d1b8fa5beb6.png)

maybe some thing as in this would help

https://plugins.gradle.org/plugin/com.github.ben-manes.versions
