### ISSUE TITLE
isNonStable not working?

### ISSUE THREAD

**Issue by ChrLipp** [ben-manes/gradle-versions-plugin#687]
I had the following plugin configuration which worked fine:

    tasks.named("dependencyUpdates").configure {
      rejectVersionIf {
        ['alpha', 'beta', 'm', 'rc', 'snapshot'].any { qualifier ->
          it.candidate.version.toLowerCase().contains(qualifier) &&
                  !it.candidate.version.toLowerCase().contains('maven')
        }
      }
    }

The result I got was

	The following dependencies are using the latest milestone version:
	 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.42.0
	 - io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.0.13.RELEASE
	 - org.codehaus.groovy:groovy:3.0.12
	 - org.springframework.boot:org.springframework.boot.gradle.plugin:2.7.3
	 - org.springframework.boot:spring-boot-starter:2.7.3
	 - org.springframework.boot:spring-boot-starter-test:2.7.3

When I change the config according the docs to

    tasks.named("dependencyUpdates").configure {
      rejectVersionIf {
        isNonStable(it.candidate.version)
      }
    }

I receive

	Failed to determine the latest version for the following dependencies (use --info for details):
	 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin
	 - io.spring.dependency-management:io.spring.dependency-management.gradle.plugin
	 - org.codehaus.groovy:groovy
	 - org.springframework.boot:org.springframework.boot.gradle.plugin
	 - org.springframework.boot:spring-boot-starter
	 - org.springframework.boot:spring-boot-starter-test

Tested with

    GRADLE_VERSION = 7.5.1
    GRADLE_VERSIONS_PLUGIN_VERSION = 0.42.0

**Comment by ben-manes** [comment]
did you define a isNonStable method? That’s in the docs, not by the plugin
