### ISSUE TITLE
Feature request: Loop through all versions in case the latest is rejected

### ISSUE THREAD

**Issue by whydoievenneedthis** [ben-manes/gradle-versions-plugin#700]
As far as I can tell by logging and reading the other issues, the plugin works by getting the `maven-metadata.xml` file and getting the `versioning.latest`, which is fine most of the time.

However, let's take protobuf-java for a moment:
https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java

The true latest version of it is 3.21.7 from sept 29, however the reported latest version is 4.0.0-rc-2 from 2020. Now I can make a `rejectVersionIf`, which will check the module and version and reject the suggested 4.0.0-rc-2 version. However if I am currently using 3.21.5, I would like to get a ping that 3.21.7 is actually out and available, and that I could update to that one.
Would it be possible to have an option to start looping through the full version list, in reverse, in case a rejection comes in, until it reaches either a non-rejection (offers the new version) or the currently used version (no newer version)?

**Comment by ben-manes** [comment]
This plugin uses Gradle's dependency management apis, which behind the scenes inspects `maven-metadata.xml` (in addition to `ivy.xml` and `.module` metadata). The `rejectVersionIf` is a convenience layer on top of a `resolutionStrategy` which will walk from the latest version to the accepted version. That is provided with your current version and the candidate. This lets you reject a major release candidates but still see incremental version upgrades, like you are requesting. I believe what you are asking for is already how it functions.

**Comment by whydoievenneedthis** [comment]
You are right, was misinterpreting the results I was seeing. I messed up the condition inside the `rejectVersionIf` and it ran into an exception, so it failed to continue resolving all other versions.
