### ISSUE TITLE
Ability to use `failOnNonReproducibleResolution` with the plugin?

### ISSUE THREAD

**Issue by boris-petrov** [ben-manes/gradle-versions-plugin#701]
I wanted to add the following to my `build.gradle` file:

```gradle
configurations.all {
	resolutionStrategy {
		failOnNonReproducibleResolution()
	}
}
```

Just to have more "safety" with dependencies. However, that seems to break the versions-plugin with a message that dynamic-versions are disabled (as [failOnNonReproducibleResolution](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ResolutionStrategy.html#failOnNonReproducibleResolution) includes [failOnDynamicVersions](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ResolutionStrategy.html#failOnDynamicVersions)). Any suggestions on how can I make the plugin work *and* have this setting enabled?

**Comment by ben-manes** [comment]
In #592

> Usually you can get around this by conditionalizing the your resolution strategy to no-op if the `dependencyUpdate` task will be run. The simplest is checking for it in`gradle.startParameter.taskNames`, with a fancier version being to use `gradle.taskGraph.whenReady`. I think the latter might not work since Gradle 7.0 as I recall them making things stricter.

**Comment by ben-manes** [comment]
Also looks like there is a workaround in #593, maybe not yet released?

**Comment by boris-petrov** [comment]
Ah, sorry, I searched for `failOnNonReproducibleResolution` before opening the issue, should have also searched for `failOnDynamicVersions`!

That PR sounds like it resolves the issue, yes. But it's not released, no. Perhaps you can do that? :smile: 

Thanks for the prompt response!

**Comment by ben-manes** [comment]
If you'd like, you can send a PR that follows a similar pattern to disable `failOnNonReproducibleResolution` and then we could trigger a release afterwards?

**Comment by boris-petrov** [comment]
I'm not sure that's needed for `failOnNonReproducibleResolution`. If I understand correctly from Gradle's documentation (the two links I sent above) - `failOnNonReproducibleResolution` just enables `failOnDynamicVersions` and `failOnChangingVersions`. The former is already fixed. I'm not sure if the latter would break `gradle-versions-plugin`? My tests show it doesn't seem so. So perhaps no change from `master` is needed?

**Comment by ben-manes** [comment]
oh then that's good, I am not familiar with that option

**Comment by boris-petrov** [comment]
Yeah, we can try - if you release a new version, I'll try it with `failOnNonReproducibleResolution` and `failOnDynamicVersions`. If it works, great. If the former doesn't work, I'll submit a PR and you can release a second version. :smile:

**Comment by ben-manes** [comment]
You could install the plugin locally and use `mavenLocal()` in your project.

Otherwise, I am reviewing how a release is performed with the build and rewrite to kotlin since I am not familiar with the process anymore.

**Comment by boris-petrov** [comment]
Sure, no worries! I'll see how this local installation works and I'll write here in a few hours with the results. Thanks!

**Comment by ben-manes** [comment]
easy peasy, released!

/cc @jaredsburrows

**Comment by boris-petrov** [comment]
Great, thanks! I confirm that the new version fixes the issue with `failOnNonReproducibleResolution`!

**Comment by ben-manes** [comment]
wonderful, thanks @keykey7! 😃
