### ISSUE TITLE
Latest version v0.43.0 doesn't produce html report

### ISSUE THREAD

**Issue by gkurmaev** [ben-manes/gradle-versions-plugin#703]
After update yesterday our task, which is configured the following way:
```
tasks.named<DependencyUpdatesTask>("dependencyUpdates").configure {

  // Example 1: reject all non stable versions
  rejectVersionIf {
    isNonStable(candidate.version)
  }

  // optional parameters
  checkConstraints = true
  checkForGradleUpdate = true
  outputFormatter = "json, html"
  outputDir = "build/dependencyUpdates"
  reportfileName = "report"
}
```

is no longer generating json and html reports (but a json and txt instead), which we uploaded somewhere else as a part of CI-pipeline, thus breaking it.

**Comment by gkurmaev** [comment]
Removing the extra space after the comma actually fixed the issue, so
```
outputFormatter = "json,html"
```

**Comment by ben-manes** [comment]
Looks like a small typo in the groovy to kotlin migration. The groovy code used String's `replaceAll` which takes a regex, whereas the kotlin version uses `replace` which does not.

https://github.com/ben-manes/gradle-versions-plugin/blob/b53e44f1459e7950706e77007b916ee522684baf/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy#L127

https://github.com/ben-manes/gradle-versions-plugin/blob/cc714f8154839b1a78fa02425cdac30cc8195e1d/gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.kt#L112

**Comment by ben-manes** [comment]
hmm.. seems that kotlin's [replace]([DependencyUpdatesReporter.kt](https://github.com/ben-manes/gradle-versions-plugin/blob/cc714f8154839b1a78fa02425cdac30cc8195e1d/gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.kt#L112)) is the same as Java's [replaceAll](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#replaceAll(java.lang.String,java.lang.String)), so I'm not sure why it wouldn't take.

**Comment by ben-manes** [comment]
Oh, they have multiple variants overloaded with the same name and different behavior. Very confusing stdlib, but I think we can use a trim() here. Seems kotlin has many footguns, like their infamous non-atomic operations on atomics...

**Comment by gkurmaev** [comment]
Oh wow, that was rather unexpected of you to actually fix a closed issue, thanks!
