### ISSUE TITLE
Version 44 fails with Gradle error

### ISSUE THREAD

**Issue by jimshowalter** [ben-manes/gradle-versions-plugin#710]
Upgraded to 0.42.0, tried to run ./gradle dependencyUpdates, and got immediate error from latest GA version of Gradle (7.5.1):

`$ ./gradlew dependencyUpdates
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'permissions-pdp'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find okio-jvm-2.10.0.jar (com.squareup.okio:okio:2.10.0).
     Searched in the following locations:
         https://box.jfrog.io/box/signedthirdpartymaven/com/squareup/okio/okio/2.10.0/okio-2.10.0.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s`

**Comment by ben-manes** [comment]
can you provide a minimal sample project to reproduce and debug from? Is it purely v42 vs v44 or does the Gradle version impact the results?

**Comment by jimshowalter** [comment]
I'll try to create a reduced sample. I doesn't matter if the Gradle version is 7.4.2 or 7.5.1 (didn't try any other versions).

**Comment by ben-manes** [comment]
for what it's worth, I kinda recall seeing this once when a repository had the pom metadata but not the corresponding jar. In that case it is an invalid maven repository and Gradle doesn't continue searching alternatives. The possible solutions are either to fix the repository or exclude the dependency using [repository content filtering](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering) if allowed. However, I don't see why this would be impacted by plugin version changes.

**Comment by jimshowalter** [comment]
I haven't been able to create a reduced version. We have th
![Screen Shot 2022-11-17 at 9 31 29 AM](https://user-images.githubusercontent.com/211780/202516951-34594f54-7902-4a37-a5d0-0744e7e1aef3.png)
e jar:

**Comment by ben-manes** [comment]
That has `okio-jvm-2.10.0.jar` while Gradle is looking for `okio-2.10.0.jar`.

**Comment by jimshowalter** [comment]
I saw that. I'll need to sync up with our Artifactory team to figure out what's going on. When I use only public repos, the problem goes away. You can close this.
