### ISSUE TITLE
Add a link to the plugin portal

### ISSUE THREAD

**Issue by onacit** [ben-manes/gradle-versions-plugin#711]
Thank you for such a great plugin which is my first plugin for every project.

I will be more helpful when anyone sees, on the README, a link to the [plugins.gradle.org/.../com.github.ben-manes.versions](https://plugins.gradle.org/plugin/com.github.ben-manes.versions) which serves usages along with the latest version.

Thank you.

**Comment by ben-manes** [comment]
Oh, it is there as a badge. 🙂 

<img width="332" alt="Screen Shot 2022-11-16 at 6 56 24 PM" src="https://user-images.githubusercontent.com/378614/202343662-7ce00e12-b3b0-4ea5-b9da-0016e2dec191.png">
