### ISSUE TITLE
[Support Question] Merge reports into a single file

### ISSUE THREAD

**Issue by captainepoch** [ben-manes/gradle-versions-plugin#712]
Hello!

I was wondering if there is any way of merging the reports from different modules into a single one, to have all the necessary updates located in a single file.

Thanks for the support!

Cheers!

**Comment by ben-manes** [comment]
> Multi-project build
> 
> In a multi-project build, running this task in the root project will generate a consolidated/merged report for dependency updates in all subprojects. Alternatively, you can run the task separately in each subproject to generate separate reports for each subproject.

**Comment by captainepoch** [comment]
Yeah, I read that, and I executed it, but when the task finished it created N different files with the report on each module.

I might missconfigured something, I'll try tomorrow.

Thanks, Ben!

**Comment by ben-manes** [comment]
It sounds like you applied the plugin inside of `allprojects` or `subprojects`. If you apply it only on the root project then you'll get a single report. You can look at [caffeine](https://github.com/ben-manes/caffeine) which does this.

**Comment by captainepoch** [comment]
You're right, I did that. I'll change it tomorrow.

Thank you very much again, Ben!

I'll close this issue then, if you don't mind.
