### ISSUE TITLE
Ver 0.43.0 breaks html report due to extra escape chars

### ISSUE THREAD

**Issue by daelfdude** [ben-manes/gradle-versions-plugin#715]
When running `./gradlew dependencyUpdates -q -DoutputFormatter=json,html -DoutputDir=./DependencyReport -DreportfileName=report :project-one:generateGradleLintReport :project-two:generateGradleLintReport :project-three:generateGradleLintReport :tproject -four:generateGradleLintReport :generateGradleLintReport` on Mac OS, the generated html report is missing the css styling and the 'click to expand' sections do not work when viewed in Chrome.  This appears to be due to some extra escape chars in the generated html file.  e.g. <style type=\"text/css\"> and  \$(document).ready

**Comment by ben-manes** [comment]
oh good find. PRs are appreciated 🙂

**Comment by marcinfigiel** [comment]
The same applies to 0.44.0. Additionally the `style` and `script` elements are placed incorrectly and `body` element is missing.

**Comment by ben-manes** [comment]
released, thanks @marcinfigiel
