### ISSUE TITLE
False exceeding versions

### ISSUE THREAD

**Issue by qoomon** [ben-manes/gradle-versions-plugin#72]
The plugin says these dependecies exceed the version found at the milestone revision level

18:42:51 The following dependencies exceed the version found at the milestone revision level:
18:42:51  - com.icegreen:greenmail [1.4.1 <- 1.3.1b]
18:42:51  - com.mangofactory:swagger-springmvc [0.9.5 <- 0.7.81-M1]
18:42:51  - com.ryantenney.metrics:metrics-spring [3.0.4 <- 3.0.0-RC4]
18:42:51  - commons-lang:commons-lang [2.6 <- 1.0-b1]
18:42:51  - org.liquibase:liquibase-core [3.3.2 <- 3.0.0-rc2]

**Comment by ben-manes** [comment]
There are some bug fixes on master. I haven't looked at you issue, but since you closed it I hope that you decided there wasn't a bug.

**Comment by jochenberger** [comment]
It that happens with a current version, that's probably because of #66.

**Comment by qoomon** [comment]
was my fault had a bad filter implementation

**Comment by vanniktech** [comment]
I'm having this again with version `0.14.0`:

The following dependencies exceed the version found at the milestone revision level:
 - com.vanniktech:gradle-android-apk-size-plugin [0.3.0 <- 0.1.1]
 - com.vanniktech:gradle-android-junit-jacoco-plugin [0.5.0 <- 0.2.0]
 - net.ltgt.gradle:gradle-errorprone-plugin [0.0.9 <- 0.0.6]
 - com.squareup.leakcanary:leakcanary-android [1.5 <- 1.3.1]
 - com.squareup.leakcanary:leakcanary-android-no-op [1.5 <- 1.3.1]
 - io.reactivex.rxjava2:rxjava [2.0.6 <- 2.0.1]

**Comment by ben-manes** [comment]
Gradle's plugin repository is broken and they ignore requests to fix it....

You need to add central and jcenter, as one might hold old versions. We use whatever repositories are in your configuration and don't add others.

**Comment by vanniktech** [comment]
Thanks that seems to have fixed the issue. Is there an issue that I can watch on Gradles site?

**Comment by ben-manes** [comment]
https://github.com/gradle/gradle/issues/1297
