### ISSUE TITLE
rejectVersionIf does not apply to gradle version

### ISSUE THREAD

**Issue by matejdro** [ben-manes/gradle-versions-plugin#722]
It seems like `Gradle release-candidate updates` are exempt from the `rejectVersionIf`. From what I can see, config does not even get called for gradle version.

This results in plugin telling us to update gradle to RC versions, such as `8.0-rc-2`, even though we have explicitly told the plugin to ignore everything that contains "rc".

**Comment by ben-manes** [comment]
yes, Gradle does not use a maven or ivy repository for itself so a resolutionStrategy does not apply. Instead you can simply set the [release channel](https://github.com/ben-manes/gradle-versions-plugin#gradle-release-channel) for those queries.

**Comment by matejdro** [comment]
Thanks, I totally missed that.
