### ISSUE TITLE
Only locally available included builds are shown as unresolved

### ISSUE THREAD

**Issue by Vampire** [ben-manes/gradle-versions-plugin#725]
I have build `A` with an included build `build-logic` that is a purely local included build without a published release.
The report show this as
```plain
Failed to determine the latest version for the following dependencies (use --info for details):
 - null:build-logic
The exception that is the cause of unresolved state: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find any matches for null:build-logic:+ as no versions of null:build-logic are available.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/null/build-logic/maven-metadata.xml
Required by:
    project :
```

If such a dependency that has no version available at all is coming from an included build, then it would be nice if it would not be shown as unresolved, but probably as up-to-date or not at all.

**Comment by ben-manes** [comment]
I would guess that we’d need to filter not just for ExternalDependency, but also exclude ExternalModuleDependency. Otherwise we think it is a BOM supplied version which is dynamically determined.

**Comment by Vampire** [comment]
Maybe you misunderstood me.
I was not talking about whether the declared dependeny has a version.
I meant when you tried to get the latest version using the `+` version and get no result at all.
Then, and if the dependency is served by an included build, it should be ignored as it is a purely local build organization dependency and not something published that could be updated.

**Comment by ben-manes** [comment]
I figured if we could simply not query for included build dependencies then that would solve the problem. We don't query for project dependencies and this is similar. My guess was that to detect if this is an included build we'd need to see if it was a `ExternalModuleDependency`, but I could be wrong. Otherwise we could probably ignore if the coordinate has a null value in either its group or artifactId properties. If you could provide a sample project then I can try to make a fix over the weekend.

**Comment by Vampire** [comment]
I don't know the Gradle internals there, but I guess it is not that trivial.
Usually those dependencies are external module dependencies that are substituted by the result of a project in an included build.
But it could of course be represented differently internally, I don't know.
`null` in the artifact is not possible I think.
And `null` in the group is not really meaningful, in my example it was `null`, but it could as well be set.

**Comment by Vampire** [comment]
You can use the branch `foo` of https://github.com/Vampire/setup-wsl to play with my concrete use-case.
But as I said, `group` being not set it not necessarily the case.
If you set a `group` for those included builds, the `group` should be set too.

**Comment by ben-manes** [comment]
Thanks! For context we get the dependency set like so. I’m guessing we can add another filter clause.

https://github.com/ben-manes/gradle-versions-plugin/blob/ad0ce46e3e1f880a4d7300eafd775e289929da7d/gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Resolver.kt#L95-L99

**Comment by Vampire** [comment]
Yep, my suspicion was correct.
Will send a PR soon that fixes it.
With that it will not fail on unresolved but instead treat them as hidden.

**Comment by ben-manes** [comment]
Released in v46
