### ISSUE TITLE
Example of outputFormatter with Closure

### ISSUE THREAD

**Issue by davidjohansson** [ben-manes/gradle-versions-plugin#74]
Docs say it should be possible to pass a closure, but can't make it work. An example would be much appreciated.

**Comment by ben-manes** [comment]
This was a contributed feature when I was inactive from the project for a while, so I'm not sure myself. There is a [unit test](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy#L294) which hints a little at how it might work.

The reporting needs to be rewritten as its a bit of a mess, imho. I was hoping to do that after I further improved the resolution logic, but haven't had the time recently to work on the plugin.

**Comment by ben-manes** [comment]
I suspect its something like `tasks.dependencyUpdates.outputFormatter = ...` but I haven't tried it yet.

**Comment by jochenberger** [comment]
I added that and yes, I should have added some docs. Shame on me...
I usually use
```groovy
dependencyUpdate.outputFormatter = { com.github.benmanes.gradle.versions.reporter.result.Result result ->
  def updatable = result.outdated.dependencies
  if (!updatable.isEmpty()){
    println "> $projectName:"
    updatable.each { dep-> println "> ${dep.group}:${dep.name}: ${dep.version} -> ${dep.available.release ?: dep.available.miles
tone}" }
  }
}
```

**Comment by davidjohansson** [comment]
Ok, got it. Thanks!

**Comment by jochenberger** [comment]
No, you're right, this needs some clarification in the docs, I'll reopen this.

**Comment by davidjohansson** [comment]
Ok, great.

**Comment by x2on** [comment]
Is it possible to use the Closure and a Json `outputFormatter` together?

**Comment by ncd7** [comment]
was there an answer to this (using a closer with a json or xml formatter)? thx
