### ISSUE TITLE
[Feature Request] - Check Gradle Wrapper Version

### ISSUE THREAD

**Issue by jaredsburrows** [ben-manes/gradle-versions-plugin#76]
I use this plugin in all of my android apps and Gradle projects.

<pre>
$ tree gradle
gradle
`-- wrapper
    |-- gradle-wrapper.jar
    `-- gradle-wrapper.properties
</pre>

Can we add support to check for the latest Gradle version?

**Comment by ben-manes** [comment]
It looks doable. The gradle distributions are not provided in a maven / ivy repository, so special handling of the [json routes](https://services.gradle.org/) would be required. The `release`, `milestone`, and `integration` revision types could be mapped to the distribution's `current`, `release candidate`, `nightly` revision types.

**Comment by jaredsburrows** [comment]
@ben-manes Something like this: https://github.com/gradle/gradle/blob/ecb669edb1af1804e91eada92d123256ebb97fc8/gradle/wrapper.gradle#L17.

It works great:
```
Wrapper tasks
-------------
currentWrapper
nightlyWrapper
rcWrapper
```

Try copying to your build and running: `gradlew currentWrapper`.

**Comment by ben-manes** [comment]
I don't think we'd want to generate the wrapper. That's built in, e.g.
`gradle wrapper --gradle-version 2.14`

I would think instead that we would want to display the version in the report (not sure if that should be in its own section or not). We'd fetch the version using those routes, query `gradle.gradleVersion`, and perhaps use the version comparator rather than a equality check (if we want to show release candidates).

I agree it should be fairly simple and a nice enhancement.

**Comment by jaredsburrows** [comment]
@ben-manes Yeah. I am just showing how the Gradle team does it in order to update their local gradle. Since it can update it, we know the version, we can just print out the version.

**Comment by jaredsburrows** [comment]
@ben-manes Something like this:
```
task("gradleUpdates") {
    group = "wrapper"
    ["nightly": "nightly",
     "rc"     : "release-candidate",
     "current": "current"].each {
        def label = it.value
        def version = new groovy.json.JsonSlurper().parseText(new URL("https://services.gradle.org/versions/${label}").text)
        if (version.empty) {
            throw new GradleException("Cannot update wrapper to '${label}' version as there is currently no version of that label")
        }
        println "${label} version: ${version.version} (downloadUrl: ${version.downloadUrl})"
    }
}
```

Command line:
```
$ gradlew gradleUpdates
```

Output:
```
$ gradle gradleUpdates
nightly version: 3.0-20160709000018+0000 (downloadUrl: https://services.gradle.org/distributions-snapshots/gradle-3.0-20160709000018+0000-bin.zip)
release-candidate version: 2.14.1-rc-1 (downloadUrl: https://services.gradle.org/distributions/gradle-2.14.1-rc-1-bin.zip)
current version: 2.14 (downloadUrl: https://services.gradle.org/distributions/gradle-2.14-bin.zip)
Incremental java compilation is an incubating feature.
:gradleUpdates UP-TO-DATE

BUILD SUCCESSFUL

Total time: 1.592 secs
```

**Comment by jaredsburrows** [comment]
@ben-manes Any update on this? We can tie these few lines of code into when we call `$ gradlew dependencyUpdates`?

**Comment by jaredsburrows** [comment]
@ben-manes any update?

**Comment by ben-manes** [comment]
Sorry, I haven't been actively working on this plugin other than keeping it compatible across Gradle releases. We'd probably want to tie this in as a new report section. You could send a PR if you're up for it.

**Comment by vanniktech** [comment]
@jaredsburrows what's the take on this? I'm seeing you're also active here and we could find a way to make it work.

**Comment by jaredsburrows** [comment]
@vanniktech This feature? Yeah, sorry I just keep getting sidetracked, I need to make PR for this.

**Comment by jaredsburrows** [comment]
Hey guys, sorry for the wait and thanks for keeping this open.

I am going to work on this. @ben-manes You mentioned in a previous comment that you want a separate reporter? Reuse the existing interface or create a 1-off reporter for this?

I am thinking we keep the report simple by printing our the latest release, something like: 
```
- Gradle [4.5 -> 4.6]
```

**Comment by ben-manes** [comment]
Yeah, sounds good.

**Comment by Vampire** [comment]
Just for the sake of correctness, you are checking the Gradle version, not the wrapper version.
Just in case it makes it into the output somehow. 
The "wrapper version" would be the version of the `gradle-wrapper.jar`, so basically the version of Gradle with which the `wrapper` task was called.
This is basically unrelated to the version defined in `gradle-wrapper.properties` which is the version that is downloaded and run by the wrapper. 

It would be really cool if actually also the wrapper version could be checked, not only the Gradle version, as you can update the Gradle version by simply editing the properties file without ever running the `wrapper` task to actually update the wrapper.

**Comment by jaredsburrows** [comment]
I have an issue for this already.

**Comment by Vampire** [comment]
"this" being what?

**Comment by aaronols** [comment]
@Vampire There are two issues related to gradle version checking in this project created by @jaredsburrows.
The older one is this current thread (titled "Check Gradle Wrapper Version") which is still unresolved and contains discussion about checking the version of Gradle itself, not the Wrapper.
Then there is a "newer" issue https://github.com/ben-manes/gradle-versions-plugin/issues/110 (almost two years old) that asks for checking the version of Gradle itself but got closed with a hint at this issue.

Anyways, I am very interested to see the gradle version check and I would also like to see the wrapper version check making it into the plugin.

**Comment by aaronols** [comment]
Is @jaredsburrows still working on this? Otherwise I can attempt to implement this too in a manner suggested in https://github.com/ben-manes/gradle-versions-plugin/issues/76#issuecomment-372006615.

**Comment by jaredsburrows** [comment]
Sorry. I have been busy lately. Feel free to take a crack at it if you want to get this feature in!

**Comment by aaronols** [comment]
I went ahead and implemented this in a simple manner (see the referenced pull request above).
There are still a few things open to discuss/change so feedback and further input is welcome.

**Comment by ben-manes** [comment]
Rebased and merged, thanks!
