### ISSUE TITLE
CVEs for xstream 1.4.19

### ISSUE THREAD

**Issue by zi4k4j74yn** [ben-manes/gradle-versions-plugin#765]
xstream has some vulnerabilities which have been fixed in 1.4.20 (https://x-stream.github.io/changes.html).

**Comment by ben-manes** [comment]
That is a deserialization attack, we are serializing to xml which is very safe. The upgrade is in master (https://github.com/ben-manes/gradle-versions-plugin/pull/751) and you can use version constraints to manage transitives in your build, so nothing is needed for now.
