### ISSUE TITLE
consider to report about time to migrate

### ISSUE THREAD

**Issue by nagkumar** [ben-manes/gradle-versions-plugin#772]
![image](https://user-images.githubusercontent.com/332234/234532440-aaccaa39-600d-4ba6-a213-fce6b5e9ac0e.png)

In this JUnit 4.x is used, can this plugin also consider discovering and say Junit 5 is x years old, and code needs to be migrated  as JUnit 4 is no more maintained..

Not with just Junit 4 but with any others that are deprecated or going out of scope etc..

Just a suggestion to consider not sure how feasible it is..

Few Inputs to this regard are

Maven does report with few if they are deprecated & outdated

https://mvnrepository.com/search?q=deprecated
https://mvnrepository.com/search?q=outdated

Also from the date of publishing if it is more than x configurable years etc..and/or github activity in the last few weeks etc..

I really like your plugin, lot of scope to be part of every grade project by default.

**Comment by ben-manes** [comment]
hey @nagkumar, it seems [libyear](https://github.com/f4lco/libyear-gradle-plugin) does exactly what you wanted.
