### ISSUE TITLE
Configuration cache problems because of using Project object in task

### ISSUE THREAD

**Issue by WebTiger89** [ben-manes/gradle-versions-plugin#777]
Hi,
just wanted to report that when running the `depedencyUpdates` Task, I get those warnings:

> 663 problems were found storing the configuration cache, 9 of which seem unique.
> - Plugin 'com.android.internal.application': execution of task ':dependencyUpdatesStable' caused invocation of 'Task.convention' in > other task at execution time which is unsupported.
>   See https://docs.gradle.org/8.1.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
> - Plugin 'com.android.internal.application': execution of task ':dependencyUpdatesStable' caused invocation of 'Task.project' in other > task at execution time which is unsupported.
>   See https://docs.gradle.org/8.1.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
> - Plugin 'com.android.internal.library': execution of task ':dependencyUpdatesStable' caused invocation of 'Task.project' in other task > at execution time which is unsupported.

I'm not sure when it started to occur. I updated Android Studio to Hedgedog and AGP to 8.2.0-alpha02.

**Comment by ben-manes** [comment]
The configuration cache is very noisy and warns when nothing is wrong. This plugin's task calls `notCompatibleWithConfigurationCache` to inform Gradle that the task is not compatible and not use the cache for that execution. This is what their docs recommend, but as they work through making this cache stable they decided to be very noisy about any incompatibility regardless whether the cache is in use or not. I expect in 8.3 or so it will be quiet again as the team gets confidence in this feature. You can run with `-q` or `--quiet` to suppress this spam.

**Comment by WebTiger89** [comment]
ok sounds legit, then I will wait. If you don't see any need for action on this you can close it :)
