### ISSUE TITLE
Gradle 8 errors

### ISSUE THREAD

**Issue by jimshowalter** [ben-manes/gradle-versions-plugin#800]
Upgrading to Gradle 8 and running dependencyUpdates generates this output:

`- Task `:dependencyUpdates` of type `com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask`: cannot serialize a lambda that captures or accepts a parameter of type 'org.gradle.api.artifacts.Configuration' as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.2.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:dependencyUpdates` of type `com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask`: execution of task ':dependencyUpdates' caused invocation of 'Task.convention' in other task at execution time which is unsupported.
  See https://docs.gradle.org/8.2.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:dependencyUpdates` of type `com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask`: execution of task ':dependencyUpdates' caused invocation of 'Task.project' in other task at execution time which is unsupported.
  See https://docs.gradle.org/8.2.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
- Task `:dependencyUpdates` of type `com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.2.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
`

Note: To see this, you may need to add this to gradle.properties:

`org.gradle.configuration-cache=true`

**Comment by jimshowalter** [comment]
Oh, thank you!

**Comment by ben-manes** [comment]
oh I'm wrong on 8.3. I thought they fixed https://github.com/gradle/gradle/issues/24435, but `-q` works like a charm so I just use that.
