### ISSUE TITLE
Possible to restrict what maven repositories are used?

### ISSUE THREAD

**Issue by rcolombo** [ben-manes/gradle-versions-plugin#806]
I only want this plugin to scan https://repo1.maven.org/maven2/. Is this possible?

**Comment by ben-manes** [comment]
sure, just remove all the other repositories in a `doFirst` action, e.g.

```gradle
tasks.dependencyUpdates.doFirst {
  repositories.clear()
  repositories {
    mavenCentral()
  }
}
```

Alternatively, you might use repository content filtering to avoid scanning the wrong repositories if you are trying to speed up the queries.

**Comment by rcolombo** [comment]
Thank you!
