### ISSUE TITLE
Any way of explicitly just telling the plugin to ignore one dependency?

### ISSUE THREAD

**Issue by liminal** [ben-manes/gradle-versions-plugin#81]
The plugin will always tell me that the jsr250-api final version isn't the latest version because of the weird naming and I'm thinking there's not going to be any more updates to that particular jar ever so it would be nice to be able to just stop getting info about it

`javax.annotation:jsr250-api [1.0 -> 1.0-20050927.133100]`

**Comment by ben-manes** [comment]
I think if you use a version range syntax it should honor that. Alternatively resolutionStrategy is also honored, so you could specify that to restrict the upper bound.

**Comment by ben-manes** [comment]
Closing, as a `resolutionStrategy` is the correct fix.
