### ISSUE TITLE
Unsupported feature "indent-number"

### ISSUE THREAD

**Issue by baron1405** [ben-manes/gradle-versions-plugin#818]
The `indent-number` is not a supported feature in all XML transformers and causes the dependencyUpdates task to fail with:
```
Unrecognized configuration feature: indent-number
```
Simply remove the call to set this feature and go with the default indentation.

https://github.com/ben-manes/gradle-versions-plugin/blob/d56bbc9eb62d738ba2af2d54860e466c9e66f163/gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/XmlReporter.kt#L43

**Comment by ben-manes** [comment]
oh thanks. if this is causing trouble we can get a release out or you could specify the JVM to prefer the native transformer in your gradle.properties. The older xml providers are not compatible due to security restrictions in Gradle 8.4 onward.

**Comment by baron1405** [comment]
Thanks for the quick reply! I would appreciate a release with the feature setting removed. Thanks for this great plugin!

**Comment by ben-manes** [comment]
Sorry, got held up with family and things. I'll cut a release with this fix, thanks!

**Comment by baron1405** [comment]
Thanks for the quick release. I can confirm that the new release fixes the problem.
