### ISSUE TITLE
gradle plugins version didn't updated

### ISSUE THREAD

**Issue by flshbt** [ben-manes/gradle-versions-plugin#819]
Hi, 

version update of normal project deplencies running fine, but using (toml declarted) plugins and version, do not update to the latest stable version. Is there a special trick or is it a bug?

Configuration is the default config from the documentation.

best reguards

**Comment by ben-manes** [comment]
I use toml in [Caffeine](https://github.com/ben-manes/caffeine) and there is the [version-catalog-update-plugin](https://github.com/littlerobots/version-catalog-update-plugin) as well.

If you use the includeBuild trick for script plugins that forces you to run the task on the two projects, since Gradle treats them as distinct. Otherwise I’m not sure what you might be seeing.

**Comment by flshbt** [comment]
And this trick will be increase the plugin versions in the libs.toml? I must be allways increase the plugin versions manually.

`
[versions]
plugin-gradle-versions = "0.47.0"
plugin-kotlin-version = "1.9.20"
plugin-nebula-publish = "20.3.0"
plugin-nebula-release = "17.2.2"
plugin-version-catalog = "0.8.1"

[libraries]
... some libs

[plugins]
plugin-gradle-versions = { id = "com.github.ben-manes:gradle-versions-plugin", version.ref = "plugin-gradle-versions" }
plugin-kotlinus-jvm = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "plugin-kotlin-version" }
plugin-nebula-publish = { id = "com.netflix.nebula:nebula-publishing-plugin", version.ref = "plugin-nebula-publish" }
plugin-nebula-release = { id = "com.netflix.nebula:nebula-release-plugin", version.ref = "plugin-nebula-release" }
plugin-version-catalog = { id = "nl.littlerobots.vcu:plugin", version.ref = "plugin-version-catalog" }
`

**Comment by ben-manes** [comment]
That additional plugin will. This one only generates a report as dependency management was fairly scattered and inconsistent in Gradle. This plugin is not opinionated, we left that to others to define the workflow
