### ISSUE TITLE
[2.0.31-beta -> 2.0.31-beta]

### ISSUE THREAD

**Issue by ligi** [ben-manes/gradle-versions-plugin#84]
the following output makes no sense to me:

The following dependencies have later milestone versions:
 - org.mockito:mockito-core [2.0.31-beta -> 2.0.31-beta]

**Comment by ben-manes** [comment]
Sorry, that's been fixed on `master` for a while now. I haven't had the time or focus to catch up on the backlog of issues and push a new release.

**Comment by ben-manes** [comment]
Closing, as fixed and will be released soon.
