### ISSUE TITLE
outputFormatter setting has no effect - json, xml & txt report always generated

### ISSUE THREAD

**Issue by joloto** [ben-manes/gradle-versions-plugin#846]
Hello,

firstly thanks for this plugin. I am trying it out (latest version 0.51.0) but always get the same report types, however I try to configure the `outputFormatter` setting.

I have also experimented using the commandline setting, i.e.: `gradle dependencyUpdates -DoutputFormatter=html`

Here my example Gradle task configuration:
```
dependencyUpdates {

    checkForGradleUpdate = false
    revision = 'release'
    outputFormatter = 'html'

    rejectVersionIf {
        isNonStable(it.candidate.version)
    }
}
```

Attached a sample project (tried executed with both Gradle 8.5 & 8.6), including the output reports in the build folder.
[test-app.zip](https://github.com/ben-manes/gradle-versions-plugin/files/14525824/test-app.zip)

The output always shows the generation of json, xml & txt reports as shown below.

<img width="1239" alt="gradle_dependencyUpdates" src="https://github.com/ben-manes/gradle-versions-plugin/assets/6827206/f5645275-e2c7-40ba-8fb9-8910bf5f8e19">

Thanks in advance for your assistance.

**Comment by ben-manes** [comment]
It looks like this is from `se.patrikerdes.use-latest-versions` which [forces](https://github.com/patrikerdes/gradle-use-latest-versions-plugin/blob/57a402a8ed287914edffc8556ca7491a0a557ec0/src/main/groovy/se/patrikerdes/UseLatestVersionsPlugin.groovy#L17) the output formatter.

```groovy
    void apply(Project project) {
        System.setProperty('outputFormatter', 'json,xml,plain')
        Task rootAggregate = setupRootAggregateTask(project)
        setupUseLatestVersions(project, rootAggregate)
        setupUseLatestVersionsCheck(project)
    }
```

**Comment by joloto** [comment]
Wow thank you very much for this information.
