### ISSUE TITLE
Change JDK 8-provider

### ISSUE THREAD

**Issue by sdavids** [ben-manes/gradle-versions-plugin#853]
https://github.com/ben-manes/gradle-versions-plugin/blob/438cbb5cc6ab62c8204c9bb73fbf9c72fa22daf0/.sdkmanrc#L3

Temurin does not provide a macOS/aarch64 JDK 8: https://adoptium.net/temurin/releases/?os=mac&arch=aarch64&version=8

I suggest switching to BellSoft Liberica JDK which is used by the Spring Boot framework: https://bell-sw.com/pages/downloads/?version=java-8&os=macos&architecture=arm

**Comment by ben-manes** [comment]
thx!
