### ISSUE TITLE
Deprecation warnings for some classpaths

### ISSUE THREAD

**Issue by jimshowalter** [ben-manes/gradle-versions-plugin#858]
Gradle 8.7 reports:

> Task :xyz:dependencyUpdates
The compileClasspathCopy configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 9.0. Please use another configuration instead. For more information, please refer to https://docs.gradle.org/8.7/userguide/declaring_dependencies.html#sec:deprecated-configurations in the Gradle documentation.
The compileClasspathCopy2 configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 9.0. Please use another configuration instead. For more information, please refer to https://docs.gradle.org/8.7/userguide/declaring_dependencies.html#sec:deprecated-configurations in the Gradle documentation.
The runtimeClasspathCopy configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 9.0. Please use another configuration instead. For more information, please refer to https://docs.gradle.org/8.7/userguide/declaring_dependencies.html#sec:deprecated-configurations in the Gradle documentation.
The runtimeClasspathCopy2 configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 9.0. Please use another configuration instead. For more information, please refer to https://docs.gradle.org/8.7/userguide/declaring_dependencies.html#sec:deprecated-configurations in the Gradle documentation.
Calling configuration method 'copyRecursive()' is deprecated for configuration 'signatures', which has permitted usage(s):
        Consumable - this configuration can be selected by another project as a dependency
        Resolvable - this configuration can be resolved by this project to a set of files (but this behavior is marked deprecated)
        Declarable - this configuration can have dependencies added to it (but this behavior is marked deprecated)
This method is only meant to be called on configurations which allow the (non-deprecated) usage(s): 'Resolvable'. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.7/userguide/upgrading_version_8.html#deprecated_configuration_usage
Calling configuration method 'getResolvedConfiguration()' is deprecated for configuration 'signaturesCopy', which has permitted usage(s):
        Consumable - this configuration can be selected by another project as a dependency
        Resolvable - this configuration can be resolved by this project to a set of files (but this behavior is marked deprecated)
        Declarable - this configuration can have dependencies added to it (but this behavior is marked deprecated)
This method is only meant to be called on configurations which allow the (non-deprecated) usage(s): 'Resolvable'. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.7/userguide/upgrading_version_8.html#deprecated_configuration_usage
The signaturesCopy configuration has been deprecated for resolution. This will fail with an error in Gradle 9.0. Please resolve another configuration instead. For more information, please refer to https://docs.gradle.org/8.7/userguide/declaring_dependencies.html#sec:deprecated-configurations in the Gradle documentation.
The testCompileClasspathCopy configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 9.0. Please use another configuration instead. For more information, please refer to https://docs.gradle.org/8.7/userguide/declaring_dependencies.html#sec:deprecated-configurations in the Gradle documentation.
The testCompileClasspathCopy2 configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 9.0. Please use another configuration instead. For more information, please refer to https://docs.gradle.org/8.7/userguide/declaring_dependencies.html#sec:deprecated-configurations in the Gradle documentation.
The testRuntimeClasspathCopy configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 9.0. Please use another configuration instead. For more information, please refer to https://docs.gradle.org/8.7/userguide/declaring_dependencies.html#sec:deprecated-configurations in the Gradle documentation.
The testRuntimeClasspathCopy2 configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 9.0. Please use another configuration instead. For more information, please refer to https://docs.gradle.org/8.7/userguide/declaring_dependencies.html#sec:deprecated-configurations in the Gradle documentation.

**Comment by ben-manes** [comment]
Take a look at #850. It's merely that we evaluate the legacy configurations by default, which you can opt out of. When Gradle removes them then they won't be picked up by the dynamic scan. So it is ignorable or easy to suppress client-side.
