### ISSUE TITLE
Failed to determine the latest version for dependencies from clojars.org

### ISSUE THREAD

**Issue by jbaginski** [ben-manes/gradle-versions-plugin#87]
https://github.com/frankiesardo/icepick

**Comment by ben-manes** [comment]
Can you try adding a `name` to your repository? There is a bug in Gradle's repository deduping. I think that will fix it and maybe over the holidays I'll be able to get through the backlog here.

```gradle
maven {
  name 'jitpack'
  url 'https://clojars.org/repo/'
}
```

**Comment by jbaginski** [comment]
thanks @ben-manes. that solves my issue XD

**Comment by ben-manes** [comment]
Great! The next version will stop aggregating repositories as there's no way to workaround this issue and the Gradle team has higher priorities than to fix it. I'm hoping that for most users this shouldn't be a noticeable change.
