### ISSUE TITLE
"Failed to determine the latest version" list contains duplicates.

### ISSUE THREAD

**Issue by huxi** [ben-manes/gradle-versions-plugin#91]
The list below "Failed to determine the latest version for the following dependencies (use --info for details):" contains duplicate entries.

**Comment by ben-manes** [comment]
Experimenting and it seems that this bug existed in the prior version as well. The unresolved list is stored in a `SortedSet` which I thought would have been enough to avoid duplicates.

**Comment by ben-manes** [comment]
This seems to have been a bug in the reporting logic by taking the raw list of unresolved instead of a set.
