### ISSUE TITLE
Checkstyle and jacoco toolVersion support?

### ISSUE THREAD

**Issue by henrik242** [ben-manes/gradle-versions-plugin#92]
Is it possible to check for upgrades to checkstyle and jacoco toolVersion?

```
apply plugin: 'checkstyle'
apply plugin: 'jacoco'

jacoco.toolVersion = '0.7.4.201502262128'
checkstyle.toolVersion = '6.14.1'
```

**Comment by ben-manes** [comment]
Yes its possible, but results in confusing report entries. The task [detects and hides](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L79) internal dependencies, so removing that check would be trivial.

If the tool versions was shown then the report would contain an entry like,
```
The following dependencies are using the latest milestone version:
 - org.jacoco:org.jacoco.agent:0.7.1.201405082137
 - org.jacoco:org.jacoco.ant:0.7.1.201405082137
```

Perhaps these should be a separate tool section for this and the gradle version (#76)?

**Comment by frmz** [comment]
I have the opposite issue actuall, I am seeing Jacoco in the report and i am not using it explicitly

The following dependencies have later milestone versions:
 - org.jacoco:org.jacoco.agent [0.7.4.201502262128 -> 0.7.9]
 - org.jacoco:org.jacoco.ant [0.7.4.201502262128 -> 0.7.9]

Should it be hidden?

**Comment by ben-manes** [comment]
Yes, it has been for me. Do you have a public build or a small sample? I'd have to look later, but don't recall experiencing it with the latest Gradle releases (in case my hiding broke).

**Comment by frmz** [comment]
No, it started a few weeks ago actually, i will try to debug this

**Comment by ben-manes** [comment]
Can you try running `gradle dependencyInsight --dependency org.jacoco`? That should show any direct or transitive dependency unless the only usage is hidden. When I run the tasks on a project without that dependency, neither the report or insight task show it.

It could be that a plugin you use also included it for some reason. I think the insight task should show that.

**Comment by frmz** [comment]
It gives no result:
```
:dependencyInsight
No dependencies matching given input were found in configuration ':compileClasspath'
```

**Comment by bhb27** [comment]
I also see the bellow on the report:

	The following dependencies have later milestone versions:
	 - org.jacoco:org.jacoco.agent [0.7.4.201502262128 -> 0.7.9]
	 - org.jacoco:org.jacoco.ant [0.7.4.201502262128 -> 0.7.9]

but none of my plugging or dependency use it. if there is a workaround to exclude it, please let me know how to.

**Comment by ben-manes** [comment]
Can you provide a build file that demonstrates this? I haven't encountered the problem and it should be hidden (see prior comment).

**Comment by bhb27** [comment]
What do you mean with a build file? the apk

**Comment by ben-manes** [comment]
A minimal project displaying the problem that we can debug with.

**Comment by bhb27** [comment]
Sorry but I may still be lost...

the project is this
https://github.com/bhb27/isu/blob/master/app/build_Isu.sh
I use that .sh to build

"greping" jacoco e get this

	Binary file app/build/intermediates/transforms/desugar/release/8.jar matches
	Binary file app/build/intermediates/transforms/desugar/debug/8.jar matches
	Binary file app/build/intermediates/transforms/stackFramesFixer/release/7.jar matches
	Binary file app/build/intermediates/transforms/stackFramesFixer/debug/7.jar matches
	build/dependencyUpdates/report.txt: - org.jacoco:org.jacoco.agent [0.7.4.201502262128 -> 0.7.9]
	build/dependencyUpdates/report.txt: - org.jacoco:org.jacoco.ant [0.7.4.201502262128 -> 0.7.9]

Don't know if that helps...please advise if that is not what you need

**Comment by bhb27** [comment]
maybe the files help
https://github.com/bhb27/scripts/tree/master/temp/randomfiles

**Comment by ben-manes** [comment]
Thanks, the project should work. I didn't know it was open-sourced and small. I cloned it and see the lines in the report, so now we have something to debug with. I'm not sure when @jochenberger or I will have the time to take a look.

The Android plugins tend to screw with Gradle's internals such that it interacts very weirdly at times. They do not conform to Gradle idioms and instead hack it in ways that cause very frustrating, brittle behavior. In the debug logs I see that the dependencies are due to the `androidJacocoAgent` configuration. My initial assumption is that it another Android hack rather than follow the patterns the Gradle team laid out, resulting in the dependency leak.

**Comment by bhb27** [comment]
I appreciate the work, for me this is not a big of a deal I really like this plugin...

If I find something I post here I will dig further on this...

On the mean time do you have a sample function like "dependencyUpdates.resolutionStrategy" so I can disable this check?

**Comment by ben-manes** [comment]
You could reject the dependency in a `resolutionStrategy`, but it would then be listed in another section as unresolvable. I don't think there is an easy way to suppress it.

**Comment by bhb27** [comment]
OK, I will try to understand better from were this comes from then, if I find something I post here, will probably take some time on my end...

Thanks for the support, and the great plunging :+1:

**Comment by bhb27** [comment]
OK not a fix just a workaround answer to my previously question **"On the mean time do you have a sample function like "dependencyUpdates.resolutionStrategy" so I can disable this check?"**

As I'm using linux and shell .sh to build and to get the result from **dependencyUpdates**, the easy way is to use the bellow

	./gradlew dependencyUpdates  | sed '/jacoco/d'

Works as a temp workaround... will keep searching about the real couse of this...

**Comment by ben-manes** [comment]
Oh, that's great. The real cause is the Android plugin's `androidJacocoAgent` configuration.

In the [source](https://android.googlesource.com/platform/tools/base/+/9fba95348ef762fd9a7c82ac332d119684a74bcb/build-system/gradle/src/main/groovy/com/android/build/gradle/internal/coverage/JacocoPlugin.groovy), that is marked as `visible = false`. So maybe we should skip the evaluation of invisible configurations?

Thoughts @jochenberger?

**Comment by jochenberger** [comment]
Sounds reasonable. I thought that this would probably also help us get rid of update notifications for `springloaded` (when the `gretty` plugin is used), but unfortunately, the [respective configuration](https://github.com/akhikhl/gretty/blob/28d24aa03e59c190dc19f97f9276754badebae03/libs/gretty/src/main/groovy/org/akhikhl/gretty/GrettyPlugin.groovy#L47) *is* visible.
But we could also add a configuration option for configurations whose dependencies we don't want to check. That would require additional configuration but it would probably also cover more use cases.
By the way, I must admit that I don't understand how the [current filter approach](https://github.com/ben-manes/gradle-versions-plugin/blob/v0.15.0/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L78) works. Maybe we could take that as an indicator that the code in that area deserves a comment. ;-)

**Comment by jaredsburrows** [comment]
@ben-manes is correct. If you run `gradlew dependencies` on an Android project for example, adding the android gradle plugin adds Jacoco to the configurations added by the plugin itself.

Since @ben-manes's `gradle-versions-plugin` is to find newer versions of dependencies, I believe this plugin is doing it's job correctly.

```
$ gradlew dependencies

> Task :dependencies 

------------------------------------------------------------
Root project
------------------------------------------------------------

androidJacocoAgent - The Jacoco agent to use to get coverage data.
\--- org.jacoco:org.jacoco.agent:0.7.4.201502262128

androidJacocoAnt - The Jacoco ant tasks to use to get execute Gradle tasks.
\--- org.jacoco:org.jacoco.ant:0.7.4.201502262128
     +--- org.jacoco:org.jacoco.core:0.7.4.201502262128
     |    \--- org.ow2.asm:asm-debug-all:5.0.1
     +--- org.jacoco:org.jacoco.report:0.7.4.201502262128
     |    +--- org.jacoco:org.jacoco.core:0.7.4.201502262128 (*)
     |    \--- org.ow2.asm:asm-debug-all:5.0.1
     \--- org.jacoco:org.jacoco.agent:0.7.4.201502262128

(*) - dependencies omitted (listed previously)

(n) - Not resolved (configuration is not meant to be resolved)


BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
```
