### ISSUE TITLE
Output project url from pom

### ISSUE THREAD

**Issue by gabrielittner** [ben-manes/gradle-versions-plugin#94]
My usual steps when updating dependencies are:
1. check if there are new versions
2. go to project that was updated, to check changelog
3. update the dependency

This plugin makes step 1 and 3 are super easy and it would be nice if it could make step 2 almost as easy. Printing the project url of a changed dependency next to or below it would achieve that.

**Comment by ben-manes** [comment]
We use Gradle's dependency management to discover the updates. This lets us avoid explicitly making http calls, parsing poms, and other reinventions. This provides a lot of convenience, correctness, and is quite simple. That is especially nice because then handling other dependency types (such as ivy) and repository types (e.g. S3, https proxy) are handled for us.

To work cleanly with all of Gradle's dependency features, we'd want to access the downloaded pom in the cache (if there is one). Then we could parse for the project information. I suspect that isn't too hard, but experimenting with the Gradle API would be necessary. I don't want to include any hacks that bypass Gradle's mechanisms.

I probably won't get to this anytime soon. If it is something frustrating or that sounds fun, you might want to give it a shot.

**Comment by gabrielittner** [comment]
I found some time and looked in to it. There is `ArtifactResolutionQuery` which allows us to get the local pom and if there is one the parent pom. I've got a working version of `Resolver` that uses it to get the urls and will upload it after I cleaned it up tomorrow.

**Comment by ben-manes** [comment]
Sounds like a very clean approach :+1:

**Comment by gabrielittner** [comment]
Here is the current wip https://github.com/ben-manes/gradle-versions-plugin/compare/master...gabrielittner:pom-urls All found project urls are put into a Map inside `DependencyUpdatesReporter`, the part that is missing is putting it from there into the report.

**Comment by ben-manes** [comment]
Very nice!

The `DependencyUpdatesReporter` is a mess and needs an overhaul. Once it gets into the phase of printing the reports it gets clean again, though.

I'd move your additions into a helper class, named something like `ProjectFinder`, to help keep the size of `Resolver` in check. Actually there is probably a better name to to avoid `project` clash, perhaps `ExternalProjectFinder`? That would match better with Gradle's `ExternalDependency` type.

I'm not sure if anyone would expect Ivy lookups so we can add that later if ever requested. I think that would be as simple as adding `IvyDescriptorArtifact` to your query and extracting the [repository url](http://ant.apache.org/ivy/history/latest-milestone/ivyfile/repository.html) if it exists. I don't know Ivy's format, so I'm guessing that's the project's url.

We should also add tests with and without the project url to avoid surprises. The tests use a local repository (`src/test/resources/maven`) so hacking their poms would suffice.

**Comment by jaredsburrows** [comment]
@gabrielittner Any update on your progress? :)

**Comment by vanniktech** [comment]
How should we display this in our reports?

**Comment by vanniktech** [comment]
I've taken a look at the PR and it seems like most of the stuff is already implemented, we'd just need to adjust the reporting.

**Comment by gabrielittner** [comment]
I didn't have time to continue the PR back then and afterwards kind of forgot about it. The branch in my fork still is the current progress. I'll take a look at it next week unless you want to continue and write the reporting.

**Comment by gabrielittner** [comment]
I've added reporting. Here is what it looks like:

``` 
 - com.google.code.gson:gson [2.8.0 -> 2.8.2]
   https://github.com/google/gson
```
```json
  {
    "group": "com.google.code.gson",
    "available": {
      "release": null,
      "milestone": "2.8.2",
      "integration": null
    },
    "version": "2.8.0",
    "projectUrl": "https://github.com/google/gson",
    "name": "gson"
  }
```
```xml
  <outdatedDependency>
    <group>com.google.code.gson</group>
    <name>gson</name>
    <version>2.8.0</version>
    <available>
      <milestone>2.8.2</milestone>
    </available>
    <projectUrl>https://github.com/google/gson</projectUrl>
  </outdatedDependency>
```

Currently the plain text report will not print the url's for up to date dependencies. If that and the format are ok I'll add tests and open a PR.

**Comment by jaredsburrows** [comment]
Looks good so far!
