### ISSUE TITLE
Show newer versions per major version 

### ISSUE THREAD

**Issue by vanniktech** [ben-manes/gradle-versions-plugin#96]
For instance I'm using assertj. There are 3 major versions available (1, 2, 3).
- 1 targets Java 6
- 2 targets Java 7
- 3 targets Java 8

Problem is that on Android you can only really use version 1 of the library. When running the task though. I get this:

`org.assertj:assertj-core [1.7.1 -> 3.3.0]`

It'd be cool if this would be the output:

`org.assertj:assertj-core [1.7.1 -> UP TO DATE ; newer major versions: 2.3.0, 3.3.0]`

Another examples are the Google Support libraries. Stable version is `23.2.1` and for testing the new Android N preview they have `24.0.0-alpha1`. Hence I get `com.android.support:appcompat-v7 [23.1.1 -> 24.0.0-alpha1]` and don't know whether the `23` version I'm using is the latest `23` or not.

**Comment by ben-manes** [comment]
This seems to be a variation of #95 and #69. As with #95 the restriction to a particular major version can be achieved using a custom `resolutionStrategy`. The concern with providing breadcrumbs is the impact on performance, as Gradle resolves each dependency sequentially instead of in parallel.

**Comment by vanniktech** [comment]
Ups okay makes sense. Though is the 'performance' impact really what's holding those tickets / issues back? Usually you execute that task once or twice a week if you want to know whether there are any dependency updates or not.

**Comment by ben-manes** [comment]
Its my only hesitation and, until recently, was merely an idea rather than a requested feature. The main issue is finding the time to work on this project.

**Comment by vanniktech** [comment]
Should we somehow consolidate all of the similar reports into one issue?

We could also brainstorm which ways we might want to provide as everyone has a different idea on how this feature should work.

**Comment by ben-manes** [comment]
Sure. Unfortunately I am no longer actively working on this project, as it fulfills my needs, and focus on maintenance only. I have too much at work and another popular project to support. I would gladly provide guidance and commit access to anyone who is interested in further developing this plugin.

**Comment by vanniktech** [comment]
I'd be happy to triage / consolidate the issues and in the further continue working on the plugin with some assistance from your side.

**Comment by ben-manes** [comment]
Great, thank you.

I think that a likely strategy is to build multiple dynamic version ranges, e.g. [1.5.9.+], [1.5.+], [1.+], and [+]. Then resolve them into a `NavigableSet` using the [VersionComparator] for ordering. Assuming that Gradle queries and caches the entire metadata, this wouldn't have a significant performance penalty. The xml/json reports should stay backwards compatible, so the incremental upgrades should be new fields. Most of these changes would occur in [Resolver](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy) with minor changes to the reporting code.

Also note that you can use `gradlew install` to push into your local m2 repository. Then do ad hoc testing using the `example` build. We also have unit tests, which would help ensure backwards compatibility.

**Comment by vanniktech** [comment]
Thanks for the information.

I'll close this issue in favor of #69 and when implementing it I'll keep an eye on implementation hints.

**Comment by memelet** [comment]
Is there an example strategy around that implements this?

**Comment by G00fY2** [comment]
Here is an example implementation to only allow specific versions using the buildSrc feature I came up with: https://gist.github.com/G00fY2/480780e1dbab42fa0ed943d0ca7fb94f
